[Appearance]
color_scheme_path=@GUEST_QT6CT_COLORS@
custom_palette=true
icon_theme=Chicago95
standard_dialogs=default
style=Windows

[Interface]
menus_have_icons=false
dialog_buttons_have_icons=0
underline_shortcut=1
toolbutton_style=4
