music_directory     "~/HelmCortex/NADA"
playlist_directory  "~/HelmCortex/NADA"
db_file             "~/.local/state/mpd/database"
state_file          "~/.local/state/mpd/state"
sticker_file        "~/.local/state/mpd/sticker.sql"
log_file            "~/.local/state/mpd/mpd.log"
pid_file            "~/.local/state/mpd/pid"

bind_to_address     "127.0.0.1"
port                "6600"
auto_update         "yes"
restore_paused      "yes"
follow_outside_symlinks "yes"
follow_inside_symlinks  "yes"

audio_output {
    type            "pulse"
    name            "PulseAudio"
}
