# args
# Autogenerated from man page /usr/share/man/man1/args.1.gz
# using Deroffing man parser
complete -c args -l delim --description 'Set a deliminator character, such as \',\', to us… [See Man Page]'
complete -c args -l directory --description 'If argument is a directory, list directory cont… [See Man Page]'
complete -c args -l follow --description 'If argument is a directory and a symlink, follo… [See Man Page]'
complete -c args -l lines --description 'Output each argument on a separate line.'
complete -c args -l quote --description 'Set a quote or special leading and trailing pai… [See Man Page]'
complete -c args -l recursive --description 'If argument is a directory, recursively scan di… [See Man Page]'
complete -c args -l reverse --description 'Reverse order of arguments.'
complete -c args -l help --description 'Outputs help screen for the user.'

