# asciidoc
# Autogenerated from man page /usr/share/man/man1/asciidoc.1.gz
# using Deroffing man parser
complete -c asciidoc -s a -l attribute --description 'Define or delete document attribute.'
complete -c asciidoc -s b -l backend --description 'Backend output file format: docbook45, xhtml11,… [See Man Page]'
complete -c asciidoc -s f -l conf-file --description 'Use configuration file CONF_FILE.'
complete -c asciidoc -l doctest --description 'Run Python doctests in asciidoc module.'
complete -c asciidoc -s d -l doctype --description 'Document type: article, manpage or book.'
complete -c asciidoc -s c -l dump-conf --description 'Dump configuration to stdout.'
complete -c asciidoc -l filter --description 'Specify the name of a filter to be loaded (used… [See Man Page]'
complete -c asciidoc -s h -l help --description 'Print help TOPIC.'
complete -c asciidoc -s e -l no-conf --description 'Exclude implicitly loaded configuration files e… [See Man Page]'
complete -c asciidoc -s s -l no-header-footer --description 'Suppress document header and footer output.'
complete -c asciidoc -s o -l out-file --description 'Write output to file OUT_FILE.'
complete -c asciidoc -s n -l section-numbers --description 'Auto-number HTML article section titles.'
complete -c asciidoc -l safe --description 'Enable safe mode.  Safe mode is disabled by default.'
complete -c asciidoc -l theme --description 'Specify a theme name.  Synonym for --attribute theme=THEME.'
complete -c asciidoc -s v -l verbose --description 'Verbosely print processing information and conf… [See Man Page]'
complete -c asciidoc -l version --description 'Print program version number.'

