# avisplit
# Autogenerated from man page /usr/share/man/man1/avisplit.1.gz
# using Deroffing man parser
complete -c avisplit -s i --description 'Specify the filename of the file to split into chunks.'
complete -c avisplit -s o --description 'Specify the base of the output filename(s) avis… [See Man Page]'
complete -c avisplit -s s --description 'Use this option to specify the maximum size (in… [See Man Page]'
complete -c avisplit -s H --description 'Create only the first num chunks then exit.'
complete -c avisplit -s t --description 'Split the input file based on time/framecode (hh:mm:ss. ms).'
complete -c avisplit -s c --description 'Together with -t.'
complete -c avisplit -s m --description 'Together with -t.'
complete -c avisplit -s b --description 'Specify if avisplit should write an VBR mp3 hea… [See Man Page]'
complete -c avisplit -s f --description 'Read AVI tombstone data for header comments from commentfile.'
complete -c avisplit -s v --description 'Print only version information and exit.  EXAMPLES The command.'

