# car
# Autogenerated from man page /usr/share/man/man1/car.1.gz
# using Deroffing man parser
complete -c car -l cipher --description 'Specify symetric cipher.   By default 256 bit aes is used.'
complete -c car -l decrypt --description 'Specify decryption operation on an existing car stream or file.'
complete -c car -l digest --description 'Specify name of digest algorithm.'
complete -c car -l follow --description 'Dereference and follow symlinks.   Otherwise they are ignored.'
complete -c car -l output --description 'Specify output file for a new archive.'
complete -c car -l overwrite --description 'Always overwrite existing files without prompting.'
complete -c car -l quiet --description 'Non-interactive and no status output.'
complete -c car -l recursive --description 'If argument is a directory, recursively scan di… [See Man Page]'
complete -c car -l help --description 'Outputs help screen for the user.'

