# cdemu
# Autogenerated from man page /usr/share/man/man1/cdemu.1.gz
# using Deroffing man parser
complete -c cdemu -s h -l help --description 'Displays the help message.'
complete -c cdemu -s v -l version --description 'Prints version info and exits.'
complete -c cdemu -l bus --description 'option.'
complete -c cdemu -l 'password)' --description '.'
complete -c cdemu -s b --description 'Sets the D-BUS bus type to use for connection.'
complete -c cdemu -l password --description 'Allows a password for an encrypted image to be … [See Man Page]'
complete -c cdemu -l encoding --description 'Allows an encoding for text-based image format … [See Man Page]'
complete -c cdemu -l dvd-report-css --description 'Mark the DVD image as CSS-encrypted.'
complete -c cdemu -l medium-type --description 'Sets the blank medium type.'
complete -c cdemu -l param --description 'Allows user to pass additional image writer parameters.'

