# certtool
# Autogenerated from man page /usr/share/man/man1/certtool.1.gz
# using Type1
complete -c certtool -o 'no-inder\\f[]' --description 'Use DER format for input certificates, private … [See Man Page]'
complete -c certtool -o 'no-outder\\f[]' --description 'Use DER format for output certificates, private… [See Man Page]'

