# commoncpp-config
# Autogenerated from man page /usr/share/man/man1/commoncpp-config.1.gz
# using Deroffing man parser
complete -c commoncpp-config -l version --description 'Print the currently installed version of  commo… [See Man Page]'
complete -c commoncpp-config -l includes --description 'Print the include directory for  common c++ headers.'
complete -c commoncpp-config -l libs --description 'Print the linker flags that are necessary to li… [See Man Page]'
complete -c commoncpp-config -l cflags --description 'Print the compiler flags that are necessary to … [See Man Page]'
complete -c commoncpp-config -l prefix --description 'If specified, use  PREFIX instead of the instal… [See Man Page]'
complete -c commoncpp-config -l exec-prefix --description 'was not specified.  This option must be specified before any.'

