# deluge
# Autogenerated from man page /usr/share/man/man1/deluge.1.gz
# using Deroffing man parser
complete -c deluge -l version --description 'Show program\'s version number and exit.'
complete -c deluge -s h -l help --description 'Show this help message and exit.'
complete -c deluge -s c -l config --description 'Sets the configuration path.'
complete -c deluge -s u -l ui --description 'The UI that you wish to launch, current options… [See Man Page]'
complete -c deluge -s l -l logfile --description 'Output to designated logfile instead of stdout.'
complete -c deluge -s L -l loglevel --description 'Set the log level (default is error): none, inf… [See Man Page]'
complete -c deluge -s q -l quiet --description 'Sets the log level to \'none\', this is the same as `-L none`.'
complete -c deluge -s s -l set-default-ui --description 'Sets the default UI to be run when no UI is specified.'

