# deluge-web
# Autogenerated from man page /usr/share/man/man1/deluge-web.1.gz
# using Deroffing man parser
complete -c deluge-web -s b -l base --description 'Set the base path that the ui is running on (proxying).'
complete -c deluge-web -s f -l fork --description 'Fork the web interface process into the background.'
complete -c deluge-web -s p -l port --description 'Sets the port to be used for the webserver.'
complete -c deluge-web -l profile --description 'Profile the webserver code.'
complete -c deluge-web -l no-ssl --description 'Forces the webserver to disable ssl.'
complete -c deluge-web -l ssl --description 'Forces the webserver to use ssl.'

