# deluged
# Autogenerated from man page /usr/share/man/man1/deluged.1.gz
# using Deroffing man parser
complete -c deluged -l version --description 'Show program\'s version number and exit.'
complete -c deluged -s h -l help --description 'Show this help message and exit.'
complete -c deluged -s p -l port --description 'Port daemon will listen on, default is 58846.'
complete -c deluged -s i -l interface --description 'Interface daemon will listen for bittorrent con… [See Man Page]'
complete -c deluged -s u -l ui-interface --description 'Interface daemon will listen for UI connections… [See Man Page]'
complete -c deluged -s d -l do-not-daemonize --description 'Do not daemonize.'
complete -c deluged -s c -l config --description 'Sets the configuration path.'
complete -c deluged -s l -l logfile --description 'Output to designated logfile instead of stdout.'
complete -c deluged -s P -l pidfile --description 'Use pidfile to store process id.'
complete -c deluged -s L -l loglevel --description 'Set the log level (default is error): none, inf… [See Man Page]'
complete -c deluged -s q -l quiet --description 'Sets the log level to \'none\', this is the same as `-L none`.'

