# desmume-glade
# Autogenerated from man page /usr/share/man/man1/desmume-glade.1.gz
# using Deroffing man parser
complete -c desmume-glade -l load-slot --description 'Loads savegame from slot NUM.'
complete -c desmume-glade -l soft-convert --description 'Use software colour conversion during OpenGL screen rendering.'
complete -c desmume-glade -l 3d-engine --description 'Select available 3d emulation: . RS 0 = 3d disabled . RE .'
complete -c desmume-glade -l disable-limiter --description 'Disables the 60 fps limiter.'
complete -c desmume-glade -l arm9gdb --description 'Enable the ARM9 GDB stub on the given port.'
complete -c desmume-glade -l arm7gdb --description 'Enable the ARM7 GDB stub on the given port.'
complete -c desmume-glade -s h -l help --description 'Show summary of options.'
complete -c desmume-glade -s v -l version --description 'Show version of program.'

