# desmume-cli
# Autogenerated from man page /usr/share/man/man1/desmume-cli.1.gz
# using Deroffing man parser
complete -c desmume-cli -l load-slot --description 'Loads savegame from slot NUM.'
complete -c desmume-cli -l disable-sound --description 'Disables the sound emulation.'
complete -c desmume-cli -l disable-limiter --description 'Disables the 60 fps limiter.'
complete -c desmume-cli -l 3d-engine --description 'Select available 3d emulation: . RS 0 = 3d disabled . RE .'
complete -c desmume-cli -l opengl-2d --description 'Enables using OpenGL for screen rendering.'
complete -c desmume-cli -l soft-convert --description 'Use software colour conversion during OpenGL screen rendering.'
complete -c desmume-cli -l arm9gdb --description 'Enable the ARM9 GDB stub on the given port.'
complete -c desmume-cli -l arm7gdb --description 'Enable the ARM7 GDB stub on the given port.'
complete -c desmume-cli -l save-type --description 'Select savetype from the following: . RS 0 = Autodetect . RE .'
complete -c desmume-cli -l fwlang --description 'Set the language in the firmware, LANG as follows: .'
complete -c desmume-cli -l cflash --description 'Enable disk image GBAMP compact flash emulation.'
complete -c desmume-cli -l help --description 'Show summary of options.'
complete -c desmume-cli -l version --description 'Show version of program.'

