# fitshdr
# Autogenerated from man page /usr/share/man/man1/fitshdr.1.gz
# using Deroffing man parser
complete -c fitshdr -s q --description 'Quit after reading the Nth header, where N is a… [See Man Page]'

