# HPXcvt
# Autogenerated from man page /usr/share/man/man1/HPXcvt.1.gz
# using Deroffing man parser
complete -c HPXcvt -o 'C<col>' --description 'Binary table column number from which to read d… [See Man Page]'
complete -c HPXcvt -o 'c<sys>' --description 'Specify the coordinate system to be used to lab… [See Man Page]'
complete -c HPXcvt -s n -s r --description 'Assume n(ested) or r(ing) organization if the O… [See Man Page]'
complete -c HPXcvt -o 'q<quad>' --description 'Recentre longitude at quad(mod 4) x 90 degrees,… [See Man Page]'
complete -c HPXcvt -o 'x<n' --description 'Use a north-polar or south-polar layout.'

