# ark
# Autogenerated from man page /usr/share/man/man1/ark.1.gz
# using Deroffing man parser
complete -c ark -s d -l dialog --description 'Show a dialog for specifying the options for a … [See Man Page]'
complete -c ark -s o -l destination --description 'Default the extraction directory to directory.'
complete -c ark -s c -l add --description 'Query the user for an archive filename and add … [See Man Page]'
complete -c ark -s t -l add-to --description 'Add the specified files to filename.'
complete -c ark -s p -l changetofirstpath --description 'Change the current directory to the first entry… [See Man Page]'
complete -c ark -s f -l autofilename --description 'Automatically choose a filename, with the selec… [See Man Page]'
complete -c ark -s b -l batch --description 'Use the batch interface instead of the usual dialog.'
complete -c ark -s e -l autodestination --description 'The destination argument will be set to the pat… [See Man Page]'
complete -c ark -s a -l autosubfolder --description 'Archive contents will be read, and if detected … [See Man Page]'

