# aviindex
# Autogenerated from man page /usr/share/man/man1/aviindex.1.gz
# using Deroffing man parser
complete -c aviindex -s o --description 'Specify the name of the output file.'
complete -c aviindex -s i --description 'Specify the name of the input file.'
complete -c aviindex -s f --description 'force the use of the existing index.'
complete -c aviindex -s n --description 'force generating the index by scanning the file.'
complete -c aviindex -s x --description '(implies -n) don\'t use any existing index to ge… [See Man Page]'
complete -c aviindex -s v --description 'show version.'
complete -c aviindex -l nav_seek --description 'the position you specified via -c.'
complete -c aviindex -s h --description 'show help text.'
complete -c aviindex -o saveidx --description 'FILE and load it again through.'
complete -c aviindex -o loadidx --description 'FILE.'

