# avimerge
# Autogenerated from man page /usr/share/man/man1/avimerge.1.gz
# using Deroffing man parser
complete -c avimerge -s o --description 'Specify the name of the output file.'
complete -c avimerge -s i --description 'Specify the name(s) of the input file(s) to mer… [See Man Page]'
complete -c avimerge -s p --description 'Specify the name of the audio file to multiplex… [See Man Page]'
complete -c avimerge -s b --description 'Specify if avimerge should write an VBR mp3 hea… [See Man Page]'
complete -c avimerge -s c --description 'Drop video frames in case audio is missing [off] .'
complete -c avimerge -s f --description 'Read AVI tombstone data for header comments from commentfile.'
complete -c avimerge -s x --description 'Read the AVI index from  indexfile.'
complete -c avimerge -s a --description 'Specify the number of the audio track you want … [See Man Page]'
complete -c avimerge -s A --description 'Specify the number of the audio track you want … [See Man Page]'

