# bar
# Autogenerated from man page /usr/share/man/man1/bar.1
# using Type1
complete -c bar -s h --description 'Display the help and exit.'
complete -c bar -s g --description 'Set the window geometry.'
complete -c bar -s b --description 'Dock the bar at the bottom of the screen.'
complete -c bar -s d --description 'Force docking without asking the window manager.'
complete -c bar -s f --description 'Comma separated list of fonts, bar supports a m… [See Man Page]'
complete -c bar -s p --description 'Make bar permanent, don\'t exit after the standa… [See Man Page]'
complete -c bar -s u --description 'Sets the underline width in pixels.  The default is 1.'
complete -c bar -s B --description 'Set the background color of the bar.'

