# dc1394_multiview
# Autogenerated from man page /usr/share/man/man1/dc1394_multiview.1.gz
# using Deroffing man parser
complete -c dc1394_multiview -l fps --description 'frames per second.  default is 7.'
complete -c dc1394_multiview -l res --description 'resolution.'
complete -c dc1394_multiview -l device --description 'specifies video1394 device to use (optional).'
complete -c dc1394_multiview -l help --description 'print help message.'

