# desmume
# Autogenerated from man page /usr/share/man/man1/desmume.1.gz
# using Deroffing man parser
complete -c desmume -l load-slot --description 'Loads savegame from slot NUM.'
complete -c desmume -l opengl-2d --description 'Enables using OpenGL for screen rendering.'
complete -c desmume -l soft-convert --description 'Use software colour conversion during OpenGL screen rendering.'
complete -c desmume -l 3d-engine --description 'Select available 3d emulation: . RS 0 = 3d disabled  . RE .'
complete -c desmume -l disable-sound --description 'Disables the sound emulation.'
complete -c desmume -l disable-limiter --description 'Disables the 60 fps limiter.'
complete -c desmume -l arm9gdb --description 'Enable the ARM9 GDB stub on the given port.'
complete -c desmume -l arm7gdb --description 'Enable the ARM7 GDB stub on the given port.'
complete -c desmume -l save-type --description 'Select savetype from the following: . RS 0 = Autodetect . RE .'
complete -c desmume -l fwlang --description 'Set the language in the firmware, LANG as follows: .'
complete -c desmume -l cflash --description 'Enable disk image GBAMP compact flash emulation.'
complete -c desmume -s h -l help --description 'Show summary of options.'
complete -c desmume -s v -l version --description 'Show version of program.'

