# finch
# Autogenerated from man page /usr/share/man/man1/finch.1.gz
# using Deroffing man parser
complete -c finch -s c -l config --description 'Use DIR as the directory for config files instead of ~/.'
complete -c finch -s d -l debug --description 'Print debugging messages to stderr and start wi… [See Man Page]'
complete -c finch -s h -l help --description 'Print this help and exit.'
complete -c finch -s n -l nologin --description 'Don\'t automatically login when finch starts.'
complete -c finch -s v -l version --description 'Display the version information window.'

