# fslint-gui
# Autogenerated from man page /usr/share/man/man1/fslint-gui.1.gz
# using Deroffing man parser
complete -c fslint-gui -s f --description 'always print full paths even if only a single p… [See Man Page]'
complete -c fslint-gui -s r --description 'turn OFF recursion.'
complete -c fslint-gui -l version --description 'Display the fslint version and exit.'
complete -c fslint-gui -l help --description 'Display help for tool specific options AUTHOR W… [See Man Page]'

