# fslint
# Autogenerated from man page /usr/share/man/man1/fslint.1.gz
# using Deroffing man parser
complete -c fslint -s f --description 'always print full paths even if only a single p… [See Man Page]'
complete -c fslint -s r --description 'turn OFF recursion.'
complete -c fslint -l version --description 'Display the fslint version and exit.'
complete -c fslint -l help --description 'Display help for tool specific options AUTHOR W… [See Man Page]'

