#
# Tosh 0.2
#

ThemeDescription="Rhapsody - QTStep - produkt"
ThemeAuthor="Row [david@comunidadnet.org]"

Look=pixmap

TitleBarCentered=1
ShowMenuButtonIcon=1
TaskBarShowStartMenu=0

TitleButtonsSupported="xmris"
TitleButtonsRight="im"
TitleButtonsLeft="x"


TitleBarHeight="19"
BorderSizeX="6"
BorderSizeY="6"
CornerSizeX="23"
CornerSizeY="23"
DlgBorderSizeX="6"
DlgBorderSizeY="6"
ButtonX="16"
ButtonY="19"

ColorDialog="rgb:31/3a/3f"
ColorActiveBorder="rgb:20/26/29"
ColorNormalBorder="rgb:31/3a/3f"

ColorNormalTitleButton="rgb:f0/f0/f0"
ColorNormalTitleButtonText="rgb:00/00/00"
ColorNormalButton="rgb:f0/f0/f0"
ColorNormalButtonText="rgb:00/00/00"
ColorActiveButton="rgb:73/ad/ef"
ColorActiveButtonText="rgb:00/00/00"
ColorActiveTitleBar="rgb:9e/9e/9e"
ColorNormalTitleBar="rgb:d8/d8/d8"
ColorActiveTitleBarText="rgb:00/00/00"
ColorNormalTitleBarText="rgb:00/00/00"
ColorNormalMinimizedWindow="rgb:f0/f0/f0"
ColorNormalMinimizedWindowText="rgb:00/00/00"
ColorActiveMinimizedWindow="rgb:73/ad/ef"
ColorActiveMinimizedWindowText="rgb:00/00/00"

ColorNormalMenu="rgb:31/3a/3f"
ColorActiveMenuItem="rgb:fb/70/2a"
ColorActiveMenuItemText="rgb:00/00/00"
ColorNormalMenuItemText="rgb:ff/ff/ff"
ColorDisabledMenuItemText="rgb:80/80/80"

ColorMoveSizeStatus="rgb:f0/f0/f0"
ColorMoveSizeStatusText="rgb:00/00/00"

ColorQuickSwitch="rgb:f0/f0/f0"
ColorQuickSwitchText="rgb:00/00/00"

ColorDefaultTaskBar="rgb:31/3a/3f"
ColorNormalTaskBarApp="rgb:31/3a/3f"
ColorNormalTaskBarAppText="rgb:00/00/00"
ColorActiveTaskBarApp="rgb:fb/70/2a"
ColorActiveTaskBarAppText="rgb:00/00/00"
ColorMinimizedTaskBarApp="rgb:f0/f0/f0"
ColorMinimizedTaskBarAppText="rgb:00/00/00"

ColorInvisibleTaskBarApp="rgb:80/80/80"
ColorInvisibleTaskBarAppText="rgb:00/00/00"

ColorScrollBar="rgb:31/3a/3f"
ColorScrollBarArrow="rgb:6f/75/79"
ColorScrollBarSlider="rgb:6f/75/79"

ColorListBox="rgb:31/3a/3f"
ColorListBoxText="rgb:ff/ff/ff"
ColorListBoxSelection="rgb:fb/70/2a"
ColorListBoxSelectionText="rgb:00/00/00"

ColorToolTip="rgb:f0/f0/f0"
ColorToolTipText="rgb:00/00/00"

ColorClock="rgb:f0/f0/f0"
ColorClockText="rgb:00/00/00"

ColorApm="rgb:f0/f0/f0"
ColorApmText="rgb:00/00/00"

ColorLabel="rgb:f0/f0/f0"
ColorLabelText="rgb:00/00/00"

ColorInput="rgb:31/3a/3f"
ColorInputText="rgb:ff/ff/ff"
ColorInputSelection="rgb:fb/70/2a"
ColorInputSelectionText="rgb:00/00/00"