#
# Tosh 0.2
#

ThemeDescription="NeXTSTEP - OneStepBack - Green Brown"
ThemeAuthor="Row [david@comunidadnet.org]"

Look=pixmap

TitleBarCentered=1
ShowMenuButtonIcon=1
TaskBarShowStartMenu=0

TitleButtonsSupported="xmris"
TitleButtonsRight="im"
TitleButtonsLeft="x"


TitleBarHeight="19"
BorderSizeX="3"
BorderSizeY="3"
CornerSizeX="3"
CornerSizeY="3"
DlgBorderSizeX="3"
DlgBorderSizeY="3"
ButtonX="16"
ButtonY="19"

ColorDialog="rgb:51/7c/5f"
ColorActiveBorder="rgb:00/00/00"
ColorNormalBorder="rgb:85/a3/8f"

ColorNormalTitleButton="rgb:f0/f0/f0"
ColorNormalTitleButtonText="rgb:00/00/00"
ColorNormalButton="rgb:f0/f0/f0"
ColorNormalButtonText="rgb:00/00/00"
ColorActiveButton="rgb:73/ad/ef"
ColorActiveButtonText="rgb:00/00/00"
ColorActiveTitleBar="rgb:00/00/00"
ColorNormalTitleBar="rgb:44/44/44"
ColorActiveTitleBarText="rgb:ff/ff/ff"
ColorNormalTitleBarText="rgb:ff/ff/ff"
ColorNormalMinimizedWindow="rgb:f0/f0/f0"
ColorNormalMinimizedWindowText="rgb:00/00/00"
ColorActiveMinimizedWindow="rgb:73/ad/ef"
ColorActiveMinimizedWindowText="rgb:00/00/00"

ColorNormalMenu="rgb:51/7c/5f"
ColorActiveMenuItem="rgb:ac/44/1d"
ColorActiveMenuItemText="rgb:ff/ff/ff"
ColorNormalMenuItemText="rgb:ff/ff/ff"
ColorDisabledMenuItemText="rgb:80/80/80"

ColorMoveSizeStatus="rgb:f0/f0/f0"
ColorMoveSizeStatusText="rgb:00/00/00"

ColorQuickSwitch="rgb:f0/f0/f0"
ColorQuickSwitchText="rgb:00/00/00"

ColorDefaultTaskBar="rgb:51/7c/5f"
ColorNormalTaskBarApp="rgb:51/7c/5f"
ColorNormalTaskBarAppText="rgb:00/00/00"
ColorActiveTaskBarApp="rgb:ac/44/1d"
ColorActiveTaskBarAppText="rgb:ff/ff/ff"
ColorMinimizedTaskBarApp="rgb:f0/f0/f0"
ColorMinimizedTaskBarAppText="rgb:00/00/00"

ColorInvisibleTaskBarApp="rgb:80/80/80"
ColorInvisibleTaskBarAppText="rgb:00/00/00"

ColorScrollBar="rgb:51/7c/5f"
ColorScrollBarArrow="rgb:85/a3/8f"
ColorScrollBarSlider="rgb:85/a3/8f"

ColorListBox="rgb:51/7c/5f"
ColorListBoxText="rgb:ff/ff/ff"
ColorListBoxSelection="rgb:ac/44/1d"
ColorListBoxSelectionText="rgb:ff/ff/ff"

ColorToolTip="rgb:f0/f0/f0"
ColorToolTipText="rgb:00/00/00"

ColorClock="rgb:f0/f0/f0"
ColorClockText="rgb:00/00/00"

ColorApm="rgb:f0/f0/f0"
ColorApmText="rgb:00/00/00"

ColorLabel="rgb:f0/f0/f0"
ColorLabelText="rgb:00/00/00"

ColorInput="rgb:51/7c/5f"
ColorInputText="rgb:ff/ff/ff"
ColorInputSelection="rgb:ac/44/1d"
ColorInputSelectionText="rgb:ff/ff/ff"