#+TITLE: Virtual Habitat — Redstone 9X Sanctuary (desktop & identity)
#+DESCRIPTION: Redstone 9X FVWM95 configuration, icons, GTK theme, terminals, Wine and DOS bridges, shell identity
#+AUTHOR: Mètsàtron — Sovereign Weaver
#+LANGUAGE: en
#+PROPERTY: header-args :mkdirp yes :results silent
#+PROPERTY: header-args:bash :comments both

* FVWM95 configuration

Win95-themed FVWM95 config projected into the guest home by the launcher.
FVWM95 reads =~/.fvwm95rc= on startup.

#+BEGIN_SRC conf :tangle linux/.config/redstone-9x/fvwm95/system.fvwm95rc :mkdirp yes
#=============================================================================#
#
# .fvwm95rc example configuration file for fvwm95-2.0.43a
# (with enhanced FvwmTaskBar)
#
# This is a Win95-themed configuration for Redstone 9X.
# Based on the upstream sample config from mintsuki/fvwm95.
#
#=============================================================================#


#------------------------------------------------------------------------------
# Fonts — exact XLFDs from Xephyr built-in font set; tested working
#------------------------------------------------------------------------------

WindowFont	-adobe-helvetica-bold-r-normal--14-100-100-100-p-82-iso10646-1
IconFont	fixed
MenuFont   	-adobe-helvetica-medium-r-normal--14-100-100-100-p-76-iso10646-1


#------------------------------------------------------------------------------
# Set the default window colors. The syntax is:
#  DefaultColors winforecolor winbackcolor titleforecolor titlebackcolor
#------------------------------------------------------------------------------

DefaultColors   Black #c0c0c0 #c0c0c0 #808080


#------------------------------------------------------------------------------
# Text and background color for the title bar of the active (selected) window
#------------------------------------------------------------------------------

HilightColors   White #000080


#------------------------------------------------------------------------------
# Text and background color for the title bar of sticky windows
#------------------------------------------------------------------------------

StickyColors    #808080 #008080

# You can also use the Style command to set the colors of individual
# title bars of some non-selected windows
#Style "*" ForeColor yellow
#Style "*" BackColor #808080

#=============================================================================#
#
# Set up the major operating modes
#
#=============================================================================#


# If we use the FvwmTaskBar we don't need the icons :-)
# Style "..." Icon is also commented below.


Style "*" NoIcon
Style "*" ClickToFocus
Style "*" MWMFunctions
Style "*" HintOverride
Style "*" MWMDecor
Style "*" OLDecor

OpaqueMoveSize 10
EdgeScroll 100 100
EdgeResistance 800 100

#
# RandomPlacement prevents user interaction while placing windows
# SmartPlacement attempts to place windows 'intelligently'
# Using both can be interesting
#
 Style "*" RandomPlacement, SmartPlacement


#------------------------------------------------------------------------------
# NoPPosition instructs fvwm to ignore the PPosition field in window
# geometry hints. Emacs annoyingly sets PPosition to (0,0)!
#------------------------------------------------------------------------------

# Style "*" NoPPosition


#------------------------------------------------------------------------------
#
# Set the desk top size in units of physical screen size
#
#------------------------------------------------------------------------------

DeskTopSize 2x2



#=============================================================================#
# Module path and Icon paths
# These paths are colon-separated lists, just like regular unix PATH
#=============================================================================#

# FVWM95 compiled with correct --prefix; compiled-in defaults work.
# Added explicit PixmapPath so menu/titlebar icons resolve.
PixmapPath $HOME/.local/fvwm95/lib/X11/icons

#=============================================================================#
# Set the decoration styles and window options
# Order is important!!!!
# If compatible styles are set for a single window in multiple Style
# commands, then the styles are ORed together. If conflicting styles
# are set, the last one specified is used.
# These commands should command before any menus or functions are defined,
# and before the internal pager is started.
#=============================================================================#


#------------------------------------------------------------------------------
# Default border and handle widths - and then some style definitions
#------------------------------------------------------------------------------

Style "*" BorderWidth 2, HandleWidth 4

Style "Fvwm*"        NoTitle, Sticky, WindowListSkip
Style "FvwmPager"    Title, Sticky, WindowListHit
Style "FvwmPager"    StaysOnTop, NoHandles
Style "FvwmTalk"     Title, WindowListHit
Style "FvwmConsole"  Title, WindowListHit
Style "FvwmBanner"   StaysOnTop

# xclass desktop manager (desktop-0.3.4) — borderless, no titlebar, sticky
Style "Desktop"      NoTitle, NoHandles, Sticky, WindowListSkip, CirculateSkip, BorderWidth 0

# Audacious music player — borderless panel style
Style "audacious"    NoTitle, NoHandles, Sticky, BorderWidth 0


Style "*lock"        NoTitle, NoHandles, Sticky, WindowListSkip
Style "xbiff"        NoTitle,            Sticky, WindowListSkip
Style "xsysinfo"     NoTitle,            Sticky, WindowListSkip
Style "xload"        NoTitle,            Sticky, WindowListSkip,RandomPlacement
Style "xconsole"                         Sticky, StartIconic
Style "xpostit"                                  WindowListSkip
Style "PostitNote"                               WindowListSkip
Style "Postit"       NoHandles,                  WindowListSkip



#------------------------------------------------------------------------------
# Some mini-icons for the title bar
#------------------------------------------------------------------------------

Style "*"         	TitleIcon mini-x2.xpm
Style "*xterm*"   	TitleIcon mini-term.xpm
Style "rxvt"      	TitleIcon mini-term.xpm
Style "redstone-calc"	TitleIcon mini-calc.xpm
Style "xsession"  	TitleIcon mini-bx2.xpm
Style "xv"        	TitleIcon mini-xv.xpm
Style "Netscape"  	TitleIcon mini-nscape.xpm
Style "xmag"      	TitleIcon mini-zoom.xpm
Style "textedit"  	TitleIcon mini-edit.xpm
Style "*emacs*"	  	TitleIcon mini-edit.xpm
Style "tkps"      	TitleIcon mini-run.xpm
Style "Ghostview" 	TitleIcon mini-gv.xpm
Style "gv*"	 	TitleIcon mini-gv.xpm
Style "Xcolorsel" 	TitleIcon mini-colors.xpm
Style "IDL*"      	TitleIcon mini-zoom.xpm
Style "xeyes"     	TitleIcon mini-eyes.xpm
Style "*fm*"      	TitleIcon mini-filemgr.xpm
Style "FileRunner"	TitleIcon mini-ofolder.xpm
Style "The GIMP"  	TitleIcon mini-wilber.xpm
Style "Scilab"    	TitleIcon mini-fractal.xpm
Style "thot"      	TitleIcon mini-pencil.xpm
Style "LyX"      	TitleIcon mini-pencil.xpm
# xman resource names
Style "topBox"    	TitleIcon mini-book1.xpm
Style "help"      	TitleIcon mini-book2.xpm
Style "manualBrowser" 	TitleIcon mini-book2.xpm
# xpaint resource names
Style "xpaint"   	TitleIcon mini-paint.xpm
Style "Canvas"   	TitleIcon mini-paint.xpm
Style "fatbits" 	TitleIcon mini-paint.xpm
Style "filebrowser"	TitleIcon mini-ofolder.xpm
# Fox
Style "Explorer"     	TitleIcon explorer.xpm
Style "Run"     	TitleIcon run1616.xpm
Style "Notepad"     	TitleIcon mini.text.xpm
Style "*onyx*"         TitleIcon onyx1616.xpm
# others...
Style "FvwmPager"    	TitleIcon mini-pager.xpm
Style "XDbx"         	TitleIcon mini-bug2.xpm
Style "Workman"      	TitleIcon mini-cd.xpm
Style "*playcd*"      	TitleIcon mini-cd.xpm
Style "*cdplay*"      	TitleIcon mini-cd.xpm
Style "Mail"         	TitleIcon mini-mail.xpm
Style "*mail*"         TitleIcon mini-mail.xpm
Style "xmh"            TitleIcon mini-mail.xpm
Style "AcroRead"     	TitleIcon mini-pdf.xpm
Style "NcFtp"        	TitleIcon mini-ftp.xpm
Style "XbmBrowser"   	TitleIcon mini-paint.xpm
Style "Bitmap"       	TitleIcon mini-paint.xpm
Style "Pixmap"       	TitleIcon mini-paint.xpm
Style "XClipboard"   	TitleIcon mini-clipboard.xpm
Style "control-panel"  	TitleIcon mini-redhat.xpm
Style "*console*"  	TitleIcon mini-display.xpm


#=============================================================================#
#
# Stuff to do at start-up and on restart
#
#=============================================================================#


DestroyFunc "InitFunction"
AddToFunc "InitFunction"    "I" Exec desktop
+                           "I" Exec sleep 0.3
+                           "I" Module FvwmBanner
+                           "I" Module FvwmWharf QuickLaunch
+                           "I" Module FvwmTaskBar

DestroyFunc "RestartFunction"
AddToFunc "RestartFunction" "I" Module FvwmTaskBar
+                           "I" Module FvwmWharf QuickLaunch


#============================================================================#
#
# Now define some handy complex functions
#
#============================================================================#

#------------------------------------------------------------------------------
# This one moves and then raises the window if you drag the mouse,
# only raises the window if you click, or does a vertical maximize if
# you double click (full screen maximize would be 'Maximize 100 100')
#------------------------------------------------------------------------------

DestroyFunc "Move-or-Raise"
AddToFunc "Move-or-Raise" "M" Move
+                         "M" Raise
+                         "C" Raise
+                         "D" Maximize 100 96



#------------------------------------------------------------------------------
# This one moves and then lowers the window if you drag the mouse,
# only lowers the window if you click, or does a RaiseLower if you double
# click
#------------------------------------------------------------------------------

DestroyFunc "Move-or-Lower"
AddToFunc "Move-or-Lower" "M" Move
+                         "M" Lower
+                         "C" Lower
+                         "D" RaiseLower


#------------------------------------------------------------------------------
# This one moves or (de)iconifies:
#------------------------------------------------------------------------------

DestroyFunc "Move-or-Iconify"
AddToFunc "Move-or-Iconify" "M" Move
+                           "D" Iconify

#------------------------------------------------------------------------------
# This one maximizes vertically if you click (leaving room for the taskbar
# at the bottom, or does a full maximization if you double click, or a
# true full vertical maximization if you just hold the mouse button down.
#------------------------------------------------------------------------------


DestroyFunc "Maximize-Func"
AddToFunc "Maximize-Func" "M"	Maximize 0 96
+ 			  "C"	Maximize 0 100
+ 			  "D"	Maximize 100 96

#------------------------------------------------------------------------------
# This one resizes and then raises the window if you drag the mouse,
# only raises the window if you click,  or does a RaiseLower if you double
# click
#------------------------------------------------------------------------------

DestroyFunc "Resize-or-Raise"
AddToFunc "Resize-or-Raise" "M" Resize
+                           "M" Raise
+                           "C" Raise
+                           "D" RaiseLower


#------------------------------------------------------------------------------
# This one focuses and then 'warps' to the center of the window.
#------------------------------------------------------------------------------


DestroyFunc "FocusAndWarp"
AddToFunc FocusAndWarp "I" Focus
+                      "I" WarpToWindow 50 50


#------------------------------------------------------------------------------
# Like the precedent, but de-iconifies first.
#------------------------------------------------------------------------------

DestroyFunc "DeiconifyFocusAndWarp"
AddToFunc DeiconifyFocusAndWarp "I" Iconify -1
+                               "I" FocusAndWarp


#------------------------------------------------------------------------------
# This one is used to modify some settings
#------------------------------------------------------------------------------

DestroyFunc "ChangeDefaultFocus"
AddToFunc ChangeDefaultFocus "I" Style "*" $0
+                            "I" Recapture


#------------------------------------------------------------------------------
# A really useful one: de-iconifies, warps to the window
# or creates it if it doen't exist (often used with mailtools)
#------------------------------------------------------------------------------

DestroyFunc "WarpOrExec"
AddToFunc WarpOrExec	   "I" Next [$0] Iconify -1
+		           "I" Next [$0] FocusAndWarp
+			   "I" None [$0] Exec $0 $1


#------------------------------------------------------------------------------
# One more complex function - couldn't be defined earlier because it used
# pop-up menus
#
# This creates the "system" menu for the title-bar window-ops
# pop-up
#------------------------------------------------------------------------------


DestroyMenu "window_ops_func"
AddToFunc "window_ops_func" "C" PopUp Window-Ops2
+	              "M" PopUp Window-Ops2
+	              "D" Delete


#=============================================================================#
#
# Now define the menus - defer bindings until later
#
#=============================================================================#



#------------------------------------------------------------------------------
#--------- Taskbar's start menu
#------------------------------------------------------------------------------

DestroyMenu "StartMenu"
AddToMenu "StartMenu@fvwm-menu.xpm@^#808080^"
+ "File Manager       %mini-filemgr.xpm%"       Exec explorer $HOME &
+ "Alt File Manager    %mini-folder.xpm%"          Exec pcmanfm $HOME &
+ "Text Editor        %mini-edit.xpm%"          Exec mousepad &
+ "Emacs              %mini-edit.xpm%"          Exec /home/metsatron/.guix-extra-profiles/desktop-common/desktop-common/bin/emacs &
+ "Audacious          %mini-cd.xpm%"            Exec audacious &
+ "Obsidian           %mini-edit.xpm%"          Exec /home/metsatron/.local/bin/sanctuary-flatpak-run md.obsidian.Obsidian &
+ "Appearance         %mini-paint.xpm%"         Exec lxappearance &
+ ""                   Nop
+ "Accessories        %mini-edit.xpm%"          Popup Accessories
+ "Games              %mini-solitaire.xpm%"      Popup Games
+ "Ports              %mini-solitaire.xpm%"      Popup Ports
+ "Multimedia         %mini-cd.xpm%"            Popup Multimedia
+ "Terminals          %mini-term.xpm%"          Popup Terminals
+ "DOS / Windows      %mini-bomb.xpm%"          Popup DosWindows
+ "Wine Tools         %mini-x2.xpm%"            Popup WineTools
+ "Control Panel      %mini-paint.xpm%"         Popup ControlPanel
+ ""                   Nop
+ "Run (ice2k)...     %mini-x2.xpm%"            Exec runbox &
+ "Shut Down (ice2k)  %mini-stop.xpm%"          Exec shutdlg &
+ ""                   Nop
+ "Restart FVWM95     %mini-turn.xpm%"          Restart
+ "Quit FVWM95        %mini-stop.xpm%"          Quit


DestroyMenu "Multimedia"
AddToMenu "Multimedia" "Multimedia" Title
+ "VLC                %vlc.xpm%"                Exec redstone-9x-vlc &
+ "Audacious          %mini-cd.xpm%"            Exec audacious &


DestroyMenu "Accessories"
AddToMenu "Accessories" "Accessories" Title
+ "Mousepad           %mini-edit.xpm%"          Exec mousepad &
+ "Paint              %mini-paint.xpm%"         Exec gpaint &
+ "AbiWord            %mini-edit.xpm%"          Exec abiword &
+ "Gnumeric           %mini-calc.xpm%"          Exec gnumeric &
+ "Calculator         %mini-calc.xpm%"          Exec xterm -name redstone-calc -title "Calculator" -e tcalc &

DestroyMenu "Games"
AddToMenu "Games" "Games" Title
+ "Minesweeper        %dsdmine.xpm%"             Exec redstone-9x-dsdmine &
+ "Minesweeper (ice2k) %dsdmine.xpm%"            Exec winmine &
+ "Solitaire          %mini-solitaire.xpm%"      Exec sol &
+ "FreeCell           %mini-solitaire.xpm%"      Exec sol --variation=freecell &
+ "GNU Backgammon     %gnubg.xpm%"                Exec gnubg &
+ "FreeCiv            %freeciv.xpm%"             Exec freeciv-gtk3.22 &
+ "CorsixTH           %corsixth.xpm%"            Exec corsix-th &
+ "OpenTTD            %openttd.xpm%"             Exec openttd &
+ "OpenRCT2           %openrct2.xpm%"            Exec openrct2 &
+ "OpenRA             %openra.xpm%"             Exec redstone-9x-openra &
+ "Micropolis         %micropolis.xpm%"          Exec redstone-9x-micropolis &
+ "Space Cadet Pinball %pinball.xpm%"            Exec redstone-9x-pinball &

# ice2k native control-panel applets (built by sanctuary-redstone-9x-ice2k-build,
# resolved via ~/.local/ice2k/bin on PATH). Icon-free entries so no XPM is needed.
DestroyMenu "ControlPanel"
AddToMenu "ControlPanel" "Control Panel" Title
+ "Device Manager"        Exec devmgmt &
+ "System"                Exec sysdmcpl &
+ "Display"               Exec deskcpl &

# The ports submenu is emitted from the bounded depth-1/depth-2 launcher glob.
PipeRead "/home/metsatron/.local/bin/ports-menu-gen fvwm"


DestroyMenu "Terminals"
AddToMenu "Terminals" "Terminals" Title
+ "Windows PowerShell"      Exec bash /home/metsatron/.local/bin/redstone-9x-run xterm -class redstone-powershell -title PowerShell -geometry 80x25 -fa "Consolas" -fs 11 -bg "#012456" -fg "#EEEDF0" -cr "#EEEDF0" -e /home/metsatron/.local/bin/redstone-9x-pwsh
+ "Zsh"                     Exec /home/metsatron/.local/bin/redstone-9x-zsh --window
+ "Bash"                    Exec /home/metsatron/.local/bin/redstone-9x-bash --window
+ "Command Prompt"          Exec bash /home/metsatron/.local/bin/redstone-9x-run urxvt -hold -name redstone-bash-cmd -title "Command Prompt" -geometry 80x25 +sb -bg rgb:0c/0c/0c -fg rgb:cc/cc/cc -cr rgb:cc/cc/cc -fn "xft:Lucida Console:pixelsize=14:antialias=true" -e bash -lc 'exec wine cmd.exe'
+ "Bash (CMD frame)"        Exec bash /home/metsatron/.local/bin/redstone-9x-run urxvt -name redstone-bash-cmd -title "Command Prompt" -geometry 80x25 +sb -bg rgb:0c/0c/0c -fg rgb:cc/cc/cc -cr rgb:cc/cc/cc -fn "xft:Lucida Console:pixelsize=14:antialias=true" -e bash
+ "URxVT"                   Exec bash /home/metsatron/.local/bin/redstone-9x-run urxvt -name redstone-plain-urxvt -title "URxVT" -geometry 80x25 +sb -bg rgb:00/00/00 -fg rgb:d6/d3/ce -cr rgb:d6/d3/ce -fn "xft:Courier New:size=11:antialias=true,xft:monospace:size:11:antialias=true" -e bash
+ "XTerm"                   Exec bash /home/metsatron/.local/bin/redstone-9x-run xterm -title "XTerm" -geometry 80x25

DestroyMenu "DosWindows"
AddToMenu "DosWindows" "DOS / Windows" Title
+ "MS-DOS Prompt      %mini-bomb.xpm%"          Exec bash /home/metsatron/.local/bin/redstone-9x-run xterm -title "MS-DOS Prompt" -geometry 80x25 -fa "Perfect DOS VGA 437 Win" -fs 11 -bg black -fg "#c0c0c0" -e /home/metsatron/.local/bin/redstone-9x-dosemu2-shell &
+ "DOSBox-X           %mini-bomb.xpm%"          Exec /home/metsatron/.local/bin/redstone-9x-dosbox-x &

DestroyMenu "WineTools"
AddToMenu "WineTools" "Wine Tools" Title
+ "Wine Configurator"  Exec wine64 winecfg
+ "Registry Editor"    Exec wine64 regedit
+ "Windows Explorer"   Exec wine64 explorer
+ "Notepad"            Exec wine64 notepad




#------------------------------------------------------------------------------
# This defines the most common window operations
#------------------------------------------------------------------------------


DestroyMenu "Window"
AddToMenu "Window" "Window Ops" Title
+ "&Move%mini-move.xpm%"                Function Move-or-Raise
+ "&Resize%mini-resize.xpm%"            Function Resize-or-Raise
+ "R&aise%mini-raise.xpm%"              Raise
+ "&Lower%mini-lower.xpm%"              Lower
+ "(De)Iconify%mini-iconify.xpm%"       Iconify
+ "(Un)Stick%mini.stick.xpm%"           Stick
+ "(Un)Maximize%mini-max1.xpm%"         Maximize 100 96
+ "(Un)Maxwide%mini-maxwide.xpm%"       Maximize 100 0
+ ""                                    Nop
+ "Kill"                                Destroy
+ "&Close"                              Delete
+ ""                                    Nop
+ "Switch to..."                        WindowList
+ "Refresh Screen"                      Refresh


#------------------------------------------------------------------------------
# Win95-style desktop right-click context menu
#------------------------------------------------------------------------------

DestroyMenu "DeskCtx"
AddToMenu "DeskCtx"@fvwm-menu.xpm@^#808080^
+ "New Folder"                         Exec xterm -e mkdir ${HOME}/.xclass/desktop/"New Folder"
+ ""                                    Nop
+ "Arrange Icons"                       Nop
+ "Line Up Icons"                       Nop
+ ""                                    Nop
+ "Paste"                               Nop
+ "Paste Shortcut"                      Nop
+ ""                                    Nop
+ "New"                                 Popup NewCtx
+ ""                                    Nop
+ "Properties%mini-paint.xpm%"          Exec lxappearance &

DestroyMenu "NewCtx"
AddToMenu "NewCtx"
+ "Folder"                              Exec xterm -e mkdir ${HOME}/.xclass/desktop/"New Folder"
+ "Text Document"                      Exec touch ${HOME}/.xclass/desktop/"New Text Document.txt"


#------------------------------------------------------------------------------
# A trimmed down version of "Window Ops", good for binding to decorations
#------------------------------------------------------------------------------

DestroyMenu "Window-Ops2"
AddToMenu "Window-Ops2" "&Restore"        Iconify -1
+	              "&Move"           Move-or-Raise
+	              "&Size"           Resize-or-Raise
+	              "Mi&nimize"       Iconify 1
+	              "Ma&ximize"       Maximize 100 96
+	              ""                Nop
+	              "&Kill"           Destroy
+	              "&Close"          Delete


#=============================================================================#
#
# Mouse , frame buttons and keyboard bindings
#
#=============================================================================#


#------------------------------------------------------------------------------
# First, for the mouse in the root window (Context=R)
# Button 1 gives the Start menu
# Button 2 gives the Window Ops menu
# Button 3 gives the WindowList
#------------------------------------------------------------------------------


#     Button	Context Modifi 	Function

Mouse 1		R   	A       Menu "StartMenu" Nop
Mouse 2		R    	A       Menu "Window" Nop
# Root button3 is intentionally NOT bound: the xclass desktop manager
# installs its own XGrabButton(AnyButton) on the root to show its native
# context menu (New / Arrange Icons By / Line Up Icons / Auto Arrange /
# Properties). A fvwm95 root button3 binding would conflict (BadAccess) and
# prevent the xclass menu — and thus Arrange Icons By / Auto Arrange —
# from ever working.
#Mouse 3         R       A       Menu "DeskCtx" Nop
#Mouse 3	R    	A      	Module "winlist" FvwmWinList transient


#------------------------------------------------------------------------------
# Now the title bar buttons
# Any button in the left title-bar button gives the window ops menu
# Any button in the first right title-bar button Iconifies the window
# Any button in the second title-bar button full-maximizes
# Any button in the third (rightmost) title-bar button closes
# Note the use of "Mouse 0" for AnyButton.
#------------------------------------------------------------------------------


#     Button	Context Modif 	Function
Mouse 0		1    	A      	Function "window_ops_func"
Mouse 1         2       A       Delete
Mouse 0		4    	A     	Maximize 100 96
Mouse 0		6    	A     	Iconify


#------------------------------------------------------------------------------
# Now the rest of the frame
# Here I invoke my complex functions for Move-or-lower, Move-or-raise,
# and Resize-or-Raise.
#------------------------------------------------------------------------------

# Button 1 in the corners or sides, with any modifiers, gives resize or raise
Mouse 1		FS	A	Function "Resize-or-Raise"

# Button 1 in the title, sides, or icon, w/ any modifiers, gives move or raise
Mouse 1		T	A	Function "Move-or-Raise"

# Button 1 in an icons gives move for a drag, de-iconify for a double-click,
# nothing for a single click
Mouse 1		I	A	Function "Move-or-Iconify"

# Button 2 in an icon, w/ any modifiers, gives de-iconify
Mouse 2		I	A	Iconify

# Button 2 in the corners, sides, or title-bar gives the window ops menu
Mouse 2		FST	A	Function "window_ops_func"

# Button 3 anywhere in the decoration (except the title-bar buttons)
# does a raise-lower
Mouse 3		TSIF	A	RaiseLower

# Button 3 in the window, with the Modifier-1 key (usually alt or diamond)
# gives Raise-Lower. Used to use control here, but that interferes with xterm
Mouse 3         W       M       RaiseLower



#------------------------------------------------------------------------------
# Now some keyboard shortcuts.
# Most are commented, they are there for documentation.
#------------------------------------------------------------------------------

#------------------------------------------------------------------------------
# press arrow + control anywhere, and scroll by 1 page
#------------------------------------------------------------------------------

Key Left	A	C	Scroll -100 0
Key Right	A	C	Scroll +100 +0
Key Up		A	C	Scroll +0   -100
Key Down	A	C	Scroll +0   +100

#------------------------------------------------------------------------------
# press arrow + meta key, and scroll by 1/10 of a page
#------------------------------------------------------------------------------

Key Left	A	M	Scroll -10 +0
Key Right	A	M	Scroll +10 +0
Key Up		A	M	Scroll +0   -10
Key Down	A	M	Scroll +0   +10

#------------------------------------------------------------------------------
# Keyboard accelerators - I left F1-F8 out because they are often used
# by apps other than the window manager
#------------------------------------------------------------------------------

Key F9		A	A	Iconify
Key F10		A	A	Iconify
Key F11		A	A	CirculateUp
Key F12		A	A	CirculateDown

#------------------------------------------------------------------------------
# Page Up/Page Down keys are used to scroll by one desktop page
# in any context, press page up/down + control
# in root context, just pressing page up/down is OK
#------------------------------------------------------------------------------

Key Next	A       C       Scroll 100000 0
Key Next	R       N       Scroll 100000 0
Key Prior	A       C       Scroll -100000 0
Key Prior	R       N       Scroll -100000 0


#------------------------------------------------------------------------------
# press arrow left/right+ control anywhere, and skip focus
#------------------------------------------------------------------------------

Key Left	A	S	Prev FocusAndWarp
Key Right	A	S	Next [!iconic] FocusAndWarp
Key Down	A	S	Prev FocusAndWarp
Key Up  	A	S	Next [iconic] DeIconifyFocusAndWarp

Key Tab         A       M       Prev FocusAndWarp
Key Tab         A       MS      Next FocusAndWarp


#=============================================================================#
#
# Definitions used by the modules
#
#=============================================================================#


#------------------------------------------------------------------------------
#------------------ FvwmWharf QuickLaunch bar
#------------------------------------------------------------------------------
# NOTE: this mintsuki FVWM95 fork sets ModuleName = argv[0] basename
# ("FvwmWharf"), NOT the fvwm alias used in `Module FvwmWharf QuickLaunch`.
# So the config prefix must be *FvwmWharf, not *QuickLaunch, or
# match_string() is never reached and FvwmWharf exits "No Buttons defined".

Style "FvwmWharf" NoTitle, NoHandles, Sticky, WindowListSkip, CirculateSkip, BorderWidth 0

*FvwmWharfGeometry +38-26
*FvwmWharfRows 1
*FvwmWharfForceSize
*FvwmWharfNoBorder
*FvwmWharfBgColor #c0c0c0
*FvwmWharfTextureType 0
*FvwmWharfTextureColor #c0c0c0 #808080

# Quick-launch icons (FvwmWharf button line: *<ModuleName> <label> <icon> <action>)
*FvwmWharf Explorer   mini-filemgr.xpm   Exec explorer $HOME &
*FvwmWharf Editor     mini-edit.xpm      Exec mousepad &
*FvwmWharf Term       mini-term.xpm      Exec xterm &
*FvwmWharf Music      mini-cd.xpm       Exec audacious &
*FvwmWharf Apps       mini-paint.xpm     Exec lxappearance &

#------------------------------------------------------------------------------
#------------------ FvwmTaskBar
#------------------------------------------------------------------------------

Style "FvwmTaskBar" NoTitle,BorderWidth 4,HandleWidth 4,Sticky, \
                    StaysOnTop,WindowListSkip,CirculateSkip

*FvwmTaskBarGeometry +0-0
*FvwmTaskBarFore Black
*FvwmTaskBarBack #c0c0c0
*FvwmTaskBarFont -adobe-helvetica-medium-r-normal--14-100-100-100-p-76-iso10646-1
*FvwmTaskBarSelFont -adobe-helvetica-bold-r-normal--14-100-100-100-p-82-iso10646-1
*FvwmTaskBarStatusFont fixed
*FvwmTaskBarAction Click1 Iconify -1,Raise,Focus
*FvwmTaskBarAction Click2 Iconify
*FvwmTaskBarAction Click3 PopUp Window-Ops2
*FvwmTaskBarUseSkipList
*FvwmTaskBarAutoStick
*FvwmTaskBarStartName Start
*FvwmTaskBarStartMenu StartMenu
*FvwmTaskBarStartIcon mini-win95.xpm
*FvwmTaskBarShowTips
*FvwmTaskBarShowTransients
#*FvwmTaskBarHighlightFocus
#*FvwmTaskBarAutoHide
*FvwmTaskBarDeskOnly



# Now the goodies....

# Clock status area (real, not a static decoration): the ShowDateModule
# goody plugin, built alongside FvwmTaskBar by sanctuary-redstone-9x-fvwm95-build
# (so its ABI matches). 12-hour AM/PM, no seconds — Win95 clock convention.
# Path is substituted at launch time by sanctuary-redstone-9x-launch
# (the FvwmTaskBar module's CopyString does NOT expand $HOME, so an absolute
# guest-home path must be patched into the projected config).
*FvwmTaskBarGoodyLoadablePlugins @GUEST_PLUGINS@
*FvwmTaskBarGoodyLoadableQuiet
*FvwmTaskBarGoodyLoadableSymbol ShowDateModuleSymbol
*FvwmTaskBarGoodyLoadableId .DATE
*FvwmTaskBarShowDateModuleClockFormat.DATE %I:%M %p

# Screen lock
# *FvwmTaskBarGoodyLoadableSymbol GoodyModuleSymbol
# *FvwmTaskBarGoodyLoadableId .LOCK
# *FvwmwmTaskBarGoodyModuleIcon.LOCK mini-lock.xpm
# *FvwmTaskBarGoodyModuleTip.LOCK Screen Locker

#------------------------------------------------------------------------------
#------------------ FvwmConsole
#------------------------------------------------------------------------------

*FvwmConsoleHook /dev/console

#------------------------------------------------------------------------------
#------------------ FvwmForm
#------------------------------------------------------------------------------

*FvwmFormFore Black
*FvwmFormBack #c0c0c0

#------------------------------------------------------------------------------
#------------------ FvwmPager
#------------------------------------------------------------------------------

*FvwmPagerFore Black
*FvwmPagerBack #c0c0c0

#+END_SRC

IceWM preferences tangle block.  Selects the Windows 95 theme (the retired Windows NT theme — wrong colours, weak implementation — was dropped 2026-07-19 by decree) and incorporates
the theme-supplied =extras/prefoverride= settings.  Stows to =~/.icewm/preferences=
on the host; the launcher above projects this file directly into the guest home.

#+BEGIN_SRC conf :tangle linux/.icewm/preferences
Theme="Windows-95/default.theme"

# ── Taskbar: authentic Windows 95/2000 layout (ice2k convention) ──
# A real Win9x taskbar is only  Start | quick-launch | task buttons | tray |
# clock.  IceWM's Linux system-monitor applets (CPU / MEM / Net / APM graphs),
# the workspace pager and the show-desktop button were the "non-conforming"
# widgets — all switched OFF here.  Workspaces still work by keybind; only the
# pager buttons leave the taskbar.
ShowTaskBar=1
TaskBarAtTop=0
TaskBarShowClock=1
TaskBarShowWindows=1
TaskBarShowWindowIcons=1
TaskBarShowWorkspaces=0
TaskBarShowShowDesktopButton=1
TaskBarShowCPUStatus=0
TaskBarShowMEMStatus=0
TaskBarShowNetStatus=0
TaskBarShowAPMStatus=0
TaskBarShowAPMAuto=0
TaskBarShowAPMGraph=0
TaskBarShowMailboxStatus=0
TaskBarDoubleHeight=0
TaskbarButtonWidthDivisor=9
TaskBarShowWindowListMenu=0
TaskBarShowCollapseButton=0

# ── System tray: enabled, sized to the Win9x tray (ice2k values) ──
TaskBarShowTray=1
TaskBarEnableSystemTray=1
TrayIconMaxWidth=20
TrayIconMaxHeight=20
TrayDrawBevel=1

# ── Suppress IceWM's built-in appended Start-menu items ──
# Without these, IceWM appends its OWN "Settings", "Windows" (window list) and
# "Logout" entries beneath our menu — that is the duplicate-Settings /
# stray-Logout / stray-Windows seen in the wild.  ice2k disables every one and
# hand-builds the whole menu; so do we (see ~/.icewm/menu).  This is what makes
# the Start menu read exactly:
#   Programs / Documents / Settings / Find / Help / Run... / Shut Down...
ShowProgramsMenu=0
ShowSettingsMenu=0
ShowFocusModeMenu=0
ShowThemesMenu=0
ShowLogoutMenu=0
ShowLogoutSubMenu=0
ShowHelp=0
ShowAbout=0
ShowRun=0
ShowWindowList=0

# Icon sizing for the theme pixmaps
MenuIconSize=24
ShowMenuButtonIcon=1

# Mouse-driven menu tracking (Windows 9x convention)
MenuMouseTracking=1

# Clock: authentic Windows 95 "h:mm AM/PM" tray clock (hover = full date).
TimeFormat=" %l:%M %p "

#+END_SRC


IceWM right-click desktop menu.  Projected into the guest home by the launcher.

#+BEGIN_SRC conf :tangle linux/.icewm/menu
# Redstone 9X — IceWM Start menu (Windows 95 canonical layout)
#
# IceWM's own built-in Settings / Logout / Windows / Run / About / Help items
# are disabled in ~/.icewm/preferences (Show*=0), so THIS file defines the
# ENTIRE menu.  The top level is the canonical Windows 95 order with the
# SerenityOS-style default-app quartet on top (Mètsàtron 2026-07-19: they
# live in both the menu AND the quick launch — we have the vertical room):
#   Terminal / File Manager / Web Browser / Text Editor /
#   Programs / Documents / Desktop / Settings / Find / Help / Run... / Shut Down...

prog "Terminal"      utilities-terminal       /home/metsatron/.local/bin/redstone-9x-bash --window
prog "File Manager"  system-file-manager      pcmanfm
prog "Web Browser"   firefox_2                firefox
prog "Text Editor"   accessories-text-editor  mousepad

separator

menu "Programs" gnome-applications {
prog "Xfe"               system-file-manager      /home/metsatron/.guix-extra-profiles/room-gaming/room-gaming/bin/xfe
prog "PCManFM"           folder                   pcmanfm
prog "Explorer (xclass)" system-file-manager      redstone-9x-explorer
prog "Text Editor"       accessories-text-editor  mousepad
prog "Emacs"             emacs  /home/metsatron/.guix-extra-profiles/desktop-common/desktop-common/bin/emacs
prog "Firefox"           firefox_2                firefox
prog "Pale Moon"         palemoon                 redstone-9x-host-gtk /home/metsatron/.local/bin/palemoon
prog "SeaMonkey"         seamonkey                redstone-9x-host-gtk /home/metsatron/.local/bin/seamonkey
prog "Audacious"         winamp                   audacious
prog "Obsidian"          obsidian  /home/metsatron/.local/bin/sanctuary-flatpak-run com.tiagopires.ObsidianRedstone

separator

# Categories in Serenity's System Menu order, each wearing its proper
# applications-* icon (both Chicago95 and Serenity95 provide all of them —
# verified 2026-07-19; bare "folder" icons on categories were the bug).
menu "Accessories" applications-utilities {
  prog "Notepad"       accessories-text-editor   xfw
  prog "Mousepad"      accessories-text-editor   mousepad
  prog "Pluma"         accessories-text-editor   dbus-run-session pluma
  prog "Imaging"       applications-multimedia   xfi
  prog "Calculator"    accessories-calculator    xterm -name redstone-calc -title "Calculator" -e tcalc
  prog "Atril"         postscript-viewer         /home/metsatron/.guix-extra-profiles/room-gaming/room-gaming/bin/atril
  prog "Ark"           archive-manager           env QT_QPA_PLATFORMTHEME=qt6ct QT_PLUGIN_PATH=@ROOM_QT6_PLUGINS@ ark
}

menu "Development" applications-development {
  prog "Emacs"         emacs                     /home/metsatron/.guix-extra-profiles/desktop-common/desktop-common/bin/emacs
  prog "VSCodium"      com.visualstudio.code     /home/metsatron/.guix-extra-profiles/room-gaming/room-gaming/bin/codium
  prog "Geany"         applications-development  geany
  separator
  prog "Adie (FOX editor)"       accessories-text-editor  adie
  prog "PathFinder (FOX)"        system-file-manager      PathFinder
  prog "FOX Calculator"          accessories-calculator   calculator
}

menu "Games" applications-games {
  prog "Minesweeper"          applications-games           redstone-9x-dsdmine
  prog "Minesweeper (ice2k)"  applications-games           winmine
  prog "Minesweeper (Wine)"   wine              redstone-9x-wine winemine
  prog "Solitaire"            applications-games   sol
  prog "FreeCell"             applications-games   sol --variation=freecell
  prog "GNU Backgammon"       applications-games             gnubg
  prog "FreeCiv"              applications-games    freeciv-gtk3.22
  prog "CorsixTH"             corsix-th         corsix-th
  prog "OpenTTD"              applications-games           openttd
  prog "OpenRCT2"             applications-games          openrct2
  prog "OpenRA"               applications-games            redstone-9x-openra
  prog "Micropolis"           applications-games     redstone-9x-micropolis
  prog "Space Cadet Pinball"  applications-games  redstone-9x-pinball
  prog "Dark Forces"          applications-games  /home/metsatron/.local/bin/sanctuary-flatpak-run io.github.theforceengine.tfe
}

menuprog "Ports" applications-games /home/metsatron/.local/bin/ports-menu-gen icewm

menu "Graphics" applications-graphics {
  prog "Paint"         applications-painting     gpaint-2
  prog "Eye of MATE"   eom                       dbus-run-session eom
  prog "GIMP"          gimp                      /home/metsatron/.guix-extra-profiles/room-gaming/room-gaming/bin/gimp
  prog "Inkscape"      inkscape                  /home/metsatron/.guix-extra-profiles/room-gaming/room-gaming/bin/inkscape
}

menu "Internet" applications-internet {
  prog "Firefox"       firefox_2                 firefox
  prog "Pale Moon"     palemoon                  redstone-9x-host-gtk /home/metsatron/.local/bin/palemoon
  prog "SeaMonkey"     seamonkey                 redstone-9x-host-gtk /home/metsatron/.local/bin/seamonkey
}

menu "Multimedia" applications-multimedia {
  prog "VLC"          vlc     redstone-9x-vlc
  prog "SMPlayer"     smplayer  /home/metsatron/.guix-extra-profiles/room-gaming/room-gaming/bin/smplayer
  prog "Audacious" winamp  audacious
}

menu "Office" applications-office {
  prog "AbiWord"       abiword                   abiword
  prog "Gnumeric"      gnumeric                  gnumeric
  separator
  prog "LibreOffice"          libreoffice-startcenter  /home/metsatron/.guix-extra-profiles/room-gaming/room-gaming/bin/soffice
  prog "LibreOffice Writer"   libreoffice-writer       /home/metsatron/.guix-extra-profiles/room-gaming/room-gaming/bin/soffice --writer
  prog "LibreOffice Calc"     libreoffice-calc         /home/metsatron/.guix-extra-profiles/room-gaming/room-gaming/bin/soffice --calc
  prog "LibreOffice Impress"  libreoffice-impress      /home/metsatron/.guix-extra-profiles/room-gaming/room-gaming/bin/soffice --impress
  prog "LibreOffice Draw"     libreoffice-draw         /home/metsatron/.guix-extra-profiles/room-gaming/room-gaming/bin/soffice --draw
  prog "LibreOffice Base"     libreoffice-base         /home/metsatron/.guix-extra-profiles/room-gaming/room-gaming/bin/soffice --base
  prog "LibreOffice Math"     libreoffice-math         /home/metsatron/.guix-extra-profiles/room-gaming/room-gaming/bin/soffice --math
}

menu "Terminals" utilities-terminal {
  prog "Windows PowerShell"  utilities-terminal  bash /home/metsatron/.local/bin/redstone-9x-run xterm -class redstone-powershell -title PowerShell -geometry 80x25 -fa "Consolas" -fs 11 -bg "#012456" -fg "#EEEDF0" -cr "#EEEDF0" -e /home/metsatron/.local/bin/redstone-9x-pwsh
  prog "Zsh"                 utilities-terminal  /home/metsatron/.local/bin/redstone-9x-zsh --window
  prog "Bash"                utilities-terminal  /home/metsatron/.local/bin/redstone-9x-bash --window
  prog "Command Prompt"      utilities-terminal  bash /home/metsatron/.local/bin/redstone-9x-run urxvt -hold -name redstone-bash-cmd -title "Command Prompt" -geometry 80x25 +sb -bg rgb:0c/0c/0c -fg rgb:cc/cc/cc -cr rgb:cc/cc/cc -fn "xft:Lucida Console:pixelsize=14:antialias=true" -e bash -lc 'exec wine cmd.exe'
  prog "Bash (CMD frame)"    utilities-terminal  bash /home/metsatron/.local/bin/redstone-9x-run urxvt -name redstone-bash-cmd -title "Command Prompt" -geometry 80x25 +sb -bg rgb:0c/0c/0c -fg rgb:cc/cc/cc -cr rgb:cc/cc/cc -fn "xft:Lucida Console:pixelsize=14:antialias=true" -e bash
  prog "URxVT"               utilities-terminal  bash /home/metsatron/.local/bin/redstone-9x-run urxvt -name redstone-plain-urxvt -title "URxVT" -geometry 80x25 +sb -bg rgb:00/00/00 -fg rgb:d6/d3/ce -cr rgb:d6/d3/ce -fn "xft:Courier New:size=11:antialias=true,xft:monospace:size=11:antialias=true"
  prog "XTerm"               utilities-terminal  bash /home/metsatron/.local/bin/redstone-9x-run xterm -title "XTerm" -geometry 80x25
}

menu "MS-DOS" ms-dos-prompt {
  prog "MS-DOS Prompt"  ms-dos-prompt  bash /home/metsatron/.local/bin/redstone-9x-run xterm -title "MS-DOS Prompt" -geometry 80x25 -fa "Perfect DOS VGA 437 Win" -fs 11 -bg black -fg "#c0c0c0" -e /home/metsatron/.local/bin/redstone-9x-dosemu2-shell
  prog "DOSBox-X"       ms-dos-prompt  /home/metsatron/.local/bin/redstone-9x-dosbox-x
}

# Wine APPLICATIONS live here; Wine SETTINGS live under Settings > Wine.
menu "Wine" wine {
  menu "Accessories" wine {
    prog "Windows Explorer"   wine  redstone-9x-wine explorer
    prog "File Manager"       wine  redstone-9x-wine winefile
    prog "Notepad"            wine  redstone-9x-wine notepad
    prog "WordPad"            wine  redstone-9x-wine wordpad
    prog "Command Prompt"     wine  redstone-9x-wine cmd
    prog "Minesweeper (Wine)" wine  redstone-9x-wine winemine
    prog "Windows Help"       wine  redstone-9x-wine winhlp32
  }
  menu "Internet" wine {
    prog "Internet Explorer"  wine  redstone-9x-ie
  }
  prog "Task Manager"           wine  redstone-9x-wine taskmgr
  prog "OLE/COM Object Viewer"  wine  redstone-9x-wine oleview
}

separator

menu "Rofi Tools" system-search {
  prog "Run command"          system-run          redstone-9x-rofi-run
  prog "Desktop apps"         applications-system redstone-9x-rofi-desktop
  prog "Application launcher" applications-system redstone-9x-rofi-launcher
  prog "Emoji"                accessories-character-map redstone-9x-rofi-emoji
  prog "Clipboard"            edit-paste          redstone-9x-rofi-clipboard
  prog "Local executables"    system-run          redstone-9x-rofi-local-bin
}
}

# Win95's Documents menu was RECENT DOCUMENTS, not a folder shortcut — the
# menuprog regenerates it from recently-used.xbel on every open (BobC's antiX
# dynamic-menu idea, Redstone-ised). Desktop mirrors ~/Desktop as a menu.
menuprog "Documents" user-home redstone-9x-menu-recent
menuprog "Desktop" user-desktop redstone-9x-menu-desktop

menu "Themes" preferences-desktop-theme {
  prog "Windows 95"           preferences-desktop-theme  redstone-9x-scheme-apply windows-95
  prog "SerenityOS"           preferences-desktop-theme  redstone-9x-scheme-apply serenity
  separator
  prog "Windows 3.1"          preferences-desktop-theme  redstone-9x-scheme-apply windows-3x
  prog "Windows 98"           preferences-desktop-theme  redstone-9x-scheme-apply windows-98
  prog "Windows 2000"         preferences-desktop-theme  redstone-9x-scheme-apply windows-2000
  prog "Windows XP"           preferences-desktop-theme  redstone-9x-scheme-apply windows-xp
  separator
  menu "Windows 98 Plus!" preferences-desktop-theme {
    prog "Baseball"             preferences-desktop-theme  redstone-9x-scheme-apply plus-baseball
    prog "Dangerous Creatures"  preferences-desktop-theme  redstone-9x-scheme-apply plus-dangerous-creatures
    prog "Inside your Computer" preferences-desktop-theme  redstone-9x-scheme-apply plus-inside-your-computer
    prog "Jungle"               preferences-desktop-theme  redstone-9x-scheme-apply plus-jungle
    prog "Leonardo da Vinci"    preferences-desktop-theme  redstone-9x-scheme-apply plus-leonardo-da-vinci
    prog "More Windows"         preferences-desktop-theme  redstone-9x-scheme-apply plus-more-windows
    prog "Mystery"              preferences-desktop-theme  redstone-9x-scheme-apply plus-mystery
    prog "Nature"               preferences-desktop-theme  redstone-9x-scheme-apply plus-nature
    prog "Science"              preferences-desktop-theme  redstone-9x-scheme-apply plus-science
    prog "Space"                preferences-desktop-theme  redstone-9x-scheme-apply plus-space
    prog "Sports"               preferences-desktop-theme  redstone-9x-scheme-apply plus-sports
    prog "The 60's USA"         preferences-desktop-theme  redstone-9x-scheme-apply plus-60s-usa
    prog "The Golden Era"       preferences-desktop-theme  redstone-9x-scheme-apply plus-golden-era
    prog "Travel"               preferences-desktop-theme  redstone-9x-scheme-apply plus-travel
    prog "Underwater"           preferences-desktop-theme  redstone-9x-scheme-apply plus-underwater
    prog "Windows 98 Plus"      preferences-desktop-theme  redstone-9x-scheme-apply plus-windows-98
  }
  menu "SerenityOS Themes" preferences-desktop-theme {
    prog "Basalt"           preferences-desktop-theme  redstone-9x-scheme-apply serenity-basalt
    prog "CakePlacid"       preferences-desktop-theme  redstone-9x-scheme-apply serenity-cakeplacid
    prog "Catppuccin Frappe" preferences-desktop-theme  redstone-9x-scheme-apply serenity-catppuccin-frappe
    prog "Catppuccin Latte" preferences-desktop-theme  redstone-9x-scheme-apply serenity-catppuccin-latte
    prog "Catppuccin Macchiato" preferences-desktop-theme  redstone-9x-scheme-apply serenity-catppuccin-macchiato
    prog "Catppuccin Mocha" preferences-desktop-theme  redstone-9x-scheme-apply serenity-catppuccin-mocha
    prog "Chillychilly"     preferences-desktop-theme  redstone-9x-scheme-apply serenity-chillychilly
    prog "Coffee"           preferences-desktop-theme  redstone-9x-scheme-apply serenity-coffee
    prog "Contrast"         preferences-desktop-theme  redstone-9x-scheme-apply serenity-contrast
    prog "Cupertino"        preferences-desktop-theme  redstone-9x-scheme-apply serenity-cupertino
    prog "Dark"             preferences-desktop-theme  redstone-9x-scheme-apply serenity-dark
    prog "Default"          preferences-desktop-theme  redstone-9x-scheme-apply serenity-default
    prog "Desert"           preferences-desktop-theme  redstone-9x-scheme-apply serenity-desert
    prog "Durrque"          preferences-desktop-theme  redstone-9x-scheme-apply serenity-durrque
    prog "Faux Pas"         preferences-desktop-theme  redstone-9x-scheme-apply serenity-faux-pas
    prog "Gruvbox Dark"     preferences-desktop-theme  redstone-9x-scheme-apply serenity-gruvbox-dark
    prog "Hotdog Stand"     preferences-desktop-theme  redstone-9x-scheme-apply serenity-hotdog-stand
    prog "Light"            preferences-desktop-theme  redstone-9x-scheme-apply serenity-light
    prog "NonDurrque"       preferences-desktop-theme  redstone-9x-scheme-apply serenity-nondurrque
    prog "Nord"             preferences-desktop-theme  redstone-9x-scheme-apply serenity-nord
    prog "Olive"            preferences-desktop-theme  redstone-9x-scheme-apply serenity-olive
    prog "Plum"             preferences-desktop-theme  redstone-9x-scheme-apply serenity-plum
    prog "Pumpkin"          preferences-desktop-theme  redstone-9x-scheme-apply serenity-pumpkin
    prog "Redmond"          preferences-desktop-theme  redstone-9x-scheme-apply serenity-redmond
    prog "Redmond 2000"     preferences-desktop-theme  redstone-9x-scheme-apply serenity-redmond-2000
    prog "Redmond Glass"    preferences-desktop-theme  redstone-9x-scheme-apply serenity-redmond-glass
    prog "Redmond Plastic"  preferences-desktop-theme  redstone-9x-scheme-apply serenity-redmond-plastic
    prog "Redmond Zehn"     preferences-desktop-theme  redstone-9x-scheme-apply serenity-redmond-zehn
    prog "Scarlett"         preferences-desktop-theme  redstone-9x-scheme-apply serenity-scarlett
    prog "Silver"           preferences-desktop-theme  redstone-9x-scheme-apply serenity-silver
    prog "Sunshine"         preferences-desktop-theme  redstone-9x-scheme-apply serenity-sunshine
    prog "Valve"            preferences-desktop-theme  redstone-9x-scheme-apply serenity-valve
  }
  separator
  menu "Window Borders Only" preferences-desktop-theme {
    prog "Windows 95"           preferences-desktop-theme  sh -c 'echo "Theme=\"Windows-95\"" > ~/.icewm/theme; icewm -r'
    prog "Serenity"             preferences-desktop-theme  sh -c 'echo "Theme=\"Serenity\"" > ~/.icewm/theme; icewm -r'
    prog "Windows 2000"         preferences-desktop-theme  sh -c 'echo "Theme=\"Win2kmod-xpm\"" > ~/.icewm/theme; icewm -r'
    prog "Windows 2000 (XP)"    preferences-desktop-theme  sh -c 'echo "Theme=\"Win2kmod-xpm-xp\"" > ~/.icewm/theme; icewm -r'
    prog "Win2k (mod colours)"  preferences-desktop-theme  sh -c 'echo "Theme=\"Win2kmod-xpm-modcolors\"" > ~/.icewm/theme; icewm -r'
    prog "Win2k (dark borders)" preferences-desktop-theme  sh -c 'echo "Theme=\"Win2kmod-xpm-dborders\"" > ~/.icewm/theme; icewm -r'
    prog "Win2k (original)"     preferences-desktop-theme  sh -c 'echo "Theme=\"Win2kmod-xpm-og\"" > ~/.icewm/theme; icewm -r'
  }
}

menu "Settings" control-center2 {
prog "Control Panel"  redstone-control-panel  control
separator
menu "Control Panel Applets" preferences-system {
  prog "Device Manager"  audio-card   devmgmt
  prog "System"          redstone-system            sysdmcpl
  prog "Display"         video-display   deskcpl
}
menu "IceWM" preferences-desktop {
  menu "Focus" preferences-desktop {
    prog "Click to Focus"     preferences-desktop  sh -c 'sed -i /^FocusMode=/d ~/.icewm/prefoverride 2>/dev/null; echo FocusMode=1 >> ~/.icewm/prefoverride; icewm -r'
    prog "Sloppy Mouse Focus" preferences-desktop  sh -c 'sed -i /^FocusMode=/d ~/.icewm/prefoverride 2>/dev/null; echo FocusMode=2 >> ~/.icewm/prefoverride; icewm -r'
    prog "Explicit Focus"     preferences-desktop  sh -c 'sed -i /^FocusMode=/d ~/.icewm/prefoverride 2>/dev/null; echo FocusMode=3 >> ~/.icewm/prefoverride; icewm -r'
  }
  prog "Appearance"        preferences-desktop-theme  lxappearance
  prog "Edit IceWM Config" text-editor                mousepad /home/metsatron/.icewm/preferences
  prog "Restart IceWM"     reload                     icewm --restart
}
menu "PCManFM" system-file-manager {
  prog "Desktop Preferences"  preferences-desktop        pcmanfm --desktop-pref
  prog "Snap Icons to Grid"   preferences-desktop-theme  redstone-9x-icons-grid
}
menu "Wine" wine {
  prog "Configure Wine"       wine  redstone-9x-wine winecfg
  prog "Winetricks"           wine  redstone-9x-wine winetricks
  prog "Registry Editor"      wine  redstone-9x-wine regedit
  prog "Add/Remove Programs"  wine  redstone-9x-wine uninstall
  prog "Control Panel (Wine)" wine  redstone-9x-wine control
  prog "Restart Wine"         wine  redstone-9x-wine wineboot
}
prog "Qt Appearance"  preferences-desktop-theme  qt6ct
separator
prog "About Windows"  help-browser  ice2kver
}

menu "Find" lxfind {
prog "Files or Folders..."  lxfind  fsearch
prog "Computer..."          lxfind  fsearch
}

prog "Help" help-browser env QT_QPA_PLATFORMTHEME=qt6ct QT_PLUGIN_PATH=@ROOM_QT6_PLUGINS@ SSL_CERT_FILE=@DESKTOP_COMMON_SSL_CERT@ QTWEBENGINE_CHROMIUM_FLAGS=--disable-gpu DBUS_SYSTEM_BUS_ADDRESS=unix:path=/run/host/run/dbus/system_bus_socket zeal

separator

prog "Run..." system-run runbox

separator

# Single item, like Windows 95 — ends the session (logs you off). icewm 4.0 has NO
# --shutdown/--logout flag (only --restart/--replace), so the old `icewm --shutdown`
# was a silent no-op — the real reason "Shut Down does nothing". icewm-session
# supervises icewmbg/icewmtray/icewm; terminating them ends the session and closes
# the Xephyr window. (The ice2k shutdlg replica needs ice2k's programs/shutdown/
# tree we don't project yet; when integrated it can live in Settings > IceWM.)
prog "Shut Down..." system-shut-down sh -c "pkill -x icewm-session; pkill -x icewm"
#+END_SRC

PCManFM desktop icon grid helper.

PCManFM exposes =Snap to Grid= as an internal desktop-context action, not as
a command-line option.  This helper gives the IceWM menu an equivalent
all-icons action: stop the desktop layer, preserve a timestamped copy of its
position file, snap only desktop-icon coordinates to Redstone's 80-pixel grid,
then start the desktop layer again.  It does not enable auto-arrange, so later
manual movement remains possible.

#+BEGIN_SRC bash :tangle linux/.local/bin/redstone-9x-icons-grid :shebang "#!/usr/bin/env bash" :tangle-mode (identity #o755)
set -euo pipefail

usage() {
  cat <<'EOF'
redstone-9x-icons-grid - snap PCManFM desktop icons to Redstone's grid

Usage: redstone-9x-icons-grid
       redstone-9x-icons-grid -h | --help

Stops the PCManFM desktop layer, backs up desktop-items-0.conf, rounds desktop
icon x/y coordinates to the nearest 80 pixels, and starts the desktop again.
EOF
}

case "${1:-}" in
  -h|--help)
    usage
    exit 0
    ;;
  "")
    ;;
  *)
    usage >&2
    exit 2
    ;;
esac

if (( $# > 1 )); then
  usage >&2
  exit 2
fi

config_home="${XDG_CONFIG_HOME:-${HOME}/.config}"
config="${config_home}/pcmanfm/default/desktop-items-0.conf"
cache_dir="${XDG_CACHE_HOME:-${HOME}/.cache}/redstone-9x"
grid=80

if [[ ! -f "${config}" ]]; then
  printf 'redstone-9x-icons-grid: PCManFM desktop config not found: %s\n' "${config}" >&2
  exit 1
fi

mkdir -p "${cache_dir}"
backup="${config}.backup-$(date +%Y%m%d-%H%M%S)-$$"
temp="$(mktemp "${config}.tmp.XXXXXX")"
restart_needed=0

cleanup() {
  [[ -z "${temp:-}" ]] || rm -f -- "${temp}"
  if (( restart_needed )); then
    pcmanfm --desktop >"${cache_dir}/pcmanfm-desktop.log" 2>&1 &
  fi
}
trap cleanup EXIT

pcmanfm --desktop-off >/dev/null 2>&1
restart_needed=1
sleep 0.5

cp -p -- "${config}" "${backup}"

awk -v grid="${grid}" '
function snap(value) {
  if (value >= 0) return int((value + grid / 2) / grid) * grid
  return -int((-value + grid / 2) / grid) * grid
}

/^\[/ {
  in_desktop_icon = ($0 ~ /^\[[^]]+\.desktop\]$/)
}

in_desktop_icon && /^x=-?[0-9]+$/ {
  sub(/^x=/, "")
  print "x=" snap($0 + 0)
  next
}

in_desktop_icon && /^y=-?[0-9]+$/ {
  sub(/^y=/, "")
  print "y=" snap($0 + 0)
  next
}

{ print }
' "${config}" >"${temp}"

chmod --reference="${config}" "${temp}"
mv -f -- "${temp}" "${config}"
temp=""

pcmanfm --desktop >"${cache_dir}/pcmanfm-desktop.log" 2>&1 &
restart_needed=0
trap - EXIT

printf 'Desktop icons snapped to a %s-pixel grid. Backup: %s\n' "${grid}" "${backup}"
#+END_SRC

IceWM quick-launch toolbar (the strip at the left of the taskbar).  Each
line is =prog "label" icon command=; icons resolve via the projected
Chicago95 theme.  Tooltips come from the label.

#+BEGIN_SRC conf :tangle linux/.icewm/toolbar
# Redstone 9X — IceWM quick-launch strip: the default-app quartet (Terminal /
# File Manager / Web Browser / Editor, SerenityOS-style) + Audacious.
# One File Manager only (pcmanfm). xclass Explorer lives in the Start menu,
# not here, to avoid a redundant second file-manager button.
prog "Terminal"       utilities-terminal    /home/metsatron/.local/bin/redstone-9x-bash --window
prog "File Manager"   system-file-manager   pcmanfm
prog "Web Browser"    firefox_2             firefox
prog "Text Editor"    text-editor           mousepad
prog "Audacious"      winamp                audacious
#+END_SRC

** Dynamic menus — recent Documents + Desktop folder

Win95's Start→Documents was a *recent documents* menu; ours was a folder shortcut. IceWM's =menuprog= regenerates a submenu by running a script on every open (the antiX/BobC pattern from =~/Downloads/icewm-menu-7=, rewritten for Redstone). Icons must be names IceWM can actually resolve — an unresolvable icon silently drops the whole entry — so both scripts pick from the grafted set and fall back to =folder=.

#+BEGIN_SRC bash :tangle linux/.local/bin/redstone-9x-menu-recent :shebang "#!/bin/sh" :tangle-mode (identity #o755)
# Emit IceWM menu entries for recent documents (Win95 Start->Documents).
# Reads recently-used.xbel (GTK apps maintain it); newest first, capped.
XBEL="${XDG_DATA_HOME:-$HOME/.local/share}/recently-used.xbel"
ICONDIR="${HOME}/.icewm/icons"
MAX=15

if [ ! -f "${XBEL}" ]; then
  echo 'prog "(no recent documents)" folder true'
  exit 0
fi

icon_for() {
  case "$(printf %s "$1" | tr "[:upper:]" "[:lower:]")" in
    *.txt|*.md|*.org|*.conf|*.ini|*.log|*.sh) echo text-x-generic ;;
    *.png|*.jpg|*.jpeg|*.gif|*.bmp|*.xpm|*.webp|*.svg) echo image-x-generic ;;
    *.wav|*.mp3|*.ogg|*.flac|*.m4a|*.mod|*.it|*.s3m|*.xm|*.mid) echo audio-x-generic ;;
    *.mp4|*.mkv|*.avi|*.webm|*.mov|*.mpg) echo video-x-generic ;;
    *.pdf) echo application-pdf ;;
    *.zip|*.7z|*.rar|*.tar|*.gz|*.xz|*.zst|*.wsz) echo package-x-generic ;;
    *) echo unknown ;;
  esac
}

count=0
# hrefs appear in chronological order; newest are last — reverse with tail+tac.
grep -oE '<bookmark href="file://[^"]*"' "${XBEL}" \
  | sed -e 's|.*href="file://||' -e 's|"$||' \
  | tail -n "${MAX}" | tac \
  | while IFS= read -r enc; do
      # URL-decode the common cases (printf %b interprets \x escapes)
      path=$(printf '%b' "$(printf %s "${enc}" | sed 's/%\([0-9a-fA-F][0-9a-fA-F]\)/\\x\1/g')")
      [ -e "${path}" ] || continue
      name=$(basename "${path}" | sed 's/"/\\"/g')
      icon=$(icon_for "${path}")
      [ -f "${ICONDIR}/${icon}_16x16.png" ] || icon=folder
      printf 'prog "%s" %s xdg-open "%s"\n' "${name}" "${icon}" "${path}"
      count=$((count+1))
    done
exit 0
#+END_SRC

#+BEGIN_SRC bash :tangle linux/.local/bin/redstone-9x-menu-desktop :shebang "#!/bin/sh" :tangle-mode (identity #o755)
# Emit IceWM menu entries mirroring ~/Desktop (BobC's antiX Desktop-folder
# menu, Redstone-ised). .desktop launchers run their Exec (field codes
# stripped); plain files open via xdg-open.
DESK="${HOME}/Desktop"
ICONDIR="${HOME}/.icewm/icons"
[ -d "${DESK}" ] || exit 0

for f in "${DESK}"/*; do
  [ -e "${f}" ] || continue
  base=$(basename "${f}")
  case "${base}" in
    *.desktop)
      name=$(sed -n 's/^Name=//p' "${f}" | head -1)
      icon=$(sed -n 's/^Icon=//p' "${f}" | head -1)
      cmd=$(sed -n 's/^Exec=//p' "${f}" | head -1 | sed 's/ %[a-zA-Z]//g')
      [ -n "${name}" ] && [ -n "${cmd}" ] || continue
      [ -f "${ICONDIR}/${icon}_16x16.png" ] || icon=folder
      printf 'prog "%s" %s %s\n' "$(printf %s "${name}" | sed 's/"/\\"/g')" "${icon}" "${cmd}"
      ;;
    *)
      icon=folder
      printf 'prog "%s" %s xdg-open "%s"\n' "$(printf %s "${base}" | sed 's/"/\\"/g')" "${icon}" "${f}"
      ;;
  esac
done
exit 0
#+END_SRC

Redstone's Rofi theme is a sanctuary-local Windows 95 control surface, so its
dialog geometry and palette do not change the shared LainCore Rofi surface on
the host.  The base theme is compact and centred; the Run launcher adds a
dedicated client-area layout and asks IceWM for a real managed titlebar.

The comma before the global selector is the Org tangle escape used by the
existing Rasi sources and becomes a normal =* {= selector in the emitted file.

#+BEGIN_SRC css :tangle linux/.config/redstone-9x/rofi/Windows95.rasi :tangle-mode (identity #o644) :mkdirp yes
,* {
    win95-grey:                     #c0c0c0;
    win95-white:                    #ffffff;
    win95-shadow:                   #808080;
    win95-black:                    #000000;
    win95-navy:                     #000080;

    background:                     @win95-grey;
    foreground:                     @win95-black;
    normal-background:              @win95-white;
    normal-foreground:              @win95-black;
    alternate-normal-background:    @win95-white;
    alternate-normal-foreground:    @win95-black;
    alternate-urgent-background:    @win95-white;
    alternate-urgent-foreground:    @win95-black;
    alternate-active-background:    @win95-white;
    alternate-active-foreground:    @win95-black;
    selected-normal-background:     @win95-navy;
    selected-normal-foreground:     @win95-white;
    urgent-background:              @win95-white;
    urgent-foreground:              @win95-black;
    selected-urgent-background:     @win95-navy;
    selected-urgent-foreground:     @win95-white;
    active-background:              @win95-white;
    active-foreground:              @win95-black;
    selected-active-background:     @win95-navy;
    selected-active-foreground:     @win95-white;
    spacing:                         4px;
}
/* Win95 raised window edge (NOT a flat black outline): the 2-tone 3D bevel is
   faked across the two nested widgets exactly like the Run-box buttons — the
   highlight (white, top/left) on the inner #mainbox, the shadow (dark grey,
   bottom/right) on the outer #window.  rofi clips an inner widget's bottom
   border, so the shadow must live on the outer frame. */
#window {
    background-color: @background;
    font: "Tahoma 8";
    border: 0px 2px 2px 0px;
    border-color: @win95-shadow;
    padding: 0px;
    width: 440px;
    height: 360px;
    location: center;
    anchor: center;
    margin: 0px;
}
#mainbox {
    background-color: @background;
    border: 2px 0px 0px 2px;
    border-color: @win95-white;
    padding: 5px;
    spacing: 5px;
}
#message {
    background-color: @background;
    border: 0px;
    padding: 4px 6px;
}
#textbox { text-color: @foreground; }
#listview {
    fixed-height: 0;
    border: 2px;
    border-color: @win95-shadow;
    background-color: @win95-white;
    spacing: 0px;
    scrollbar: false;
    padding: 2px;
}
#element {
    border: 0px;
    padding: 3px 4px;
    spacing: 6px;
    highlight: none;
}
#element.normal.normal {
    background-color: @normal-background;
    text-color: @normal-foreground;
}
#element.normal.urgent {
    background-color: @urgent-background;
    text-color: @urgent-foreground;
}
#element.normal.active {
    background-color: @active-background;
    text-color: @active-foreground;
}
#element.selected.normal {
    background-color: @selected-normal-background;
    text-color: @selected-normal-foreground;
}
#element.selected.urgent {
    background-color: @selected-urgent-background;
    text-color: @selected-urgent-foreground;
}
#element.selected.active {
    background-color: @selected-active-background;
    text-color: @selected-active-foreground;
}
#element.alternate.normal {
    background-color: @alternate-normal-background;
    text-color: @alternate-normal-foreground;
}
#element.alternate.urgent {
    background-color: @alternate-urgent-background;
    text-color: @alternate-urgent-foreground;
}
#element.alternate.active {
    background-color: @alternate-active-background;
    text-color: @alternate-active-foreground;
}
#scrollbar {
    width: 12px;
    border: 1px;
    border-color: @win95-shadow;
    handle-width: 12px;
    padding: 1px;
}
#mode-switcher {
    border: 0px;
    spacing: 6px;
}
#button {
    background-color: @background;
    text-color: @foreground;
    border: 2px;
    border-color: @win95-white;
    padding: 3px 10px;
}
#button.selected {
    background-color: @selected-normal-background;
    text-color: @selected-normal-foreground;
    border-color: @win95-shadow;
}
#inputbar {
    background-color: @win95-white;
    border: 2px;
    border-color: @win95-shadow;
    spacing: 4px;
    text-color: @normal-foreground;
    padding: 3px 4px;
    children: [ prompt, entry, case-indicator ];
}
#case-indicator {
    spacing: 0px;
    text-color: @normal-foreground;
}
#entry {
    spacing: 0px;
    text-color: @normal-foreground;
    cursor: text;
}
#prompt {
    spacing: 0px;
    margin: 0px 6px 0px 0px;
    text-color: @normal-foreground;
}
element-icon {
    size: 16px;
}
#+END_SRC

The Run variant follows the original 350-by-160 dialog proportions.  IceWM adds
the navy titlebar around this client area; Rofi supplies the explanatory copy,
the recessed =Open:= field, and native command buttons.  The patched
=rofi-redstone= package keeps the built-in run mode alive while =Browse...=
toggles its real history/result list, preserving both entry text and Rofi's
=rofi-4.runcache= history.

#+BEGIN_SRC css :tangle linux/.config/redstone-9x/rofi/Windows95-Run.rasi :tangle-mode (identity #o644) :mkdirp yes
,* {
    font: "Tahoma 8";
    background-color: #c0c0c0;
    text-color: #000000;
    border-color: #808080;
    margin: 0px;
    padding: 0px;
    spacing: 0px;
}
window {
    width: 350px;
    height: 0px;
    padding: 8px;
    border: 0px;
    background-color: #c0c0c0;
    location: center;
    anchor: center;
    children: [ mainbox ];
}
mainbox {
    orientation: vertical;
    spacing: 8px;
    children: [ textbox-message, inputbar, listview, actions ];
}
/* NOTE: the Win95 corner Run icon and the dropdown ▼ glyph are both IMAGES, and
   this rofi 2.0.0 build does not render images inside custom theme widgets
   (filename icon, background-image — both come up blank; text renders fine). So
   the message carries no icon and the combobox button is a bare bevel. Revisit
   if rofi is rebuilt from mainline. */
textbox-message {
    content: "Type the name of a program, folder, or document, and\nRedstone will open it for you.";
    expand: false;
    background-color: #c0c0c0;
    text-color: #000000;
    padding: 0px 0px 0px 34px;
    horizontal-align: 0.0;
}
inputbar {
    orientation: horizontal;
    expand: false;
    spacing: 6px;
    children: [ textbox-open, field-combo ];
}
textbox-open {
    content: "Open:";
    expand: false;
    vertical-align: 0.5;
    background-color: transparent;
    text-color: #000000;
}
/* Win95 combobox field. The dropdown chevron button was removed: rofi cannot
   render a real ▼ glyph inside the inputbar (a font glyph and a background-image
   triangle both fail there), so a blank beveled button just read as junk. The Run
   history is still reachable by keyboard (Down / Alt+Down / F4), exactly like the
   real Open: combobox. */
field-combo {
    orientation: horizontal;
    expand: true;
    spacing: 0px;
    children: [ entry-frame ];
}
/* Sunken Win95 field: rofi border-color is single-colour, so the 2-tone bevel
   is faked with per-side widths — dark top/left on the frame, light bottom/right
   on the inner entry. */
entry-frame {
    orientation: horizontal;
    expand: true;
    background-color: #ffffff;
    border: 2px 0px 0px 2px;
    border-color: #808080;
    padding: 0px;
    children: [ entry ];
}
entry {
    expand: true;
    background-color: #ffffff;
    text-color: #000000;
    border: 0px 2px 2px 0px;
    border-color: #ffffff;
    padding: 2px 3px;
}
listview {
    enabled: false;
    expand: false;
    lines: 8;
    fixed-height: true;
    dynamic: false;
    scrollbar: true;
    background-color: #ffffff;
    text-color: #000000;
    border: 2px;
    border-color: #808080;
    padding: 1px;
}
element {
    padding: 3px 5px;
    background-color: #ffffff;
    text-color: #000000;
}
element selected.normal {
    background-color: #000080;
    text-color: #ffffff;
}
element-text {
    background-color: inherit;
    text-color: inherit;
}
scrollbar {
    handle-color: #808080;
    handle-width: 8px;
}
/* Real Win95 Run buttons are compact and RIGHT-aligned, not stretched across the
   dialog.  An expanding filler on the left pushes the three fixed-width buttons
   to the right edge; each button is a fixed 72px like the genuine dialog. */
actions {
    orientation: horizontal;
    expand: true;
    spacing: 6px;
    children: [ actions-filler, ok-frame, cancel-frame, browse-frame ];
}
actions-filler {
    expand: true;
    background-color: #c0c0c0;
}
/* Raised Win95 buttons: 2-tone bevel from single-colour per-side borders.  Each
   edge sits on the widget that renders it fully — the shadow (bottom/right) on
   the OUTER frame, the highlight (top/left) on the INNER button.  (rofi clips an
   inner widget's bottom border, so the shadow must live on the outer frame.) */
ok-frame,cancel-frame,browse-frame {
    expand: false;
    background-color: #c0c0c0;
    border: 0px 2px 2px 0px;
    border-color: #808080;
    padding: 0px;
}
button-ok,button-cancel,button-browse {
    expand: false;
    width: 72px;
    background-color: #c0c0c0;
    text-color: #000000;
    border: 2px 0px 0px 2px;
    border-color: #ffffff;
    padding: 3px 0px;
    vertical-align: 0.5;
    horizontal-align: 0.5;
    cursor: pointer;
}
ok-frame {
    children: [ button-ok ];
}
cancel-frame {
    children: [ button-cancel ];
}
browse-frame {
    children: [ button-browse ];
}
button-ok {
    content: "OK";
    action: "kb-accept-custom";
}
button-cancel {
    content: "Cancel";
    action: "kb-cancel";
}
button-browse {
    content: "Browse...";
    action: "kb-custom-1";
}
#+END_SRC

The companion configuration imports that theme for Rofi callers that do not pass a
theme explicitly, including the emoji selector.

#+BEGIN_SRC css :tangle linux/.config/redstone-9x/rofi/config.rasi :tangle-mode (identity #o644) :mkdirp yes
@import "~/.config/redstone-9x/rofi/Windows95.rasi"

configuration {
    modi: "drun,run,window";
    show-icons: false;
}
#+END_SRC

#+BEGIN_SRC conf :tangle linux/.icewm/keys :tangle-mode (identity #o644)
# Redstone 9X — the host owns Super-key grabs, so launcher commands live in
# the IceWM Rofi Shortcuts menu instead of competing with the host desktop.
#+END_SRC

The Rofi Run/launcher dialogs are stock-rofi ~-normal-window~ clients, so IceWM
decorates them.  These winoptions frame them as authentic Windows 95 dialog
boxes — a titlebar carrying the system menu and Close button only, with no
maximise, minimise, or resize — matching how a real Win95 =Run= box behaves.
Rofi's WM_CLASS is instance ~rofi~, class ~Rofi~; the launcher additionally
=icesh -c Rofi center=s the window because Rofi ignores its own theme location
under ~-normal-window~.

#+BEGIN_SRC conf :tangle linux/.icewm/winoptions :tangle-mode (identity #o644)
# Redstone 9X — IceWM per-window options for the Rofi Win95 dialogs.
# Match on the Rofi window class (instance "rofi", class "Rofi").
Rofi.dTitleBar: 1
Rofi.dSysMenu: 1
Rofi.dClose: 1
Rofi.dBorder: 1
Rofi.dResize: 0
Rofi.dMaximize: 0
Rofi.dMinimize: 0
Rofi.dDepth: 0
Rofi.dRollup: 0
Rofi.fResize: 0
Rofi.fMaximize: 0
Rofi.fMinimize: 0
#+END_SRC

#+BEGIN_SRC bash :tangle linux/.local/bin/redstone-9x-rofi-run :shebang "#!/bin/bash" :tangle-mode (identity #o755)
GUIX_PROFILE="$HOME/.guix-extra-profiles/desktop-common/desktop-common"; export GUIX_PROFILE
[ -r "$GUIX_PROFILE/etc/profile" ] && . "$GUIX_PROFILE/etc/profile"
GUIX_PROFILE="$HOME/.guix-extra-profiles/room-gaming/room-gaming"; export GUIX_PROFILE
[ -r "$GUIX_PROFILE/etc/profile" ] && . "$GUIX_PROFILE/etc/profile"
set -euo pipefail
runtime="${XDG_RUNTIME_DIR:-${TMPDIR:-/tmp}}"
pidfile="$runtime/rofi-run95-$(id -u).pid"
config="$HOME/.config/redstone-9x/rofi/config.rasi"
theme="$HOME/.config/redstone-9x/rofi/Windows95-Run.rasi"
histfile="$HOME/.cache/redstone-9x/run-history"
mkdir -p "$(dirname "$histfile")"
: >>"$histfile"

case "${1-}" in
  --check-theme)
    exec rofi -no-config -theme "$theme" -dump-theme
    ;;
esac

# --- Why -dmenu, not run mode (rofi 2.0.0, verified 2026-07-18) ---------------
# rofi fires a themed button's `action:` on MOUSE CLICK only in -dmenu mode; in
# -modes run / -show run the click is silently swallowed, so the Browse and
# dropdown buttons were dead however they were styled. So the box is driven as
# -dmenu and this wrapper runs the accepted command itself — which also matches
# the real Win95 Run box, that does not autocomplete. The Run history IS the
# -dmenu row list, fed on stdin; it stays hidden (listview enabled:false) until
# the ▼ dropdown reveals it. A trailing blank line is always fed as a guard:
# clicking any button while the dmenu list is EMPTY segfaults rofi, so >=1 row
# must always be present.
#
# Button -> exit code -> handled below (no rofi binary patch):
#   Return / OK  (kb-accept-custom) -> exit 0  -> run the typed/selected command
#   Browse...    (button-browse -> kb-custom-1) -> exit 10 -> drun app launcher
#   ▼ dropdown   (combo-button  -> kb-custom-2) -> exit 11 -> reveal Run history
#   Cancel / Esc (kb-cancel)                    -> exit 1  -> do nothing
#
# Once IceWM maps the Rofi window, retitle it ("Run", not "rofi - Run") and
# centre it — rofi ignores its own theme location under -normal-window, so IceWM
# would otherwise pin it top-left and clip the titlebar. The map + WM handshake
# outruns a fixed delay, so poll (icesh ships with IceWM).
_frame_rofi() {
  local title="$1"
  ( for _i in $(seq 1 50); do
      if icesh -c Rofi list 2>/dev/null | grep -q Rofi; then
        icesh -c Rofi setWindowTitle "${title}" 2>/dev/null
        icesh -c Rofi center 2>/dev/null
        break
      fi
      sleep 0.08
    done ) &
}

# Most-recent-first, de-duplicated, non-blank history rows.
_history_rows() { tac "$histfile" 2>/dev/null | awk 'NF && !seen[$0]++'; }

# Prepend a command to the history (dedup, cap 50). Never fails the script.
_record() {
  local c="$1"
  [ -z "$c" ] && return 0
  { printf '%s\n' "$c"; grep -vxF "$c" "$histfile" 2>/dev/null || true; } \
    | awk 'NF' | head -n 50 >"$histfile.tmp" 2>/dev/null \
    && mv "$histfile.tmp" "$histfile" 2>/dev/null || true
  return 0
}

view="run"
while : ; do
  args=( -dmenu -normal-window -config "$config" -theme "$theme"
         -kb-accept-entry "Control+j,Control+m"
         -kb-accept-custom "Return,KP_Enter,Control+Return"
         -pid "$pidfile" )
  if [ "$view" = history ]; then
    # ▼ dropdown view: reveal the history list, hide the chevron (list is open).
    # Down navigates the list here (rofi default), so no key override.
    args+=( -theme-str 'listview { enabled: true; }'
            -theme-str 'combo-frame { enabled: false; }' )
    _frame_rofi "Run history"
  else
    # Run view: Down / Alt+Down / F4 open the dropdown, exactly like a real Win95
    # combobox. Move row-down off Down first (the list is hidden here, so row
    # navigation is unused) — rofi rejects a key bound to two actions.
    args+=( -kb-row-down "Control+n"
            -kb-custom-2 "Down,Alt+Down,F4" )
    _frame_rofi "Run"
  fi

  rc=0
  cmd="$( { _history_rows; printf '\n'; } | rofi "${args[@]}" )" || rc=$?

  case "$rc" in
    10)
      # Browse... -> the drun application launcher (a normal rofi window so its
      # listview grows without the -normal-window fixed-height oscillation).
      exec rofi -config "$config" -show drun -show-icons -display-drun "Programs"
      ;;
    11)
      view="history"
      continue
      ;;
    0)
      if printf '%s' "$cmd" | grep -q '[^[:space:]]'; then
        _record "$cmd"
        setsid bash -c "$cmd" >/dev/null 2>&1 &
      fi
      break
      ;;
    *)
      break
      ;;
  esac
done
#+END_SRC

#+BEGIN_SRC bash :tangle linux/.local/bin/redstone-9x-rofi-desktop :shebang "#!/bin/bash" :tangle-mode (identity #o755)
GUIX_PROFILE="$HOME/.guix-extra-profiles/desktop-common/desktop-common"; export GUIX_PROFILE
[ -r "$GUIX_PROFILE/etc/profile" ] && . "$GUIX_PROFILE/etc/profile"
GUIX_PROFILE="$HOME/.guix-extra-profiles/room-gaming/room-gaming"; export GUIX_PROFILE
[ -r "$GUIX_PROFILE/etc/profile" ] && . "$GUIX_PROFILE/etc/profile"
set -euo pipefail
exec rofi -config "$HOME/.config/redstone-9x/rofi/config.rasi" -show drun -no-show-icons "$@"
#+END_SRC

#+BEGIN_SRC bash :tangle linux/.local/bin/redstone-9x-rofi-launcher :shebang "#!/bin/bash" :tangle-mode (identity #o755)
GUIX_PROFILE="$HOME/.guix-extra-profiles/desktop-common/desktop-common"; export GUIX_PROFILE
[ -r "$GUIX_PROFILE/etc/profile" ] && . "$GUIX_PROFILE/etc/profile"
GUIX_PROFILE="$HOME/.guix-extra-profiles/room-gaming/room-gaming"; export GUIX_PROFILE
[ -r "$GUIX_PROFILE/etc/profile" ] && . "$GUIX_PROFILE/etc/profile"
set -euo pipefail
exec rofi -config "$HOME/.config/redstone-9x/rofi/config.rasi" -show drun -show-icons "$@"
#+END_SRC

#+BEGIN_SRC bash :tangle linux/.local/bin/redstone-9x-rofi-emoji :shebang "#!/bin/bash" :tangle-mode (identity #o755)
GUIX_PROFILE="$HOME/.guix-extra-profiles/desktop-common/desktop-common"; export GUIX_PROFILE
[ -r "$GUIX_PROFILE/etc/profile" ] && . "$GUIX_PROFILE/etc/profile"
GUIX_PROFILE="$HOME/.guix-extra-profiles/room-gaming/room-gaming"; export GUIX_PROFILE
[ -r "$GUIX_PROFILE/etc/profile" ] && . "$GUIX_PROFILE/etc/profile"
set -euo pipefail
# rofimoji is a host user package. Its pure-Python payload is visible through
# /run/host; xdotool is likewise a host X utility, so expose that directory.
export PATH="/run/host/usr/bin:$PATH"
export XDG_CONFIG_HOME="$HOME/.config/redstone-9x"
for site in /run/host/home/metsatron/.local/lib/python*/site-packages; do
    [ -d "$site/picker" ] || continue
    export PYTHONPATH="$site${PYTHONPATH:+:$PYTHONPATH}"
    break
done
[ -f /run/host/home/metsatron/.local/bin/rofimoji ] || {
    echo "redstone-9x-rofi-emoji: host rofimoji is unavailable" >&2
    exit 127
}
exec python3 /run/host/home/metsatron/.local/bin/rofimoji --selector rofi --action type "$@"
#+END_SRC

#+BEGIN_SRC bash :tangle linux/.local/bin/redstone-9x-rofi-clipboard :shebang "#!/bin/bash" :tangle-mode (identity #o755)
GUIX_PROFILE="$HOME/.guix-extra-profiles/desktop-common/desktop-common"; export GUIX_PROFILE
[ -r "$GUIX_PROFILE/etc/profile" ] && . "$GUIX_PROFILE/etc/profile"
GUIX_PROFILE="$HOME/.guix-extra-profiles/room-gaming/room-gaming"; export GUIX_PROFILE
[ -r "$GUIX_PROFILE/etc/profile" ] && . "$GUIX_PROFILE/etc/profile"
set -euo pipefail
export XDG_CONFIG_HOME="$HOME/.config/redstone-9x"
export CM_LAUNCHER=rofi
exec clipmenu
#+END_SRC

#+BEGIN_SRC bash :tangle linux/.local/bin/redstone-9x-rofi-local-bin :shebang "#!/bin/bash" :tangle-mode (identity #o755)
GUIX_PROFILE="$HOME/.guix-extra-profiles/desktop-common/desktop-common"; export GUIX_PROFILE
[ -r "$GUIX_PROFILE/etc/profile" ] && . "$GUIX_PROFILE/etc/profile"
GUIX_PROFILE="$HOME/.guix-extra-profiles/room-gaming/room-gaming"; export GUIX_PROFILE
[ -r "$GUIX_PROFILE/etc/profile" ] && . "$GUIX_PROFILE/etc/profile"
set -euo pipefail
choice="$(
    for candidate in "$HOME/.local/bin"/*; do
        [ -f "$candidate" ] && [ -x "$candidate" ] || continue
        basename "$candidate"
    done | sort -f | rofi -config "$HOME/.config/redstone-9x/rofi/config.rasi" -dmenu -i -p "local/bin"
)"
[ -n "$choice" ] || exit 0
exec "$HOME/.local/bin/$choice"
#+END_SRC

IceWM startup hook.  Runs after =icewm-session= initialises the WM.  Starts
=pcmanfm= in desktop mode which draws Win95-style desktop icons from =~/Desktop/=.

#+BEGIN_SRC bash :tangle linux/.icewm/startup :shebang "#!/bin/sh" :tangle-mode (identity #o755)
# Redstone 9X — Win95 desktop manager
if command -v xrdb >/dev/null 2>&1; then
  xrdb -merge /home/metsatron/DotCortex/linux/.config/redstone-9x/Xresources \
    2>/dev/null || true
fi
mkdir -p "${HOME}/Desktop" "${HOME}/.cache/redstone-9x"
export XDG_CURRENT_DESKTOP="${XDG_CURRENT_DESKTOP:-LXDE}"
export GDK_BACKEND="${GDK_BACKEND:-x11}"
pcmanfm --desktop >"${HOME}/.cache/redstone-9x/pcmanfm-desktop.log" 2>&1 &

# IceWM GUI-event sounds — icesound (ships in our IceWM 4.0 build, AO backend
# with a libao pulse plugin, verified 2026-07-19). Sample dir rides the active
# sound scheme: ~/.local/share/sounds/sanctuary/icewm/ (the sanctuary symlink
# retargets per scheme; scheme-apply restarts icesound on switch). Recognised
# filenames: startup shutdown restart launchApp workspaceChange windowOpen
# windowClose dialogOpen dialogClose windowMax windowMin windowRestore
# windowRollup windowMoved windowSized windowLower windowHide (.wav each).
ICEWM_SOUNDS="${HOME}/.local/share/sounds/sanctuary/icewm"
if command -v icesound >/dev/null 2>&1 \
  && [ -n "$(ls "${ICEWM_SOUNDS}"/*.wav 2>/dev/null)" ] \
  && ! pgrep -xu "$(id -u)" icesound >/dev/null 2>&1; then
  icesound --interface=AO --sample-dir="${ICEWM_SOUNDS}" \
    >"${HOME}/.cache/redstone-9x/icesound.log" 2>&1 &
fi

# Startup chime — the desktop is coming up, which is exactly when Win95 played
# it. When the scheme ships icewm/startup.wav, icesound owns the boot chime
# and this hook yields (no double-play); otherwise sanctuary-sound covers it.
# User-supplied media in ~/.local/share/sounds/sanctuary/; silent no-op when
# absent (see sanctuary-distrobox.org "Sanctuary system sounds").
if command -v sanctuary-sound >/dev/null 2>&1 \
  && [ ! -f "${ICEWM_SOUNDS}/startup.wav" ]; then
  sanctuary-sound startup >"${HOME}/.cache/redstone-9x/sanctuary-sound.log" 2>&1 &
fi

# XSETTINGS manager — lets redstone-9x-scheme-apply restyle RUNNING GTK3 apps
# (theme/icons/cursor/font) with a SIGHUP instead of requiring relaunches.
# Config is written by scheme-apply before the session starts (--boot mode).
if command -v xsettingsd >/dev/null 2>&1 \
  && [ -f "${HOME}/.config/xsettingsd/xsettingsd.conf" ] \
  && ! pgrep -xu "$(id -u)" xsettingsd >/dev/null 2>&1; then
  xsettingsd >"${HOME}/.cache/redstone-9x/xsettingsd.log" 2>&1 &
fi

# Clipboard history daemon for the Rofi Shortcuts menu.
if command -v clipmenud >/dev/null 2>&1 \
  && ! pgrep -xu "$(id -u)" clipmenud >/dev/null 2>&1; then
  clipmenud >"${HOME}/.cache/redstone-9x/clipmenud.log" 2>&1 &
fi

# Tray inhabitants: start only when available and not already running.
# PCManFM remains the desktop/background owner; these only occupy IceWM's tray.
if command -v nm-applet >/dev/null 2>&1 \
  && pgrep -x NetworkManager >/dev/null 2>&1 \
  && ! pgrep -xu "$(id -u)" nm-applet >/dev/null 2>&1; then
  nm-applet >"${HOME}/.cache/redstone-9x/nm-applet.log" 2>&1 &
fi

if command -v pnmixer >/dev/null 2>&1 \
  && ! pgrep -xu "$(id -u)" pnmixer >/dev/null 2>&1; then
  pnmixer >"${HOME}/.cache/redstone-9x/pnmixer.log" 2>&1 &
fi

# Recycle Bin icon state watcher: the static ~/Desktop/recycle-bin.desktop
# launcher has no dynamic full/empty state on its own (GVFS's native trash
# object would give us that for free, but room-gaming has no gvfs — a
# 2026-07-07 retry of plain gvfs leaked the HOST's real Trash contents into
# the sandboxed room via distrobox's /run/host bind mount — see
# redstone-9x-state-digest.md). Poll the on-disk Trash folder instead and
# rewrite Icon= directly; no new package required.
if [ -x "${HOME}/.local/bin/redstone-9x-recycle-bin-watch" ] \
  && ! pgrep -fu "$(id -u)" "redstone-9x-recycle-bin-watch" >/dev/null 2>&1; then
  "${HOME}/.local/bin/redstone-9x-recycle-bin-watch" \
    >"${HOME}/.cache/redstone-9x/recycle-bin-watch.log" 2>&1 &
fi
#+END_SRC

Recycle Bin icon-state watcher.  PCManFM's own native trash desktop object
would track full/empty state for free, but room-gaming deliberately has no
=gvfs= (it crashes =pcmanfm --desktop= — see the running registry). This
polls the plain on-disk Trash folder instead — no GVFS, no new package,
just =ls=/=sed= against a path that already exists — and rewrites the
static launcher's =Icon== key directly. =pcmanfm --desktop= already
monitors =~/Desktop/= for content changes (that's how manual icon
repositioning/renaming persists), so an in-place edit to the =.desktop=
file's icon is picked up the same way.

#+BEGIN_SRC bash :tangle linux/.local/bin/redstone-9x-recycle-bin-watch :shebang "#!/bin/bash" :tangle-mode (identity #o755)
# Redstone 9X — Recycle Bin icon state watcher.
# Toggles ~/Desktop/recycle-bin.desktop's Icon= between user-trash and
# user-trash-full to match the real on-disk Trash folder, since the static
# launcher has no dynamic state of its own (no gvfs in this room — see
# redstone-9x-state-digest.md). Plain poll loop; no inotify dependency.
set -euo pipefail

TRASH_FILES="${XDG_DATA_HOME:-${HOME}/.local/share}/Trash/files"
DESKTOP_ICON="${HOME}/Desktop/recycle-bin.desktop"

while true; do
  if [[ -d "${TRASH_FILES}" ]] && [[ -n "$(ls -A "${TRASH_FILES}" 2>/dev/null)" ]]; then
    icon="user-trash-full"
  else
    icon="user-trash"
  fi
  # Compare against the file's ACTUAL current Icon= line, not a remembered
  # in-process variable — a relaunch reprojects a fresh copy of this file
  # over top of a still-running watcher, and an in-memory "last state" would
  # never notice the reset, silently going stale (found 2026-07-07).
  if [[ -f "${DESKTOP_ICON}" ]] && ! grep -qx "Icon=${icon}" "${DESKTOP_ICON}"; then
    sed -i "s/^Icon=.*/Icon=${icon}/" "${DESKTOP_ICON}"
  fi
  sleep 3
done
#+END_SRC

Win95 desktop icon declarations.  The launcher symlinks each file individually
into =~/Desktop/= inside the isolated guest home so the directory itself remains
writable (users can drop files there).  =pcmanfm --desktop= reads =~/Desktop/=
and renders any =.desktop= file found there as a clickable desktop icon.

#+BEGIN_SRC conf :tangle linux/.icewm/desktop/my-computer.desktop
[Desktop Entry]
Version=1.0
Type=Application
Name=My Computer
Comment=Browse this computer
Exec=pcmanfm /
Icon=computer
Terminal=false
#+END_SRC

#+BEGIN_SRC conf :tangle linux/.icewm/desktop/my-documents.desktop
[Desktop Entry]
Version=1.0
Type=Application
Name=My Documents
Comment=Open personal folder
Exec=pcmanfm
Icon=user-home
Terminal=false
#+END_SRC

#+BEGIN_SRC conf :tangle linux/.icewm/desktop/recycle-bin.desktop
[Desktop Entry]
Version=1.0
Type=Application
Name=Recycle Bin
Comment=Browse the Recycle Bin
Exec=sh -c 'pcmanfm "$HOME/.local/share/Trash/files"'
Icon=user-trash
Terminal=false
#+END_SRC

#+BEGIN_SRC conf :tangle linux/.icewm/desktop/cmd.desktop
[Desktop Entry]
Version=1.0
Type=Application
Name=Command Prompt
Comment=Windows Command Prompt via Wine
Exec=bash /home/metsatron/.local/bin/redstone-9x-run urxvt -hold -name redstone-bash-cmd -title "Command Prompt" -geometry 80x25 +sb -bg rgb:0c/0c/0c -fg rgb:cc/cc/cc -cr rgb:cc/cc/cc -fn "xft:Lucida Console:pixelsize=14:antialias=true" -e bash -lc 'exec wine cmd.exe'
Icon=utilities-terminal
Terminal=false
#+END_SRC

#+BEGIN_SRC conf :tangle linux/.icewm/desktop/powershell.desktop
[Desktop Entry]
Version=1.0
Type=Application
Name=Windows PowerShell
Comment=PowerShell 7 for Linux
Exec=bash /home/metsatron/.local/bin/redstone-9x-run xterm -class redstone-powershell -title PowerShell -geometry 80x25 -fa "Consolas" -fs 11 -bg "#012456" -fg "#EEEDF0" -cr "#EEEDF0" -e /home/metsatron/.local/bin/redstone-9x-pwsh
Icon=utilities-terminal
Terminal=false
#+END_SRC

#+BEGIN_SRC conf :tangle linux/.icewm/desktop/dosemu2.desktop
[Desktop Entry]
Version=1.0
Type=Application
Name=MS-DOS Prompt
Comment=DOSEMU2 interactive DOS session
Exec=bash /home/metsatron/.local/bin/redstone-9x-run xterm -title "MS-DOS Prompt" -geometry 80x25 -fa "Perfect DOS VGA 437 Win" -fs 11 -bg black -fg "#c0c0c0" -e /home/metsatron/.local/bin/redstone-9x-dosemu2-shell
Icon=ms-dos-prompt
Terminal=false
#+END_SRC

#+BEGIN_SRC conf :tangle linux/.icewm/desktop/dosbox-x.desktop
[Desktop Entry]
Version=1.0
Type=Application
Name=DOSBox-X
Comment=DOSBox-X compatibility lane
Exec=/home/metsatron/.local/bin/redstone-9x-dosbox-x
Icon=ms-dos-prompt
Terminal=false
#+END_SRC

#+BEGIN_SRC conf :tangle linux/.icewm/desktop/firefox.desktop
[Desktop Entry]
Version=1.0
Type=Application
Name=Firefox
Comment=Firefox with Diet Netscape chrome
Exec=firefox
Icon=firefox_2
Terminal=false
#+END_SRC

* Desktop icons — the childhood reconstruction (2026-07-15)

Ultimate Doom on crispy with Mètsàtron's own CD-quality remaster of the original score
earned its place on the desktop.  Quake and the console emulators sit beside it.

Sourcing, by his ladder:

| what        | rung | where it comes from                                            |
|-------------+------+----------------------------------------------------------------|
| ZSNES       |    1 | Guix =zsnes= 2.0.12 — and it IS =github.com/xyproto/zsnes=, the |
|             |      | maintained fork (upstream ZSNES died at 1.51).  Verified.       |
| Mupen64Plus |    1 | Guix =mupen64plus-ui-console= 2.6.0                             |
| Snes9x      |    3 | Flatpak =com.snes9x.Snes9x= — absent from Guix and nonguix      |

Still to source (noted, not built — see LOGS/TODO/DotCortex.md):
- *ePSXe* — proprietary; no Guix, no nonguix, no Flatpak.  Rung 4/6: needs the Linux
  binary from epsxe.com, or a pull from an existing install.  =pcsxr= is in Guix if an
  open-source PS1 lane is ever wanted instead.
- *NEStical, no$gmb, KGen* — DOS binaries, to run under DOSBox-X.  The DOSBox-X lane
  already exists on this desktop; these need the actual DOS executables.
- *Bleem!* — via Wine, later.

** The icons are not drawn, they are excavated

Every launcher below wore =Icon=applications-games= — the same generic joystick, four
times over, which is why the desktop read as unfinished even though the launchers all
worked.  Nothing here is newly drawn.  The art was already in the tree:

| icon          | comes from                                                              |
|---------------+-------------------------------------------------------------------------|
| =ultimate-doom= | =DOOM.WAD= lump =STFST01= — the Doomguy's face, original palette          |
| =quake=         | =pak0.pak= → =gfx.wad:sb_quad= — the Quake Q                             |
| =winamp=        | his own BeOS-r5 pack: =apps/32/winamp-295.png=                          |
| =mupen64plus=   | his own BeOS-r5 pack: =extras/misc/32/N64_Cart= — an N64 cartridge      |
| =zsnes=, =snes9x= | each emulator's own logo                                              |

=game-art-extract= (sanctuary-retropie.org) pulls the WAD/PAK lumps; =icon-theme-inject --square=
scales them into Chicago95.  Both are reproducible from source — the PNGs under
=linux/.local/share/icons/Chicago95/apps/= are payload, not hand-editing.

Selection was by *legibility at 16px*, not by what looks good at 128.  The Quake Ranger's
HUD face (=gfx.wad:face1=) is the exact counterpart of the Doomguy's and was the obvious
pick — but it is dark, low-contrast art and collapses into brown mush below 32px, so the
Q logo took the slot.  The SNES and N64 *console* photos in the BeOS pack are gorgeous at
128 and unreadable grey smears at 32.  Render a candidate at every size it will actually
be used at, and look, before choosing it.

** =Exec=" must be QUOTED when the path contains spaces

A =.desktop= =Exec== line is not a shell command; the launcher runs it through
=g_shell_parse_argv=, which splits on whitespace exactly like a POSIX shell.  Every
launcher in the ports tree is named like =Ultimate Doom (MP3) (crispy).sh=, so an
unquoted =Exec== resolves =argv[0]= to =.../ports/doom/Ultimate= and the icon does
nothing at all — no error, no window, no log line.  The Ultimate Doom entry shipped
broken this way and nobody noticed, because a desktop icon that silently does nothing
looks exactly like a desktop icon nobody clicked.  Quote the path.  Spaces AND
parentheses are reserved characters in the spec.

#+BEGIN_SRC conf :tangle linux/.icewm/desktop/ultimate-doom.desktop
[Desktop Entry]
Version=1.0
Type=Application
Name=Ultimate Doom
Comment=Ultimate Doom on crispy-doom, with the CD-quality remastered soundtrack
Exec="/run/dotcortex/retropie/isos/ports/doom/Ultimate Doom (MP3) (crispy).sh"
Icon=ultimate-doom
Terminal=false
#+END_SRC

#+BEGIN_SRC conf :tangle linux/.icewm/desktop/quake.desktop
[Desktop Entry]
Version=1.0
Type=Application
Name=Quake
Comment=Quake on QuakeSpasm
Exec="/run/dotcortex/retropie/isos/ports/quake/Quake (QuakeSpasm).sh"
Icon=quake
Terminal=false
#+END_SRC

#+BEGIN_SRC conf :tangle linux/.icewm/desktop/diablo.desktop
[Desktop Entry]
Version=1.0
Type=Application
Name=Diablo
Comment=Diablo on DevilutionX
Exec="/run/dotcortex/retropie/isos/ports/diablo/Diablo (DevilutionX).sh"
Icon=diablo
Terminal=false
#+END_SRC

#+BEGIN_SRC conf :tangle linux/.icewm/desktop/hellfire.desktop
[Desktop Entry]
Version=1.0
Type=Application
Name=Diablo: Hellfire
Comment=Hellfire on DevilutionX
Exec="/run/dotcortex/retropie/isos/ports/diablo/Hellfire (DevilutionX).sh"
Icon=hellfire
Terminal=false
#+END_SRC

#+BEGIN_SRC conf :tangle linux/.icewm/desktop/theme-hospital.desktop
[Desktop Entry]
Version=1.0
Type=Application
Name=Theme Hospital
Comment=Theme Hospital on CorsixTH
Exec="/run/dotcortex/retropie/isos/ports/theme-hospital/Theme Hospital (CorsixTH).sh"
Icon=theme-hospital
Terminal=false
#+END_SRC

#+BEGIN_SRC conf :tangle linux/.icewm/desktop/duke-nukem-3d.desktop
[Desktop Entry]
Version=1.0
Type=Application
Name=Duke Nukem 3D
Comment=Duke Nukem 3D on eduke32
Exec="/run/dotcortex/retropie/isos/ports/duke3d/Duke Nukem 3D (eduke32).sh"
Icon=duke-nukem-3d
Terminal=false
#+END_SRC

#+BEGIN_SRC conf :tangle linux/.icewm/desktop/red-alert.desktop
[Desktop Entry]
Version=1.0
Type=Application
Name=Command & Conquer: Red Alert
Comment=Red Alert on OpenRA
Exec="/run/dotcortex/retropie/isos/ports/openra/Red Alert (OpenRA).sh"
Icon=red-alert
Terminal=false
#+END_SRC

#+BEGIN_SRC conf :tangle linux/.icewm/desktop/command-conquer.desktop
[Desktop Entry]
Version=1.0
Type=Application
Name=Command & Conquer
Comment=Command & Conquer on OpenRA
Exec="/run/dotcortex/retropie/isos/ports/openra/Command and Conquer (OpenRA).sh"
Icon=command-conquer
Terminal=false
#+END_SRC

#+BEGIN_SRC conf :tangle linux/.icewm/desktop/half-life.desktop
[Desktop Entry]
Version=1.0
Type=Application
Name=Half-Life
Comment=Half-Life on Xash3D
Exec="/run/dotcortex/retropie/isos/ports/xash3d/Half-Life (0.20).sh"
Icon=half-life
Terminal=false
#+END_SRC

#+BEGIN_SRC conf :tangle linux/.icewm/desktop/blue-shift.desktop
[Desktop Entry]
Version=1.0
Type=Application
Name=Half-Life: Blue Shift
Comment=Half-Life: Blue Shift on Xash3D
Exec="/run/dotcortex/retropie/isos/ports/xash3d/Half-Life - Blue Shift (0.20).sh"
Icon=blue-shift
Terminal=false
#+END_SRC

#+BEGIN_SRC conf :tangle linux/.icewm/desktop/opposing-force.desktop
[Desktop Entry]
Version=1.0
Type=Application
Name=Half-Life: Opposing Force
Comment=Half-Life: Opposing Force on Xash3D
Exec="/run/dotcortex/retropie/isos/ports/xash3d/Half-Life - Opposing Force (0.20).sh"
Icon=opposing-force
Terminal=false
#+END_SRC

#+BEGIN_SRC conf :tangle linux/.icewm/desktop/zsnes.desktop
[Desktop Entry]
Version=1.0
Type=Application
Name=ZSNES
Comment=Super Nintendo — the xyproto fork, the one that still builds
Exec=zsnes
Icon=zsnes
Terminal=false
#+END_SRC

#+BEGIN_SRC conf :tangle linux/.icewm/desktop/snes9x.desktop
[Desktop Entry]
Version=1.0
Type=Application
Name=Snes9x
Comment=Super Nintendo — the accuracy lane (Flatpak)
Exec=/home/metsatron/.local/bin/sanctuary-flatpak-run com.snes9x.Snes9x
Icon=snes9x
Terminal=false
#+END_SRC

#+BEGIN_SRC conf :tangle linux/.icewm/desktop/mupen64plus.desktop
[Desktop Entry]
Version=1.0
Type=Application
Name=Mupen64Plus
Comment=Nintendo 64
Exec=mupen64plus
Icon=mupen64plus
Terminal=false
#+END_SRC

* Wine prefix initialiser

Idempotent script run by the launch script before IceWM starts.  Creates
the Wine prefix in the isolated guest home, installs Wine package fonts into
the Windows =Fonts= directory, and imports the CMD console registry template.

Requires environment: =WINEPREFIX=, =DOTCORTEX_DIR=, =wine= in PATH.

#+BEGIN_SRC bash :tangle linux/.local/bin/sanctuary-redstone-9x-wineprefix-init :shebang "#!/usr/bin/env bash" :tangle-mode (identity #o755)
set -euo pipefail

MARKER="${WINEPREFIX}/.dotcortex-wineprefix-complete"
[[ -f "${MARKER}" ]] && exit 0

echo "redstone-9x: initialising Wine prefix at ${WINEPREFIX}…"

WINEDEBUG=-all wineboot -u

# 1. Copy Wine package fonts (from Guix profile)
WINE_FONTS_SRC="$(dirname "$(dirname "$(command -v wine)")")/share/wine/fonts"
WINE_FONTS_DST="${WINEPREFIX}/drive_c/windows/Fonts"
if [[ -d "${WINE_FONTS_SRC}" && -d "${WINE_FONTS_DST}" ]]; then
  cp -n "${WINE_FONTS_SRC}"/*.ttf "${WINE_FONTS_DST}/" 2>/dev/null || true
fi

# 2. Copy staged Microsoft fonts (provisioned by redstone-9x-font-provision)
FONT_STAGE="${WINEPREFIX%/.wine-redstone}/../fonts"
if [[ -d "${FONT_STAGE}" ]]; then
  cp -n "${FONT_STAGE}"/*.ttf "${WINE_FONTS_DST}/" 2>/dev/null || true
  cp -n "${FONT_STAGE}"/*.TTF "${WINE_FONTS_DST}/" 2>/dev/null || true
fi

# 3. Import CMD console appearance registry template
REG="${DOTCORTEX_DIR}/linux/.config/redstone-9x/wine-cmd-console.reg"
if [[ -f "${REG}" ]]; then
  WINEDEBUG=-all wine regedit "${REG}"
fi

# 4. bash.cmd bridge: typing 'bash' in Wine CMD opens a Bash-CMD frame.
#    Uses Wine's start /unix extension to spawn a native Linux process.
BASH_CMD="${WINEPREFIX}/drive_c/windows/system32/bash.cmd"
cat > "${BASH_CMD}" <<'BASHCMD'
@echo off
start /unix urxvt -name redstone-bash-cmd -title "Bash"
BASHCMD

# 5. Install Internet Explorer declaratively via winetricks. ie6 (2002) is the
#    oldest winetricks can fetch unattended and the most period-appropriate for a
#    Win95 desktop; IE 4/5/5.5 + Netscape Communicator (true 1996-2000 era) are a
#    planned follow-up, sourced from the evolt.org browser archive (browsers.evolt.org).
IE_WINETRICKS_VERB="ie6"
IE_EXE_64="${WINEPREFIX}/drive_c/Program Files/Internet Explorer/iexplore.exe"
IE_EXE_32="${WINEPREFIX}/drive_c/Program Files (x86)/Internet Explorer/iexplore.exe"
if [[ -f "${IE_EXE_64}" || -f "${IE_EXE_32}" ]]; then
  echo "redstone-9x: Internet Explorer already present — skipping ${IE_WINETRICKS_VERB}"
else
  winetricks -q "${IE_WINETRICKS_VERB}"
fi

fc-cache -s 2>/dev/null || true
touch "${MARKER}"
echo "redstone-9x: Wine prefix ready"
#+END_SRC

* CMD console registry template

Sets Lucida Console font and classic black/grey colour scheme for Wine's
CMD window.  Imported once by =sanctuary-redstone-9x-wineprefix-init=.

#+BEGIN_SRC conf :tangle linux/.config/redstone-9x/wine-cmd-console.reg :mkdirp yes
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Console]
"FaceName"="Lucida Console"
"FontSize"=dword:000e0000
"FontWeight"=dword:00000190
"ScreenColors"=dword:00000007
"WindowSize"=dword:001e0050
"ColorTable00"=dword:000c0c0c
"ColorTable07"=dword:00cccccc

[HKEY_CURRENT_USER\Console\%SystemRoot%_system32_cmd.exe]
"FaceName"="Lucida Console"
"FontSize"=dword:000e0000
"FontWeight"=dword:00000190
"ScreenColors"=dword:00000007
#+END_SRC

* URxvt terminal profiles (Xresources)

Named URxvt instance configurations loaded into the Xephyr display before IceWM
starts.  Each launcher uses =-name <instance>= to select the matching profile.

Palette: Windows 10 ConHost colour scheme (accurate for Win9x/2K era CMD and
PowerShell).  Fonts: Consolas for PowerShell, Lucida Console for CMD (falls back
to Courier New when not installed yet — see =redstone-9x-font-provision=).

#+BEGIN_SRC conf :tangle linux/.config/redstone-9x/Xresources :mkdirp yes
! Redstone 9X — URxvt terminal profiles
! Loaded into Xephyr display by sanctuary-redstone-9x-launch via xrdb -merge.
! Each launcher uses: urxvt -name <instance> ...

Xft.dpi: 96

! ── Common defaults ──────────────────────────────────────────────────────────
URxvt*scrollBar:       false
URxvt*geometry:        80x25
URxvt*letterSpace:     0
URxvt*lineSpace:       1
URxvt*borderLess:      false
URxvt*internalBorder:  2

! ── redstone-powershell — Windows PowerShell (deep blue / white) ─────────────
redstone-powershell*background:  #012456
redstone-powershell*foreground:  #EEEDF0
redstone-powershell*cursorColor: #EEEDF0
redstone-powershell*color0:      #0C0C0C
redstone-powershell*color1:      #C50F1F
redstone-powershell*color2:      #13A10E
redstone-powershell*color3:      #C19C00
redstone-powershell*color4:      #0037DA
redstone-powershell*color5:      #881798
redstone-powershell*color6:      #3A96DD
redstone-powershell*color7:      #CCCCCC
redstone-powershell*color8:      #767676
redstone-powershell*color9:      #E74856
redstone-powershell*color10:     #16C60C
redstone-powershell*color11:     #F9F1A5
redstone-powershell*color12:     #3B78FF
redstone-powershell*color13:     #B4009E
redstone-powershell*color14:     #61D6D6
redstone-powershell*color15:     #F2F2F2
redstone-powershell*font:        xft:Consolas:size=11:antialias=true

! ── redstone-bash-powershell — Bash in PowerShell frame ─────────────────────
redstone-bash-powershell*background:  #012456
redstone-bash-powershell*foreground:  #EEEDF0
redstone-bash-powershell*cursorColor: #EEEDF0
redstone-bash-powershell*color0:      #0C0C0C
redstone-bash-powershell*color1:      #C50F1F
redstone-bash-powershell*color2:      #13A10E
redstone-bash-powershell*color3:      #C19C00
redstone-bash-powershell*color4:      #0037DA
redstone-bash-powershell*color5:      #881798
redstone-bash-powershell*color6:      #3A96DD
redstone-bash-powershell*color7:      #CCCCCC
redstone-bash-powershell*color8:      #767676
redstone-bash-powershell*color9:      #E74856
redstone-bash-powershell*color10:     #16C60C
redstone-bash-powershell*color11:     #F9F1A5
redstone-bash-powershell*color12:     #3B78FF
redstone-bash-powershell*color13:     #B4009E
redstone-bash-powershell*color14:     #61D6D6
redstone-bash-powershell*color15:     #F2F2F2
redstone-bash-powershell*font:        xft:Cascadia Mono:size=11:antialias=true,xft:Consolas:size=11:antialias=true

! ── redstone-bash-cmd — Bash in CMD frame (classic black / pale grey) ────────
redstone-bash-cmd*background:  #0C0C0C
redstone-bash-cmd*foreground:  #CCCCCC
redstone-bash-cmd*cursorColor: #CCCCCC
redstone-bash-cmd*color0:      #0C0C0C
redstone-bash-cmd*color1:      #C50F1F
redstone-bash-cmd*color2:      #13A10E
redstone-bash-cmd*color3:      #C19C00
redstone-bash-cmd*color4:      #0037DA
redstone-bash-cmd*color5:      #881798
redstone-bash-cmd*color6:      #3A96DD
redstone-bash-cmd*color7:      #CCCCCC
redstone-bash-cmd*color8:      #767676
redstone-bash-cmd*color9:      #E74856
redstone-bash-cmd*color10:     #16C60C
redstone-bash-cmd*color11:     #F9F1A5
redstone-bash-cmd*color12:     #3B78FF
redstone-bash-cmd*color13:     #B4009E
redstone-bash-cmd*color14:     #61D6D6
redstone-bash-cmd*color15:     #F2F2F2
redstone-bash-cmd*font:        xft:Lucida Console:size=11:antialias=true,xft:Courier New:size=11:antialias=true
#+END_SRC

* qt6ct — Win95 Qt widget theming

Zeal — the Start-menu =Help= — is the sanctuary's one Qt app, and it is *Qt6* (Guix builds it against =qtbase-6.9.2=), not Qt5.  So the tool is =qt6ct=, not qt5ct: a Qt6 app will not load the Qt5 =libqt5ct.so= platform theme.  qt6ct drives Qt's own built-in =Windows= widget style — the classic =QWindowsStyle=, square grey beveled buttons and all, still shipped in Qt6 qtbase alongside Fusion — plus a silver/navy palette.  There is no Chicago95 Qt theme (upstream ships only GTK/icon/cursor/xfwm4 plus experimental KDE login+splash), and none is needed: =style=Windows= plus the palette *is* the Win95 look.

qt6ct is applied *per app*, never session-wide.  =QT_QPA_PLATFORMTHEME=qt6ct= is set only on the individual menu entries (Help→Zeal, Settings→Qt Appearance) — it is deliberately kept out of the =icewm-session= launch environment so it can never interact with session start.  The qt6ct package sits in =room-gaming= alongside Zeal; the package is env-inert in the profile.  Zeal's Guix wrapper hardcodes =QT_PLUGIN_PATH= to its own qtbase store dirs but *appends* any inherited value, and the room-gaming =etc/profile= does not export =QT_PLUGIN_PATH=, so the Help menu entry sets it explicitly to the profile's =lib/qt6/plugins= (where qt6ct's platformtheme plugin lives) — the launcher sed-injects that absolute in-container path into =@ROOM_QT6_PLUGINS@=.  qt6ct itself is a self-wrapped Guix binary, so the =Qt Appearance= entry launches it plainly.

The palette lives in a separate color-scheme file.  =color_scheme_path= must be an absolute path as seen *inside* the container, so the launcher sed-injects the projected guest path into =@GUEST_QT6CT_COLORS@= at projection time (same idiom the FVWM95 config uses for its plugins path).

#+BEGIN_SRC conf :tangle linux/.config/redstone-9x/qt6ct/qt6ct.conf :mkdirp yes
[Appearance]
color_scheme_path=@GUEST_QT6CT_COLORS@
custom_palette=true
icon_theme=Chicago95
standard_dialogs=default
style=Windows

[Interface]
menus_have_icons=false
dialog_buttons_have_icons=0
underline_shortcut=1
toolbutton_style=4

[Fonts]
general="Sans,8,-1,5,50,0,0,0,0,0"
fixed="Monospace,8,-1,5,50,0,0,0,0,0"
#+END_SRC

The Windows-95 QPalette.  22 =#AARRGGBB= values per group in =QPalette::ColorRole= order (WindowText, Button, Light, Midlight, Dark, Mid, Text, BrightText, ButtonText, Base, Window, Shadow, Highlight, HighlightedText, Link, LinkVisited, AlternateBase, NoRole, ToolTipBase, ToolTipText, PlaceholderText, Accent) — Qt6 added =Accent= as the last role, so 22 not 21.  Button/Window are =#c0c0c0= silver, Light is white and Dark/Shadow are grey/black for the bevels, Highlight and Accent are =#000080= navy with white text, tooltips are the pale-yellow =#ffffe1=.  Disabled greys out the text roles.

#+BEGIN_SRC conf :tangle linux/.config/redstone-9x/qt6ct/colors/win95.conf :mkdirp yes
[ColorScheme]
active_colors=#ff000000, #ffc0c0c0, #ffffffff, #ffe0e0e0, #ff808080, #ffa0a0a0, #ff000000, #ffffffff, #ff000000, #ffffffff, #ffc0c0c0, #ff000000, #ff000080, #ffffffff, #ff0000ff, #ff800080, #ffe8e8e8, #ff000000, #ffffffe1, #ff000000, #ff808080, #ff000080
disabled_colors=#ff808080, #ffc0c0c0, #ffffffff, #ffe0e0e0, #ff808080, #ffa0a0a0, #ff808080, #ffffffff, #ff808080, #ffc0c0c0, #ffc0c0c0, #ff000000, #ff808080, #ffffffff, #ff0000ff, #ff800080, #ffe8e8e8, #ff000000, #ffffffe1, #ff000000, #ff808080, #ff808080
inactive_colors=#ff000000, #ffc0c0c0, #ffffffff, #ffe0e0e0, #ff808080, #ffa0a0a0, #ff000000, #ffffffff, #ff000000, #ffffffff, #ffc0c0c0, #ff000000, #ff000080, #ffffffff, #ff0000ff, #ff800080, #ffe8e8e8, #ff000000, #ffffffe1, #ff000000, #ff808080, #ff000080
#+END_SRC

The SerenityOS palette is the same 22-role structure mapped through the scheme's colour substitutions (=#c0c0c0→#d4d0c8= chrome, =#000080→#84351a= selection, =#e0e0e0→#e8e4dc= light bevel), derived from =Base/res/themes/Default.ini= in the SerenityOS repo (BSD-2-Clause).

#+BEGIN_SRC conf :tangle linux/.config/redstone-9x/qt6ct/colors/serenity.conf :mkdirp yes
[ColorScheme]
active_colors=#ff000000, #ffd4d0c8, #ffffffff, #ffe8e4dc, #ff808080, #ffa0a0a0, #ff000000, #ffffffff, #ff000000, #ffffffff, #ffd4d0c8, #ff000000, #ff84351a, #ffffffff, #ff0000ff, #ff800080, #ffe8e8e8, #ff000000, #ffffffe1, #ff000000, #ff808080, #ff84351a
disabled_colors=#ff808080, #ffd4d0c8, #ffffffff, #ffe8e4dc, #ff808080, #ffa0a0a0, #ff808080, #ffffffff, #ff808080, #ffd4d0c8, #ffd4d0c8, #ff000000, #ff808080, #ffffffff, #ff0000ff, #ff800080, #ffe8e8e8, #ff000000, #ffffffe1, #ff000000, #ff808080, #ff808080
inactive_colors=#ff000000, #ffd4d0c8, #ffffffff, #ffe8e4dc, #ff808080, #ffa0a0a0, #ff000000, #ffffffff, #ff000000, #ffffffff, #ffd4d0c8, #ff000000, #ff84351a, #ffffffff, #ff0000ff, #ff800080, #ffe8e8e8, #ff000000, #ffffffe1, #ff000000, #ff808080, #ff84351a
#+END_SRC

* Font provision script

Stages Microsoft and period-appropriate fonts into the room's private font directory
at =~/.local/share/dotcortex/guests/sanctuary-redstone-9x/fonts/=.  This path is
outside DotCortex git (mutable guest state).  The launch script symlinks this dir
into the guest home's =.local/share/fonts/redstone-9x= for fontconfig.

Provenance table:

| Font          | Source                       | Licence          | Status           |
|---------------|------------------------------|------------------|------------------|
| Arial         | Winetricks =corefonts=       | Microsoft EULA   | Auto-install into Redstone prefix |
| Tahoma        | Winetricks =tahoma=          | Microsoft EULA   | Auto-install into Redstone prefix |
| Times New Roman | Winetricks =corefonts=     | Microsoft EULA   | Auto-install into Redstone prefix |
| Courier New   | Winetricks =corefonts=       | Microsoft EULA   | Auto-install into Redstone prefix |
| Cascadia Mono | github.com/microsoft/cascadia-code | MIT       | Auto-download    |
| Lucida Console | Winetricks =lucida=          | Microsoft EULA   | Auto-install into Redstone prefix |
| Consolas      | Winetricks =consolas=        | Microsoft EULA   | Auto-install into Redstone prefix |
| Verdana       | Winetricks =corefonts=       | Microsoft EULA   | Auto-install into Redstone prefix |
| Webdings      | Winetricks =webdings=        | Microsoft EULA   | Auto-install into Redstone prefix |
| MS Sans Serif | Windows system (bitmap)      | Proprietary      | Manual fallback only |

Run: =redstone-9x-font-provision= (once; idempotent).

#+BEGIN_SRC bash :tangle linux/.local/bin/redstone-9x-font-provision :shebang "#!/usr/bin/env bash" :tangle-mode (identity #o755)
set -euo pipefail

SANCTUARY="sanctuary-redstone-9x"
GUESTS_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/dotcortex/guests"
FONT_STAGE="${GUESTS_DIR}/${SANCTUARY}/fonts"
FONT_WINEPREFIX="${GUESTS_DIR}/${SANCTUARY}/font-provision-prefix"
mkdir -p "${FONT_STAGE}"

STAGED=0

# Source 1: Winetricks Microsoft font verbs.
# Use a managed font-provisioning prefix so active Redstone Wine sessions do not
# block font installation. Never use the default ~/.wine.
WINE_PROFILE="${HOME}/.guix-extra-profiles/room-windows-compat/room-windows-compat"
if [[ -x "${WINE_PROFILE}/bin/winetricks" ]]; then
  echo "redstone-9x-fonts: installing Microsoft fonts via Winetricks…"
  WINEPREFIX="${FONT_WINEPREFIX}" \
  WINEARCH=win32 \
  WINEDEBUG=-all \
  PATH="${WINE_PROFILE}/bin:${PATH}" \
    "${WINE_PROFILE}/bin/winetricks" -q corefonts tahoma webdings lucida consolas

  PREFIX_FONTS="${FONT_WINEPREFIX}/drive_c/windows/Fonts"
  if [[ -d "${PREFIX_FONTS}" ]]; then
    for font in \
      andale32.exe arial.ttf arialbd.ttf arialbi.ttf ariali.ttf ariblk.ttf \
      comic.ttf comicbd.ttf cour.ttf courbd.ttf courbi.ttf couri.ttf \
      georgia.ttf georgiab.ttf georgiai.ttf georgiaz.ttf impact.ttf \
      lucon.ttf consola.ttf consolab.ttf consolai.ttf consolaz.ttf \
      tahoma.ttf tahomabd.ttf times.ttf timesbd.ttf timesbi.ttf timesi.ttf \
      trebuc.ttf trebucbd.ttf trebucbi.ttf trebucit.ttf verdana.ttf \
      verdanab.ttf verdanai.ttf verdanaz.ttf webdings.ttf; do
      [[ -f "${PREFIX_FONTS}/${font}" ]] && cp -n "${PREFIX_FONTS}/${font}" "${FONT_STAGE}/"
    done
    find "${FONT_STAGE}" -maxdepth 1 -type f \( -iname "lucon.ttf" -o -iname "consola.ttf" -o -iname "cour.ttf" \) | grep -q . && STAGED=1
  fi
else
  echo "redstone-9x-fonts: winetricks not available — build room-windows-compat first"
fi

# Source 2: GE-Proton Wine fonts from X230 NFS (fallback/cache when mounted)
GEPROTON_FONTS="/home/metsatron/mnt/x230/.steam/compatibilitytools.d/GE-Proton7-45/files/share/wine/fonts"
if [[ -d "${GEPROTON_FONTS}" ]]; then
  echo "redstone-9x-fonts: copying from GE-Proton7 (X230 NFS)…"
  cp -n "${GEPROTON_FONTS}"/*.ttf "${FONT_STAGE}/" 2>/dev/null || true
  STAGED=1
else
  echo "redstone-9x-fonts: X230 NFS not mounted — skipping GE-Proton fonts"
fi

# Source 3: Guix wine64 profile fonts (fallback; available once room-windows-compat is built)
GUIX_WINE_FONTS="${WINE_PROFILE}/share/wine/fonts"
if [[ -d "${GUIX_WINE_FONTS}" ]]; then
  echo "redstone-9x-fonts: copying from Guix wine64 profile…"
  cp -n "${GUIX_WINE_FONTS}"/*.ttf "${FONT_STAGE}/" 2>/dev/null || true
  STAGED=1
fi

# Source 4: Cascadia Mono (MIT licence — auto-download)
CASCADIA_TTF="${FONT_STAGE}/CascadiaMono.ttf"
if [[ ! -f "${CASCADIA_TTF}" ]]; then
  echo "redstone-9x-fonts: downloading Cascadia Mono (MIT)…"
  CASCADIA_URL="https://github.com/microsoft/cascadia-code/releases/download/v2404.23/CascadiaCode-2404.23.zip"
  CASCADIA_TMP="$(mktemp -d)"
  trap "rm -rf '${CASCADIA_TMP}'" EXIT
  curl -L --fail -o "${CASCADIA_TMP}/cascadia.zip" "${CASCADIA_URL}"
  unzip -q "${CASCADIA_TMP}/cascadia.zip" "ttf/CascadiaMono.ttf" -d "${CASCADIA_TMP}" 2>/dev/null \
    || unzip -q "${CASCADIA_TMP}/cascadia.zip" "*CascadiaMono.ttf" -d "${CASCADIA_TMP}" 2>/dev/null
  find "${CASCADIA_TMP}" -name "CascadiaMono*.ttf" -exec cp -n {} "${FONT_STAGE}/" \;
  STAGED=1
fi

echo ""
echo "Font staging complete: ${FONT_STAGE}"
ls "${FONT_STAGE}/"
if [[ "${STAGED}" -eq 0 ]]; then
  echo "WARNING: no fonts were staged. Mount X230 NFS and/or build room-windows-compat profile first."
fi
echo ""
echo "Fonts requiring manual provisioning (proprietary):"
echo "  MS Sans Serif   — extract from Windows install if exact bitmap UI fallback is needed"
#+END_SRC

* PowerShell $PROFILE

DotCortex-managed PowerShell profile.  Projected into the guest home by the
launcher at =~/.config/powershell/Microsoft.PowerShell_profile.ps1=.

#+BEGIN_SRC powershell :tangle linux/.config/powershell/Microsoft.PowerShell_profile.ps1 :mkdirp yes
# Redstone 9X — Windows PowerShell profile
# Projected from DotCortex: sanctuary-distrobox.org

# Distinguish from native pwsh in prompt colour
function Prompt {
    $host.UI.RawUI.WindowTitle = "Windows PowerShell"
    "PS $($PWD.Path)> "
}

# Make bash easily reachable from pwsh
function bash { /usr/bin/env bash @args }
#+END_SRC

* Redstone PowerShell launcher

PowerShell interactive redraw is sensitive to the terminal line editor and
terminal identity.  Keep this isolated from Bash/CMD launchers.

#+BEGIN_SRC bash :tangle linux/.local/bin/redstone-9x-pwsh :shebang "#!/bin/bash" :tangle-mode (identity #o755)
set -euo pipefail

export TERM="${TERM:-xterm-256color}"
export POWERSHELL_UPDATECHECK=Off
export DOTNET_CLI_TELEMETRY_OPTOUT=1

# .NET 8 System.Console locates the terminfo database via $TERMINFO, ~/.terminfo,
# then fixed roots (/usr/share/terminfo, ...) -- it NEVER consults $TERMINFO_DIRS.
# Inside this rootless Distrobox container /usr/share/terminfo has no 'xterm'
# entry (only /run/host/usr/share/terminfo/x/xterm does), so .NET loads no
# terminfo, CursorAddress (cup) is null, Console.SetCursorPosition silently
# emits nothing while still caching the move, and PSReadLine's full-buffer
# redraw never repositions to the prompt origin -> the interactive "smear".
# CPR (ESC[6n) is unaffected because .NET hard-codes it.  Point .NET at the
# host terminfo tree so cup is emitted and the redraw is correct.  (Root cause
# confirmed 2026-07-06 via strace: openat of the host xterm entry + 26 CUP
# writes appear, smear gone.)
if [ -d /run/host/usr/share/terminfo ]; then
  export TERMINFO=/run/host/usr/share/terminfo
fi

# Let pwsh handle the TTY directly.  PSReadLine (PowerShell 7's readline
# engine) sets raw terminal mode itself and handles all echoing; running
# stty -echo before launch creates a double-echo conflict with PSReadLine.
pwsh -NoLogo -NoProfile
#+END_SRC

#+BEGIN_SRC powershell :tangle linux/.config/redstone-9x/powershell/basic-repl.ps1 :mkdirp yes
$host.UI.RawUI.WindowTitle = "Windows PowerShell"
Remove-Module PSReadLine -Force -ErrorAction SilentlyContinue

while ($true) {
    [Console]::Write("PS $($PWD.Path)> ")
    $line = [Console]::ReadLine()
    if ($null -eq $line) { break }
    if ($line.Trim() -eq "exit") { break }
    if ($line.Trim().Length -eq 0) { continue }

    try {
        Invoke-Expression $line
    }
    catch {
        Write-Error $_
    }
}
#+END_SRC

** Command Prompt and PowerShell Run-box shims

Small launchers so typing =cmd= or =powershell= / =pwsh= in the Run box (the
rofi Run box or the ice2k =runbox=) opens the same styled terminals as the
Terminals menu.  The sanctuary launcher symlinks =cmd=, =powershell= and =pwsh=
to these on the guest =PATH=.

#+BEGIN_SRC bash :tangle linux/.local/bin/redstone-9x-cmd :shebang "#!/bin/bash" :tangle-mode (identity #o755)
set -euo pipefail
# `cmd` in the Run box -> the Win-styled Command Prompt (wine cmd.exe in a
# Lucida-Console urxvt), matching the Terminals menu "Command Prompt" entry.
exec redstone-9x-run urxvt -hold -name redstone-bash-cmd -title "Command Prompt" \
  -geometry 80x25 +sb -bg rgb:0c/0c/0c -fg rgb:cc/cc/cc -cr rgb:cc/cc/cc \
  -fn "xft:Lucida Console:pixelsize=14:antialias=true" -e bash -lc 'exec wine cmd.exe'
#+END_SRC

#+BEGIN_SRC bash :tangle linux/.local/bin/redstone-9x-powershell :shebang "#!/bin/bash" :tangle-mode (identity #o755)
set -euo pipefail
# `powershell` / `pwsh` in the Run box -> Windows PowerShell in a Consolas xterm,
# matching the Terminals menu "Windows PowerShell" entry.
exec redstone-9x-run xterm -class redstone-powershell -title PowerShell \
  -geometry 80x25 -fa "Consolas" -fs 11 -bg "#012456" -fg "#EEEDF0" -cr "#EEEDF0" \
  -e redstone-9x-pwsh
#+END_SRC

** Bash and Zsh PowerShell-frame launchers (Run-box safe)

=bash= and =zsh= typed in the Run box open the PowerShell-frame urxvt, like the
Terminals menu and desktop shortcuts.  Unlike =cmd=/=powershell=, these names
ARE real shells that scripts constantly resolve via PATH — and =~/.local/bin=
is first on the session PATH, so the Run-box symlinks =bash=/=zsh= -> these
launchers shadow the real binaries for every bare-name lookup.  The launcher
therefore passes through to the real shell for anything that is not an
unambiguous GUI launch: any arguments (=bash script.sh=, =zsh -c …=), a tty on
stdin (a user typing =bash= inside a terminal keeps normal nesting), or piped
stdin (=echo cmd | bash=).  Only =--window= (menu/desktop entries) or a bare
no-arg call with stdin on =/dev/null= and =DISPLAY= set (the Run box) opens the
styled terminal.

#+BEGIN_SRC bash :tangle linux/.local/bin/redstone-9x-bash :shebang "#!/bin/bash" :tangle-mode (identity #o755)
set -u
# Resolve the REAL shell by walking PATH past our own directory (the symlink
# `bash` -> this script lives in ~/.local/bin, which is first on PATH).
self_dir="$(cd "$(dirname "$0")" && pwd)"
shell_name="bash"
real=""
IFS=: read -ra _dirs <<< "${PATH}"
for _d in "${_dirs[@]}"; do
  [ "${_d}" = "${self_dir}" ] && continue
  [ -x "${_d}/${shell_name}" ] && { real="${_d}/${shell_name}"; break; }
done
[ -n "${real}" ] || real="/bin/${shell_name}"

if [ "${1:-}" != "--window" ]; then
  # Passthrough unless this is an unambiguous GUI launch (Run box): no args,
  # stdin is /dev/null, DISPLAY present. Everything else gets the real shell.
  if [ $# -gt 0 ] || [ -t 0 ] || [ -z "${DISPLAY:-}" ] \
     || [ "$(readlink -f /proc/self/fd/0 2>/dev/null)" != "/dev/null" ]; then
    exec "${real}" "$@"
  fi
fi

exec redstone-9x-run urxvt -name redstone-bash-powershell -title "Bash" \
  -geometry 80x25 +sb -bg rgb:01/24/56 -fg rgb:ee/ed/f0 -cr rgb:ee/ed/f0 \
  -fn "xft:Cascadia Mono:size=11:antialias=true,xft:Consolas:size=11:antialias=true" \
  -e "${real}"
#+END_SRC

#+BEGIN_SRC bash :tangle linux/.local/bin/redstone-9x-zsh :shebang "#!/bin/bash" :tangle-mode (identity #o755)
set -u
# Same contract as redstone-9x-bash, for zsh — the default PowerShell-frame
# shell (Terminals menu lists Zsh first).
self_dir="$(cd "$(dirname "$0")" && pwd)"
shell_name="zsh"
real=""
IFS=: read -ra _dirs <<< "${PATH}"
for _d in "${_dirs[@]}"; do
  [ "${_d}" = "${self_dir}" ] && continue
  [ -x "${_d}/${shell_name}" ] && { real="${_d}/${shell_name}"; break; }
done
[ -n "${real}" ] || real="/bin/${shell_name}"

if [ "${1:-}" != "--window" ]; then
  if [ $# -gt 0 ] || [ -t 0 ] || [ -z "${DISPLAY:-}" ] \
     || [ "$(readlink -f /proc/self/fd/0 2>/dev/null)" != "/dev/null" ]; then
    exec "${real}" "$@"
  fi
fi

exec redstone-9x-run urxvt -name redstone-bash-powershell -title "Zsh" \
  -geometry 80x25 +sb -bg rgb:01/24/56 -fg rgb:ee/ed/f0 -cr rgb:ee/ed/f0 \
  -fn "xft:Cascadia Mono:size=11:antialias=true,xft:Consolas:size=11:antialias=true" \
  -e "${real}"
#+END_SRC

* Redstone runtime spine

Redstone's shared compatibility substrate lives under =~/.compat/=.  The
runtime root is intentionally Unix-centric and host-visible, while DOS-visible
layout is a generated projection layered over it.

Current spine:

- =~/.compat/library/= — future canonical content roots
- =~/.compat/generated/dos/c/REDSTONE/= — DOS-visible projection for DOSEMU2
- =~/.compat/state/= — lane-private mutable state
- =~/.compat/machines/dosbox-x/= — Windows 3.1 / Win9x machine folders

The current live RetroPie topology is recorded exactly, not inferred:

- EmulationStation =ports= logical path: =~/RetroPie/roms/ports=
- Physical backing directory: =~/RetroPie/isos/ports=
- The logical path is currently a symlink to the backing directory
- DOSBox Pure PC/DOS collection: =~/RetroPie/isos/pc= (separate import surface)

#+BEGIN_SRC bash :tangle linux/.local/bin/redstone-9x-compat-init :shebang "#!/bin/bash" :tangle-mode (identity #o755)
set -euo pipefail

QUIET=0
if [[ "${1:-}" == "--quiet" ]]; then
  QUIET=1
  shift
fi

COMPAT_ROOT="${REDSTONE_COMPAT_ROOT:-${HOME}/.compat}"

mkdir -p \
  "${COMPAT_ROOT}/library/media/floppy" \
  "${COMPAT_ROOT}/library/media/cdrom" \
  "${COMPAT_ROOT}/library/media/iso" \
  "${COMPAT_ROOT}/library/dos/apps" \
  "${COMPAT_ROOT}/library/dos/toolchains" \
  "${COMPAT_ROOT}/library/games" \
  "${COMPAT_ROOT}/library/ports/engines" \
  "${COMPAT_ROOT}/library/ports/families" \
  "${COMPAT_ROOT}/generated/dos/c/REDSTONE/USR/BIN" \
  "${COMPAT_ROOT}/generated/dos/c/REDSTONE/ETC" \
  "${COMPAT_ROOT}/generated/dos/c/REDSTONE/OPT" \
  "${COMPAT_ROOT}/generated/dos/c/REDSTONE/SHARE" \
  "${COMPAT_ROOT}/generated/dos/c/REDSTONE/HOME" \
  "${COMPAT_ROOT}/generated/dos/c/REDSTONE/TMP" \
  "${COMPAT_ROOT}/generated/dos/c/REDSTONE/VAR" \
  "${COMPAT_ROOT}/generated/dosemu2" \
  "${COMPAT_ROOT}/generated/dosbox-x" \
  "${COMPAT_ROOT}/generated/dosbox-staging" \
  "${COMPAT_ROOT}/generated/retroarch" \
  "${COMPAT_ROOT}/generated/desktop" \
  "${COMPAT_ROOT}/state/shared" \
  "${COMPAT_ROOT}/state/apps" \
  "${COMPAT_ROOT}/state/dosemu2" \
  "${COMPAT_ROOT}/state/dosbox-x" \
  "${COMPAT_ROOT}/state/dosbox-staging" \
  "${COMPAT_ROOT}/state/retroarch" \
  "${COMPAT_ROOT}/state/86box" \
  "${COMPAT_ROOT}/state/wine" \
  "${COMPAT_ROOT}/state/proton" \
  "${COMPAT_ROOT}/state/lutris" \
  "${COMPAT_ROOT}/machines/dosbox-x/win31-standard" \
  "${COMPAT_ROOT}/machines/dosbox-x/win31-upgraded" \
  "${COMPAT_ROOT}/machines/dosbox-x/win95" \
  "${COMPAT_ROOT}/machines/dosbox-x/win98se" \
  "${COMPAT_ROOT}/machines/86box"

if (( ! QUIET )); then
  echo "redstone-9x-compat-init: initialised ${COMPAT_ROOT}"
fi
#+END_SRC

* DOSEMU2 bridge scaffold

DOSEMU2 uses the Redstone runtime spine's generated DOS projection.  The mutable
guest DOS bridge remains under =~/.dosemu/=, but =C:\REDSTONE= is backed by the
host-visible =~/.compat/generated/dos/c/REDSTONE= tree.

#+BEGIN_SRC bash :tangle linux/.local/bin/redstone-9x-dosemu2-init :shebang "#!/bin/bash" :tangle-mode (identity #o755)
set -euo pipefail

COMPAT_BIN="${HOME}/.local/bin/redstone-9x-compat-init"
[[ -x "${COMPAT_BIN}" ]] && "${COMPAT_BIN}" --quiet

DOSEMU_HOME="${HOME}/.dosemu"
DRIVE_C="${DOSEMU_HOME}/drive_c"
GENERATED_ROOT="${REDSTONE_COMPAT_ROOT:-${HOME}/.compat}/generated/dos/c/REDSTONE"
REDSTONE_LINK="${DRIVE_C}/redstone"
BIN_DIR="${GENERATED_ROOT}/USR/BIN"
ETC_DIR="${GENERATED_ROOT}/ETC"
OPT_DIR="${GENERATED_ROOT}/OPT"
SHARE_DIR="${GENERATED_ROOT}/SHARE"
HOME_DIR="${GENERATED_ROOT}/HOME"
TMP_DIR="${GENERATED_ROOT}/TMP"
VAR_DIR="${GENERATED_ROOT}/VAR"
HOOK_BAT="${DRIVE_C}/userhook.bat"
HOOK_SYS="${DRIVE_C}/userhook.sys"

mkdir -p "${DRIVE_C}" "${BIN_DIR}" "${ETC_DIR}" "${OPT_DIR}" "${SHARE_DIR}" "${HOME_DIR}" "${TMP_DIR}" "${VAR_DIR}"
if [[ ! -e "${REDSTONE_LINK}" || -L "${REDSTONE_LINK}" ]]; then
  ln -sfnT "${GENERATED_ROOT}" "${REDSTONE_LINK}"
fi

cat > "${HOOK_BAT}" <<'EOF'
@ECHO OFF
SET REDSTONE_HOME=C:\REDSTONE
SET PATH=C:\REDSTONE\USR\BIN;%PATH%
SET TEMP=C:\REDSTONE\TMP
SET TMP=C:\REDSTONE\TMP
IF EXIST C:\REDSTONE\ETC\AUTOEXEC.BAT CALL C:\REDSTONE\ETC\AUTOEXEC.BAT
EOF

if [[ ! -f "${HOOK_SYS}" ]]; then
  cat > "${HOOK_SYS}" <<'EOF'
REM Redstone 9X DOSEMU2 hook placeholder.
REM Add CONFIG.SYS-style directives here only when a DOS program needs them.
EOF
fi

if [[ ! -f "${BIN_DIR}/README.BAT" ]]; then
  cat > "${BIN_DIR}/README.BAT" <<'EOF'
@ECHO OFF
ECHO Redstone 9X DOS launchers live in C:\REDSTONE\USR\BIN
ECHO Unix-side wrappers live at ~/.local/bin/redstone-9x-dos-*
EOF
fi
#+END_SRC

#+BEGIN_SRC bash :tangle linux/.local/bin/redstone-9x-dos :shebang "#!/bin/bash" :tangle-mode (identity #o755)
set -euo pipefail

DOTCORTEX_BIN="${HOME}/.local/bin"
BIN_DIR="${REDSTONE_COMPAT_ROOT:-${HOME}/.compat}/generated/dos/c/REDSTONE/USR/BIN"

"${DOTCORTEX_BIN}/redstone-9x-dosemu2-init"

if ! command -v dosemu >/dev/null 2>&1; then
  echo "redstone-9x-dos: dosemu not found in room-windows-compat" >&2
  echo "  Current state: wrapper scaffold is ready, package provisioning is still pending." >&2
  exit 127
fi

if (( $# == 0 )); then
  exec dosemu -K "${BIN_DIR}" -T
fi

launcher="$1"
match="$(
  find "${BIN_DIR}" -maxdepth 1 -type f \
    \( -iname "${launcher}" -o -iname "${launcher}.bat" \) \
    | sort \
    | head -n 1
)"

if [[ -z "${match}" ]]; then
  echo "redstone-9x-dos: launcher not found: ${launcher}" >&2
  echo "  Expected a .bat file under ${BIN_DIR}" >&2
  exit 1
fi

exec dosemu -K "${BIN_DIR}" -E "$(basename "${match}")"
#+END_SRC

#+BEGIN_SRC bash :tangle linux/.local/bin/redstone-9x-dosemu2-shell :shebang "#!/bin/bash" :tangle-mode (identity #o755)
set -euo pipefail

exec "${HOME}/.local/bin/redstone-9x-dos"
#+END_SRC

#+BEGIN_SRC bash :tangle linux/.local/bin/redstone-9x-dosbox-x :shebang "#!/bin/bash" :tangle-mode (identity #o755)
set -euo pipefail

if ! command -v dosbox-x >/dev/null 2>&1; then
  echo "redstone-9x-dosbox-x: dosbox-x not found in room-windows-compat" >&2
  exit 127
fi

exec dosbox-x "$@"
#+END_SRC

* PNMixer volume control

The tray speaker's click needs a mixer command — with none configured pnmixer errors ("No mixer application was found"). pavucontrol (room-gaming) under a private bus, same MATE/GApplication cross-wall rule as everything else.

#+BEGIN_SRC conf :tangle linux/.config/redstone-9x/pnmixer/config :mkdirp yes
[PNMixer]
AlsaCard=(default)
VolumeControlCommand=dbus-run-session pavucontrol
#+END_SRC

* Audacious profile

Redstone seeds only baseline Audacious Winamp-interface preferences.  The
launcher projects the skin corpus into Audacious' guest-local skin directory,
but the selected skin is user preference and must remain guest-local.

#+BEGIN_SRC conf :tangle linux/.config/redstone-9x/audacious/config :mkdirp yes
[audacious]
record=FALSE

[skins]
equalizer_visible=TRUE
mainwin_font=Tahoma 8
playlist_font=Tahoma 8
playlist_visible=TRUE
sticky=TRUE
#+END_SRC

* GTK theme

Redstone uses the Windows-95 GTK theme and a repo-backed Chicago95 icon theme.

#+BEGIN_SRC conf :tangle linux/.config/redstone-9x/gtk-3.0/settings.ini :mkdirp yes
[Settings]
gtk-theme-name=Windows-95
gtk-icon-theme-name=Chicago95
gtk-application-prefer-dark-theme=0
gtk-font-name=Sans 8
gtk-xft-dpi=98304
gtk-button-images=0
gtk-menu-images=0
gtk-toolbar-style=GTK_TOOLBAR_BOTH
gtk-toolbar-icon-size=GTK_ICON_SIZE_LARGE_TOOLBAR
gtk-cursor-theme-name=Win95
gtk-cursor-theme-size=24
#+END_SRC

#+BEGIN_SRC conf :tangle linux/.config/redstone-9x/gtk-2.0/gtkrc :mkdirp yes
gtk-theme-name="Windows-95"
gtk-icon-theme-name="Chicago95"
gtk-font-name="Sans 8"
gtk-xft-dpi=98304
gtk-cursor-theme-name="Win95"
gtk-cursor-theme-size=24
gtk-toolbar-style=GTK_TOOLBAR_BOTH
gtk-toolbar-icon-size=GTK_ICON_SIZE_LARGE_TOOLBAR
gtk-button-images=0
gtk-menu-images=0
#+END_SRC

The user CSS is a *template*: the selection colours are per-scheme, so the tangled file carries =@SEL_BG@= / =@SEL_RGBA@= tokens and =redstone-9x-scheme-apply= renders the live =~/.config/gtk-3.0/gtk.css= from it (the launcher projects the template, then boot-applies the active scheme).

#+BEGIN_SRC conf :tangle linux/.config/redstone-9x/gtk-3.0/gtk.css.in :mkdirp yes
/* Redstone 9X GTK user overrides — TEMPLATE, rendered by redstone-9x-scheme-apply.
 * Keep the theme visually static: no fade, no hide, no animated sidebar.
 */

,* {
  transition: none;
  animation: none;
}

.sidebar,
.sidebar *,
places-sidebar,
places-sidebar * {
  transition: none;
  animation: none;
  opacity: 1;
}

button,
button:hover,
button:active,
button:checked,
entry,
entry:hover,
entry:focus {
  transition: none;
}

/* PCManFM's custom desktop renderer consumes these states after room-gaming
 * names its CSS node fmdesktop, lowers its internal provider to application
 * priority, and exposes its Cairo rubber band through GTK's rubberband class.
 */
FmDesktop:selected,
fmdesktop:selected {
  background-color: @SEL_BG@;
  color: @SEL_FG@;
}

FmDesktop.rubberband,
fmdesktop.rubberband {
  background-color: @SEL_RGBA@;
  border-color: @SEL_BG@;
  border-style: solid;
  border-width: 1px;
}
#+END_SRC

#+BEGIN_SRC bash :tangle linux/.local/bin/redstone-9x-run :shebang "#!/bin/bash" :tangle-mode (identity #o755)
set -euo pipefail

GUIX_PROFILES="${HOME}/.guix-extra-profiles"

source_guix_profile() {
  local profile="$1"
  local status=0
  local had_nounset=0

  case $- in
    *u*) had_nounset=1; set +u ;;
  esac

  GUIX_PROFILE="$profile"
  export GUIX_PROFILE

  if . "$profile/etc/profile"; then
    status=0
  else
    status=$?
  fi

  (( had_nounset )) && set -u
  return "$status"
}

for _prof in desktop-common room-gaming room-windows-compat; do
  source_guix_profile "${GUIX_PROFILES}/${_prof}/${_prof}"
done

export DISPLAY="${DISPLAY:-:93}"
export XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"
export WINEPREFIX="${WINEPREFIX:-${HOME}/.wine-redstone}"
export WINEDEBUG="${WINEDEBUG:--all}"
export DOTCORTEX_DIR="${DOTCORTEX_DIR:-${HOME}/DotCortex}"

exec "$@"
#+END_SRC

#+BEGIN_SRC bash :tangle linux/.local/bin/redstone-9x-ie :shebang "#!/bin/bash" :tangle-mode (identity #o755)
set -euo pipefail

GUIX_PROFILES="${HOME}/.guix-extra-profiles"

source_guix_profile() {
  local profile="$1"
  local status=0
  local had_nounset=0

  case $- in
    *u*) had_nounset=1; set +u ;;
  esac

  GUIX_PROFILE="$profile"
  export GUIX_PROFILE

  if . "$profile/etc/profile"; then
    status=0
  else
    status=$?
  fi

  (( had_nounset )) && set -u
  return "$status"
}

for _prof in desktop-common room-gaming room-windows-compat; do
  source_guix_profile "${GUIX_PROFILES}/${_prof}/${_prof}"
done

export DISPLAY="${DISPLAY:-:93}"
export XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"
export WINEPREFIX="${WINEPREFIX:-${HOME}/.wine-redstone}"
export WINEDEBUG="${WINEDEBUG:--all}"
export DOTCORTEX_DIR="${DOTCORTEX_DIR:-${HOME}/DotCortex}"

exec wine iexplore.exe "$@"
#+END_SRC

** Wine tool dispatcher — redstone-9x-wine

One env-wrapped entry point for every Wine tool.  It sources the same three Guix
profiles and Wine environment as =redstone-9x-run=, then dispatches to a tool
chosen either by an explicit first argument (how the IceWM menu calls it, e.g.
=redstone-9x-wine winecfg=) or by its own invoked name (how the Run-box PATH
shims call it — =~/.local/bin/explorer= is a symlink to this script, so typing
=explorer= in the Run box lands here with =$0= = =explorer=).  Native profile
binaries (winetricks, wineboot, msiexec, regsvr32) are exec'd by ABSOLUTE path so
a same-named PATH shim can never recurse into itself; the =.exe= tools go through
=wine=, which is never shadowed.

#+BEGIN_SRC bash :tangle linux/.local/bin/redstone-9x-wine :shebang "#!/bin/bash" :tangle-mode (identity #o755)
set -euo pipefail

GUIX_PROFILES="${HOME}/.guix-extra-profiles"
WINCOMPAT="${GUIX_PROFILES}/room-windows-compat/room-windows-compat"

source_guix_profile() {
  local profile="$1"
  local status=0
  local had_nounset=0

  case $- in
    *u*) had_nounset=1; set +u ;;
  esac

  GUIX_PROFILE="$profile"
  export GUIX_PROFILE

  if . "$profile/etc/profile"; then
    status=0
  else
    status=$?
  fi

  (( had_nounset )) && set -u
  return "$status"
}

for _prof in desktop-common room-gaming room-windows-compat; do
  source_guix_profile "${GUIX_PROFILES}/${_prof}/${_prof}"
done

export DISPLAY="${DISPLAY:-:93}"
export XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"
export WINEPREFIX="${WINEPREFIX:-${HOME}/.wine-redstone}"
export WINEDEBUG="${WINEDEBUG:--all}"
export DOTCORTEX_DIR="${DOTCORTEX_DIR:-${HOME}/DotCortex}"

# Pick the tool: explicit first arg when invoked as redstone-9x-wine, otherwise
# the name we were called by (a PATH shim symlink).
self="$(basename "$0")"
if [ "${self}" = "redstone-9x-wine" ]; then
  tool="${1:-explorer}"
  shift || true
else
  tool="${self}"
fi

case "${tool}" in
  # Native profile binaries — absolute path so a same-named shim can't recurse.
  winetricks)
    if [ "$#" -eq 0 ] && command -v zenity >/dev/null 2>&1; then
      exec "${WINCOMPAT}/bin/winetricks" --gui
    fi
    exec "${WINCOMPAT}/bin/winetricks" "$@" ;;
  wineboot|msiexec|regsvr32|winedbg|winepath)
    exec "${WINCOMPAT}/bin/${tool}" "$@" ;;
  # Friendly aliases.
  ie|iexplore) exec wine iexplore.exe "$@" ;;
  uninstall|addremove) exec wine uninstaller.exe "$@" ;;
  cmd|command) exec wine cmd.exe "$@" ;;
  # Everything else is a Wine built-in .exe reached through the wine loader.
  *) exec wine "${tool}" "$@" ;;
esac
#+END_SRC

* Additional desktop entries — terminals and portals

#+BEGIN_SRC conf :tangle linux/.icewm/desktop/bash-ps.desktop
[Desktop Entry]
Version=1.0
Type=Application
Name=Bash
Comment=Bash shell in PowerShell colours
Exec=/home/metsatron/.local/bin/redstone-9x-bash --window
Icon=utilities-terminal
Terminal=false
#+END_SRC

#+BEGIN_SRC conf :tangle linux/.icewm/desktop/zsh-ps.desktop
[Desktop Entry]
Version=1.0
Type=Application
Name=Zsh
Comment=Zsh shell in PowerShell colours
Exec=/home/metsatron/.local/bin/redstone-9x-zsh --window
Icon=utilities-terminal
Terminal=false
#+END_SRC

#+BEGIN_SRC conf :tangle linux/.icewm/desktop/bash-cmd.desktop
[Desktop Entry]
Version=1.0
Type=Application
Name=Bash (CMD frame)
Comment=Bash shell in CMD colours
Exec=bash /home/metsatron/.local/bin/redstone-9x-run urxvt -name redstone-bash-cmd -title "Bash" -geometry 80x25 +sb -bg rgb:0c/0c/0c -fg rgb:cc/cc/cc -cr rgb:cc/cc/cc -fn "xft:Lucida Console:pixelsize=14:antialias=true" -e bash
Icon=utilities-terminal
Terminal=false
#+END_SRC

#+BEGIN_SRC conf :tangle linux/.icewm/desktop/my-briefcase.desktop
[Desktop Entry]
Version=1.0
Type=Application
Name=My Briefcase
Comment=Open personal briefcase folder
Exec=pcmanfm ~/Briefcase
Icon=my_briefcase
Terminal=false
#+END_SRC

* Browser portal stubs

URLs are configurable: the default scheme opens Firefox-ESR in kiosk-adjacent mode.
Replace =about:blank= with a living portal, archived page, or local period HTML once
chosen.  Both targets are intentionally left as =about:blank= placeholders in the
canonical DotCortex source.

#+BEGIN_SRC conf :tangle linux/.config/redstone-9x/portals.env :mkdirp yes
# Redstone 9X — browser portal URLs
# Override these by editing this file on the guest home (it is NOT symlinked from
# DotCortex; edit directly in the guest to keep URLs out of the public repo).
MSN_URL=about:blank
AOL_URL=about:blank
#+END_SRC

#+BEGIN_SRC conf :tangle linux/.icewm/desktop/msn-online.desktop
[Desktop Entry]
Version=1.0
Type=Application
Name=Set Up The Microsoft Network
Comment=The Microsoft Network
Exec=bash -lc 'source ~/.config/redstone-9x/portals.env 2>/dev/null; exec /home/metsatron/.local/bin/redstone-9x-run /home/metsatron/.local/bin/redstone-9x-ie "${MSN_URL:-about:blank}"'
Icon=msn
Terminal=false
#+END_SRC

#+BEGIN_SRC conf :tangle linux/.icewm/desktop/inbox.desktop
[Desktop Entry]
Version=1.0
Type=Application
Name=Inbox
Comment=Inbox
Exec=pcmanfm ~/Inbox
Icon=inbox
Terminal=false
#+END_SRC

#+BEGIN_SRC conf :tangle linux/.icewm/desktop/aol-online.desktop
[Desktop Entry]
Version=1.0
Type=Application
Name=The Internet
Comment=Internet Explorer
Exec=bash -lc 'source ~/.config/redstone-9x/portals.env 2>/dev/null; exec /home/metsatron/.local/bin/redstone-9x-run /home/metsatron/.local/bin/redstone-9x-ie "${AOL_URL:-about:blank}"'
Icon=internet-web-browser
Terminal=false
#+END_SRC

* Application inventory

Guix package availability queried against current channel (2026-06-25).

| Application           | Guix package          | Exec model        | Profile                | Mutable state           |
|-----------------------|-----------------------|-------------------|------------------------|-------------------------|
| PCManFM               | =pcmanfm=             | native            | room-gaming            | guest Desktop/home      |
| Mousepad              | =mousepad=            | native            | room-windows-compat*   | guest home              |
| Pluma                 | =pluma=               | native            | room-windows-compat*   | guest home              |
| Wine Notepad          | built into wine64     | Wine              | room-windows-compat    | WINEPREFIX              |
| tcalc                 | =tcalc=               | native (xterm -e) | room-gaming           | none                    |
| Audacious             | =audacious=           | native            | room-windows-compat*   | guest home              |
| Qmmp                  | =qmmp=                | native            | room-windows-compat*   | guest home              |
| VLC                   | =vlc=                 | native            | room-windows-compat*   | guest home              |
| Audacity              | =audacity=            | native            | room-windows-compat*   | guest home              |
| mGBA                  | =mgba=                | native            | room-windows-compat*   | guest home              |
| DOSEMU2               | bridge + wrapper scaffold | native        | room-windows-compat    | =~/.dosemu/= plus =~/.compat/= |
| DOSBox-X              | local package (compat lane) | native    | room-windows-compat    | guest home              |
| Firefox ESR           | =firefox-esr= (nongnu)| native            | room-windows-compat*   | guest home              |
| IceCat                | =icecat=              | native            | room-windows-compat*   | guest home              |
| Emacs                 | =emacs=               | native            | desktop-common         | guest home              |
| Obsidian              | =md.obsidian.Obsidian= | Flatpak bridge    | host user Flatpak      | guest home / HelmCortex vault |
| PowerShell            | local binary pkg      | native            | room-windows-compat    | guest home              |
| URxvt                 | =rxvt-unicode=        | native            | room-windows-compat    | none                    |
| Wine CMD              | built into wine64     | Wine              | room-windows-compat    | WINEPREFIX              |
| Wine Configurator     | built into wine64     | Wine              | room-windows-compat    | WINEPREFIX              |
| Notepad++             | n/a (Wine EXE)        | Wine              | room-windows-compat    | WINEPREFIX per-app      |
| Sublime Text          | n/a (Wine EXE)        | Wine              | room-windows-compat    | WINEPREFIX per-app      |
| Dreamweaver           | n/a (Wine EXE)        | Wine              | room-windows-compat    | WINEPREFIX per-app      |
| SeaMonkey             | not in Guix           | Wine EXE          | room-windows-compat    | WINEPREFIX per-app      |
| Minesweeper           | built into wine64     | Wine              | room-windows-compat    | WINEPREFIX              |

=*= = not yet added to profile; planned next slice.

Wine recreation / built-in programs (in wine64 by default):
- =wine notepad= — Notepad
- =wine minesweeper= — Minesweeper (winmine.exe, in some wine builds)
- =wine explorer= — Windows Explorer / C: Drive
- =wine control= — Control Panel
- =wine regedit= — Registry Editor
- =wine taskmgr= — Task Manager
- =wine winecfg= — Wine Configuration

Wine programs that need a real Microsoft EXE (not in wine64):
- Notepad++, Sublime Text, Dreamweaver, Cygwin — install from X230 installers into per-app WINEPREFIX

* Redstone 9X shell identity — DOS prompt + fastfetch greeting

The Redstone sanctuary projects a live Win9x/MS-DOS shell identity into both bash and zsh.

#+BEGIN_SRC json :tangle linux/.config/redstone-9x/fastfetch.jsonc :mkdirp yes
{
    "$schema": "https://github.com/fastfetch-cli/fastfetch/raw/dev/doc/json_schema.json",
    "logo": {
        "type": "builtin",
        "source": "Windows 95",
        "padding": { "top": 1, "right": 3 }
    },
    "display": { "separator": "" },
    "modules": [
        {"type": "custom", "format": "\u001b[37mC:\\> SYSINFO /ARCH"},
        {"type": "custom", "format": "\u001b[37m Volume in drive C is \u001b[97mREDSTONE-9X"},
        {"type": "custom", "format": "\u001b[90m -------------------------------------------------------"},
        {"type": "host", "key": "  Machine", "keyColor": "white", "keyWidth": 12},
        {"type": "kernel", "key": "  Kernel", "keyColor": "white", "keyWidth": 12},
        {"type": "cpu", "key": "  CPU", "keyColor": "white", "keyWidth": 12},
        {"type": "memory", "key": "  Memory", "keyColor": "white", "keyWidth": 12},
        {"type": "uptime", "key": "  Uptime", "keyColor": "white", "keyWidth": 12},
        {"type": "shell", "key": "  Shell", "keyColor": "white", "keyWidth": 12},
        {"type": "wm", "key": "  Shell UI", "keyColor": "white", "keyWidth": 12},
        {"type": "custom", "format": "\u001b[90m -------------------------------------------------------"},
        {"type": "command", "key": "  Host OS", "keyColor": "white", "keyWidth": 12, "text": ". /run/host/etc/os-release 2>/dev/null && printf '%s' \"$PRETTY_NAME\" || printf 'Unknown'"},
        {"type": "command", "key": "  DotCortex", "keyColor": "white", "keyWidth": 12, "text": "printf '%s' 'literate dotfiles \u2192 tangle \u2192 stow \u2192 $HOME'"},
        {"type": "command", "key": "  Habitat", "keyColor": "white", "keyWidth": 12, "text": "[ -f /run/.containerenv ] && printf 'Sanctuary (Distrobox)' || printf 'Baremetal'"},
        {"type": "command", "key": "  Substrate", "keyColor": "white", "keyWidth": 12, "text": "[ -d /gnu/store ] && printf 'Guix' || printf 'Unknown'"},
        {"type": "command", "key": "  Layer", "keyColor": "white", "keyWidth": 12, "text": "printf 'Xephyr %s' \"${DISPLAY:-?}\""},
        {"type": "custom", "format": "\u001b[90m -------------------------------------------------------"},
        {"type": "custom", "format": "\u001b[37m SOUND BLASTER 16  \u001b[92mREADY  \u001b[37mVESA SVGA  \u001b[92mREADY"},
        {"type": "custom", "format": "\u001b[37m WINE BOARD        \u001b[92mREADY  \u001b[37mDIRECTX    \u001b[92mREADY"},
        {"type": "custom", "format": "\u001b[37m MSCDEX CD-ROM     \u001b[92mREADY  \u001b[37mNETWORK    \u001b[92mREADY"},
        {"type": "custom", "format": "\u001b[37mC:\\> WIN"},
        {"type": "custom", "format": "\u001b[97mStarting Redstone 9X..."}
    ]
}
#+END_SRC

#+BEGIN_SRC bash :tangle linux/.config/redstone-9x/shell/bashrc :comments no :mkdirp yes
# Redstone 9X sanctuary bash rc — Win9x/MS-DOS shell identity.
# Shared sanctuary grammar: symlinked to ~/.bashrc by sanctuary-redstone-9x-launch.
# Interactive shells only.
case $- in *i*) ;; *) return ;; esac

# Map the Unix path to a DOS drive path: $HOME collapses to Z:\ , anything above
# $HOME shows as a C:\ path, forward slashes become backslashes. The final result
# is doubled ('\' -> '\\') because it lands in PS1, which bash re-expands as prompt
# escapes — an un-doubled '\h' '\s' '\d' '\w' '\u' would render as the
# hostname/shell/date/cwd/user. (Verified via ${PS1@P} rendering, 2026-07-15.)
_redstone_dospath() {
  local p="${PWD}" rel dos
  if [ "${p}" = "${HOME}" ]; then
    dos='Z:\'
  elif [ "${p#${HOME}/}" != "${p}" ]; then
    rel="${p#${HOME}/}"; dos="Z:\\${rel//\//\\}"
  else
    rel="${p#/}"; dos="C:\\${rel//\//\\}"
  fi
  printf '%s' "${dos//\\/\\\\}"
}
PROMPT_COMMAND='PS1="BASH $(_redstone_dospath)> "'

# First interactive shell in each terminal: open at HOME, print the boot banner.
# REDSTONE_SHELL_INIT is exported so nested subshells inherit it and stay quiet.
if [ -z "${REDSTONE_SHELL_INIT:-}" ]; then
  export REDSTONE_SHELL_INIT=1
  cd "${HOME}" 2>/dev/null || true
  printf '\033[97mMineshaft Redstone 9X.0.26715\033[0m\n\n'
fi
#+END_SRC

#+BEGIN_SRC bash :tangle linux/.config/redstone-9x/shell/bash_profile :comments no :mkdirp yes
# Redstone 9X sanctuary bash login profile — ensure .bashrc runs for login shells
# (distrobox enter / terminal emulators that start bash as a login shell).
[ -f "${HOME}/.bashrc" ] && . "${HOME}/.bashrc"
#+END_SRC

#+BEGIN_SRC bash :tangle linux/.config/redstone-9x/shell/zshrc :comments no :mkdirp yes
# Redstone 9X sanctuary zsh rc — Win9x/MS-DOS shell identity.
# Shared sanctuary grammar: symlinked to ~/.zshrc by sanctuary-redstone-9x-launch,
# replacing the global symlink. Sources the global DotCortex zshrc FIRST so all
# global aliases/functions survive, THEN applies the sanctuary prompt — the global
# ~/DotCortex/all/.zshrc is never edited.
[ -f "${HOME}/DotCortex/all/.zshrc" ] && source "${HOME}/DotCortex/all/.zshrc"

# Clean PowerShell-style prompt showing only the current directory name
# (`ZSH metsatron> `, `~` at home) — no DOS-path grammar, no boot banner. Both
# stay bash-only by request (2026-07-18); the global zshrc's prompt and any
# RPROMPT are overridden after sourcing so nothing decorates the line.
PROMPT='ZSH %1/> '
unset RPROMPT

# First interactive shell in each terminal: open at HOME (silently).
if [[ -z "${REDSTONE_SHELL_INIT:-}" ]]; then
  export REDSTONE_SHELL_INIT=1
  cd "${HOME}" 2>/dev/null || true
fi
#+END_SRC
