ThemeDescription="BeOS Personal (terracotta tab, close-left)"
ThemeAuthor="Tverdov Andrey"
Look=metal

RolloverButtonsSupported=0

TitleButtonsLeft="x"
TitleButtonsRight="mi"
TitleButtonsSupported="sxim"
TitleBarHeight=25

TitleBarJustify=50

TaskBarAtTop=1

BorderSizeX=5
BorderSizeY=5
CornerSizeX=30
CornerSizeY=30
DlgBorderSizeX=5
DlgBorderSizeY=5

MenuMouseTracking=1
ShowMenuButtonIcon=1

TaskBarClockLeds=0
ColorClock=""
ColorClockText="black"
TrayDrawBevel=1

ColorCPUStatusUser="#6C6C6C"
ColorCPUStatusSystem="#A4A4F5"
ColorCPUStatusNice="#6C6C6C"
ColorCPUStatusIdle="#363651"
ColorNet="#6C6C6C"
ColorNetSend="#6C6C6C"
ColorNetReceive="#A4A4F5"
ColorNetIdle="#363651"
DesktopBackgroundColor="#B0B0B0"
ColorNormalMenu="#D8D8D8"
ColorActiveMenuItem="#B0B0B0"
ColorNormalMenuItemText="#000000"
ColorActiveMenuItemText="#000000"
ColorDisabledMenuItemText="#6C6C6C"
ColorDefaultTaskBar="#D8D8D8"
ColorNormalTaskBarApp="#D8D8D8"
ColorNormalTaskBarAppText="#000000"
ColorActiveTaskBarApp="#B0B0B0"
ColorActiveTaskBarAppText="#000000"
ColorMinimizedTaskBarApp="#D8D8D8"
ColorMinimizedTaskBarAppText="#000000"
ColorNormalBorder="#E8E8E8"
ColorActiveBorder="#E8E8E8"
ColorActiveTitleBar="#be816c"
ColorNormalTitleBar="#eaeaea"
ColorNormalButton="#D8D8D8"
ColorActiveButton="#B0B0B0"
ColorNormalTitleBarText="#000000"
ColorActiveTitleBarText="#000000"
ColorMoveSizeStatus="#D8D8D8"
ColorMoveSizeStatusText="#B0B0B0"
ColorListBox="#6C6C6C"
ColorListBoxText="#B0B0B0"
ColorListBoxSelection="#000000"
ColorListBoxSelectionText="#B0B0B0"
ColorScrollBar="#6C6C6C"
ColorScrollBarSlider="#000000"
ColorScrollBarButton="#6C6C6C"
ColorScrollBarButtonArrow="#B0B0B0"
ColorToolTip="#D8D8D8"
ColorToolTipText="#000000"

# Font Specification
TitleFontNameXft = Swis721 BT:size=10:bold
MenuFontNameXft = Swis721 BT:size=10
MinimizedWindowFontNameXft = Swis721 BT:size=10
ActiveButtonFontNameXft = Swis721 BT:size=10
NormalButtonFontNameXft = Swis721 BT:size=10
ToolButtonFontNameXft = Swis721 BT:size=10
NormalWorkspaceFontNameXft = Swis721 BT:size=10
ActiveWorkspaceFontNameXft = Swis721 BT:size=10
QuickSwitchFontNameXft =Swis721 BT:size=10
ListBoxFontNameXft = Swis721 BT:size=10
StatusFontNameXft = Swis721 BT:size=10
ToolTipFontNameXft = Swis721 BT:size=10
ActiveTaskBarFontNameXft = Swis721 BT:size=10
NormalTaskBarFontNameXft = Swis721 BT:size=10
ClockFontNameXft = Swis721 BT:size=10
InputFontNameXft = Swis721 BT:size=10

TaskBarClockLeds=0
