#
# Tosh 0.2
#

ThemeDescription="NeXTSTEP - QTStep - WMaker OpenStep"
ThemeAuthor="Row [david@comunidadnet.org]"

Look=pixmap

TitleBarCentered=1
ShowMenuButtonIcon=1
TaskBarShowStartMenu=0

TitleButtonsSupported="xmris"
TitleButtonsRight="im"
TitleButtonsLeft="x"


TitleBarHeight="19"
BorderSizeX="3"
BorderSizeY="3"
CornerSizeX="3"
CornerSizeY="3"
DlgBorderSizeX="3"
DlgBorderSizeY="3"
ButtonX="16"
ButtonY="19"

ColorDialog="rgb:ae/aa/ae"
ColorActiveBorder="rgb:00/00/00"
ColorNormalBorder="rgb:ae/aa/ae"

ColorNormalTitleButton="rgb:f0/f0/f0"
ColorNormalTitleButtonText="rgb:00/00/00"
ColorNormalButton="rgb:f0/f0/f0"
ColorNormalButtonText="rgb:00/00/00"
ColorActiveButton="rgb:73/ad/ef"
ColorActiveButtonText="rgb:00/00/00"
ColorActiveTitleBar="rgb:00/00/00"
ColorNormalTitleBar="rgb:44/44/44"
ColorActiveTitleBarText="rgb:ff/ff/ff"
ColorNormalTitleBarText="rgb:ff/ff/ff"
ColorNormalMinimizedWindow="rgb:f0/f0/f0"
ColorNormalMinimizedWindowText="rgb:00/00/00"
ColorActiveMinimizedWindow="rgb:73/ad/ef"
ColorActiveMinimizedWindowText="rgb:00/00/00"

ColorNormalMenu="rgb:ae/aa/ae"
ColorActiveMenuItem="rgb:1b/1b/4b"
ColorActiveMenuItemText="rgb:ff/ff/ff"
ColorNormalMenuItemText="rgb:00/00/00"
ColorDisabledMenuItemText="rgb:80/80/80"

ColorMoveSizeStatus="rgb:f0/f0/f0"
ColorMoveSizeStatusText="rgb:00/00/00"

ColorQuickSwitch="rgb:f0/f0/f0"
ColorQuickSwitchText="rgb:00/00/00"

ColorDefaultTaskBar="rgb:ae/aa/ae"
ColorNormalTaskBarApp="rgb:ae/aa/ae"
ColorNormalTaskBarAppText="rgb:00/00/00"
ColorActiveTaskBarApp="rgb:1b/1b/4b"
ColorActiveTaskBarAppText="rgb:ff/ff/ff"
ColorMinimizedTaskBarApp="rgb:f0/f0/f0"
ColorMinimizedTaskBarAppText="rgb:00/00/00"

ColorInvisibleTaskBarApp="rgb:80/80/80"
ColorInvisibleTaskBarAppText="rgb:00/00/00"

ColorScrollBar="rgb:ae/aa/ae"
ColorScrollBarArrow="rgb:c6/c4/c6"
ColorScrollBarSlider="rgb:c6/c4/c6"

ColorListBox="rgb:ae/aa/ae"
ColorListBoxText="rgb:00/00/00"
ColorListBoxSelection="rgb:1b/1b/4b"
ColorListBoxSelectionText="rgb:ff/ff/ff"

ColorToolTip="rgb:f0/f0/f0"
ColorToolTipText="rgb:00/00/00"

ColorClock="rgb:f0/f0/f0"
ColorClockText="rgb:00/00/00"

ColorApm="rgb:f0/f0/f0"
ColorApmText="rgb:00/00/00"

ColorLabel="rgb:f0/f0/f0"
ColorLabelText="rgb:00/00/00"

ColorInput="rgb:ae/aa/ae"
ColorInputText="rgb:00/00/00"
ColorInputSelection="rgb:1b/1b/4b"
ColorInputSelectionText="rgb:ff/ff/ff"