#+TITLE: Project Name
#+AUTHOR: Your Name
#+DATE: <2025-07-08>
#+OPTIONS: toc:nil

* Debian & Ubuntu README.md metsatron dotfiles

** About
Metsatron's dotfiles for Debian & Ubuntu platforms.

** Table of Contents :TOC:
- [[#debian--ubuntu-readmemd-metsatron-dotfiles][Debian & Ubuntu README.md metsatron dotfiles]]
  - [[#about][About]]
  - [[#configure-keyboard][Configure Keyboard]]
  - [[#installing-git-and-stow][Installing git and stow]]
    - [[#debian][Debian]]
  - [[#clone-dotfiles][Clone dotfiles]]
  - [[#stowing-dotfiles][Stowing dotfiles]]
    - [[#debian-1][Debian]]
  - [[#installing-tools][Installing tools]]
    - [[#debian-2][Debian]]
    - [[#ubuntu][Ubuntu]]
  - [[#updating-fonts][Updating fonts]]
    - [[#load-xresources][Load .Xresources]]
  - [[#install-powerline][Install Powerline]]
    - [[#ubuntu-1][Ubuntu]]
    - [[#debian-3][Debian]]
    - [[#install-zplug-zsh-plugins][Install ZPlug ZSH Plugins]]
    - [[#copy-xfce4-terminal-colorschemes][Copy XFCE4 Terminal Colorschemes]]
  - [[#plugins-for-vlc-2x-to-support-hevc-decoding-using-libde265][Plugins for VLC 2.x to support HEVC decoding using libde265]]
- [[#contributing][Contributing]]
- [[#license][License]]

** Configure Keyboard
#+BEGIN_EXAMPLE sh
# Proxmox
# sudo apt install console-data
sudo dpkg-reconfigure keyboard-configuration
setxkbmap us -variant colemak
#+END_EXAMPLE

** Installing git and stow
*** Debian
=sudo apt update && sudo apt install git stow=

** Clone dotfiles
#+BEGIN_EXAMPLE sh
    git clone --recursive https://gitlab.com/metsarono/dotfiles.git ~/.dotfiles
    cd ~/.dotfiles && git submodule update --recursive --remote
#+END_EXAMPLE

** Stowing dotfiles
*** Debian  
=stow all linux debian=

** Installing tools
*** Debian
#+BEGIN_SRC sh
# Install Nala

echo "deb [arch=amd64,arm64,armhf] http://deb.volian.org/volian/ scar main" | sudo tee /etc/apt/sources.list.d/volian-archive-scar-unstable.list
wget -qO - https://deb.volian.org/volian/scar.key | sudo tee /etc/apt/trusted.gpg.d/volian-archive-scar-unstable.gpg > /dev/null
sudo apt update && sudo apt install nala
sudo nala install neovim zsh tmux ranger rxvt-unicode
chsh -s $(which zsh)
#+END_SRC

#+RESULTS:

*** Ubuntu
#+BEGIN_SRC sh
# Install Nala

echo "deb [arch=amd64,arm64,armhf] http://deb.volian.org/volian/ scar main" | sudo tee /etc/apt/sources.list.d/volian-archive-scar-unstable.list
wget -qO - https://deb.volian.org/volian/scar.key | sudo tee /etc/apt/trusted.gpg.d/volian-archive-scar-unstable.gpg > /dev/null
sudo apt update && sudo apt install nala

sudo nala install software-properties-common 
sudo add-apt-repository ppa:neovim-ppa/stable 
sudo nala update && sudo nala install neovim zsh tmux ranger rxvt-unicode 
sudo nala install python-is-python3 python3 python3-pip python3-setuptools

sudo update-alternatives --install /usr/bin/vi vi /usr/bin/nvim 60 
sudo update-alternatives --install /usr/bin/vim vim /usr/bin/nvim 60 
sudo update-alternatives --install /usr/bin/editor editor /usr/bin/nvim 60
#+END_SRC

** Updating fonts
=fc-cache -f $fond_dir=

*** Load .Xresources
=xrdb ~/.Xresources=

** Install Powerline
*** Ubuntu
#+BEGIN_EXAMPLE sh
sudo apt update
sudo apt install python3-pip
sudo pip install powerline-status
#+END_EXAMPLE

*** Debian
#+BEGIN_EXAMPLE sh
wget https://bootstrap.pypa.io/get-pip.py
python get-pip.py
sudo pip install powerline-status
#+END_EXAMPLE

*** Install ZPlug ZSH Plugins
#+BEGIN_EXAMPLE sh
export ZPLUG_HOME=~/.dotfiles/all/.zplug
git clone https://github.com/zplug/zplug $ZPLUG_HOME
zsh
zplug install
chsh -s /bin/zsh
sudo reboot now
#+END_EXAMPLE

*** Copy XFCE4 Terminal Colorschemes
=sudo \cp ~/.colors/base16-xfce4-terminal/colorschemes/*.theme /usr/share/xfce4/terminal/colorschemes=

** Plugins for VLC 2.x to support HEVC decoding using libde265
=git clone https://github.com/strukturag/vlc-libde265.git ./autogen.sh ./configure  make sudo make install sudo \ln -s /usr/local/lib/libde265_plugin.so /usr/lib/vlc/plugins/codec/libde265_plugin.so sudo \ln -s /usr/local/lib/libde265demux_plugin.so /usr/lib/vlc/plugins/demux/libde265demux_plugin.so=

* Contributing
Pull requests welcome! See CONTRIBUTING.org for guidelines.

* License
MIT License.

