#
# Tosh 0.2
#

ThemeDescription="Rhapsody - OneStepBack - DarkAdobe BlueHighlights"
ThemeAuthor="Row [david@comunidadnet.org]"

Look=pixmap

TitleBarCentered=1
ShowMenuButtonIcon=1
TaskBarShowStartMenu=0

TitleButtonsSupported="xmris"
TitleButtonsRight="im"
TitleButtonsLeft="x"


TitleBarHeight="19"
BorderSizeX="6"
BorderSizeY="6"
CornerSizeX="23"
CornerSizeY="23"
DlgBorderSizeX="6"
DlgBorderSizeY="6"
ButtonX="16"
ButtonY="19"

ColorDialog="rgb:45/45/45"
ColorActiveBorder="rgb:30/30/30"
ColorNormalBorder="rgb:5b/5b/5b"

ColorNormalTitleButton="rgb:f0/f0/f0"
ColorNormalTitleButtonText="rgb:00/00/00"
ColorNormalButton="rgb:f0/f0/f0"
ColorNormalButtonText="rgb:00/00/00"
ColorActiveButton="rgb:73/ad/ef"
ColorActiveButtonText="rgb:00/00/00"
ColorActiveTitleBar="rgb:9e/9e/9e"
ColorNormalTitleBar="rgb:d8/d8/d8"
ColorActiveTitleBarText="rgb:00/00/00"
ColorNormalTitleBarText="rgb:00/00/00"
ColorNormalMinimizedWindow="rgb:f0/f0/f0"
ColorNormalMinimizedWindowText="rgb:00/00/00"
ColorActiveMinimizedWindow="rgb:73/ad/ef"
ColorActiveMinimizedWindowText="rgb:00/00/00"

ColorNormalMenu="rgb:45/45/45"
ColorActiveMenuItem="rgb:4b/69/83"
ColorActiveMenuItemText="rgb:ff/ff/ff"
ColorNormalMenuItemText="rgb:ff/ff/ff"
ColorDisabledMenuItemText="rgb:80/80/80"

ColorMoveSizeStatus="rgb:f0/f0/f0"
ColorMoveSizeStatusText="rgb:00/00/00"

ColorQuickSwitch="rgb:f0/f0/f0"
ColorQuickSwitchText="rgb:00/00/00"

ColorDefaultTaskBar="rgb:45/45/45"
ColorNormalTaskBarApp="rgb:45/45/45"
ColorNormalTaskBarAppText="rgb:00/00/00"
ColorActiveTaskBarApp="rgb:4b/69/83"
ColorActiveTaskBarAppText="rgb:ff/ff/ff"
ColorMinimizedTaskBarApp="rgb:f0/f0/f0"
ColorMinimizedTaskBarAppText="rgb:00/00/00"

ColorInvisibleTaskBarApp="rgb:80/80/80"
ColorInvisibleTaskBarAppText="rgb:00/00/00"

ColorScrollBar="rgb:45/45/45"
ColorScrollBarArrow="rgb:5b/5b/5b"
ColorScrollBarSlider="rgb:5b/5b/5b"

ColorListBox="rgb:45/45/45"
ColorListBoxText="rgb:ff/ff/ff"
ColorListBoxSelection="rgb:4b/69/83"
ColorListBoxSelectionText="rgb:ff/ff/ff"

ColorToolTip="rgb:f0/f0/f0"
ColorToolTipText="rgb:00/00/00"

ColorClock="rgb:f0/f0/f0"
ColorClockText="rgb:00/00/00"

ColorApm="rgb:f0/f0/f0"
ColorApmText="rgb:00/00/00"

ColorLabel="rgb:f0/f0/f0"
ColorLabelText="rgb:00/00/00"

ColorInput="rgb:45/45/45"
ColorInputText="rgb:ff/ff/ff"
ColorInputSelection="rgb:4b/69/83"
ColorInputSelectionText="rgb:ff/ff/ff"