#!/data/data/com.termux/files/usr/bin/sh
# ~/DotCortex/termux/.termux/tasker/termux-revive
# Tasker heartbeat target: idempotent supervision revive, silent.
exec /data/data/com.termux/files/home/.termux/boot/00-services
