[Icon Theme]
Name=NeXTSTEP
Comment=NextSpace and GNUstep icons over the Redstone CDE/Irixium fallback
Inherits=Irixium
Directories=16x16/apps,16x16/devices,16x16/mimetypes,16x16/places,22x22/apps,22x22/devices,22x22/mimetypes,22x22/places,24x24/apps,24x24/devices,24x24/mimetypes,24x24/places,32x32/apps,32x32/devices,32x32/mimetypes,32x32/places,48x48/apps,48x48/categories,48x48/devices,48x48/mimetypes,48x48/places,48x48/status

[16x16/apps]
Size=16
Context=Applications
Type=Fixed

[16x16/devices]
Size=16
Context=Devices
Type=Fixed

[16x16/mimetypes]
Size=16
Context=MimeTypes
Type=Fixed

[16x16/places]
Size=16
Context=Places
Type=Fixed

[22x22/apps]
Size=22
Context=Applications
Type=Fixed

[22x22/devices]
Size=22
Context=Devices
Type=Fixed

[22x22/mimetypes]
Size=22
Context=MimeTypes
Type=Fixed

[22x22/places]
Size=22
Context=Places
Type=Fixed

[24x24/apps]
Size=24
Context=Applications
Type=Fixed

[24x24/devices]
Size=24
Context=Devices
Type=Fixed

[24x24/mimetypes]
Size=24
Context=MimeTypes
Type=Fixed

[24x24/places]
Size=24
Context=Places
Type=Fixed

[32x32/apps]
Size=32
Context=Applications
Type=Fixed

[32x32/devices]
Size=32
Context=Devices
Type=Fixed

[32x32/mimetypes]
Size=32
Context=MimeTypes
Type=Fixed

[32x32/places]
Size=32
Context=Places
Type=Fixed

[48x48/apps]
Size=48
Context=Applications
Type=Fixed

[48x48/categories]
Size=48
Context=Categories
Type=Fixed

[48x48/devices]
Size=48
Context=Devices
Type=Fixed

[48x48/mimetypes]
Size=48
Context=MimeTypes
Type=Fixed

[48x48/places]
Size=48
Context=Places
Type=Fixed

[48x48/status]
Size=48
Context=Status
Type=Fixed
