[Icon Theme]
Name=Indigo Reality
Comment=An SGI IRIX icon theme version 2.0. Some images from Vecteezy.com, freepik.com; N64 controller image from pngitem.com (Salsationgoriska); link image (copyright Orchid) comes from svgrepo.com (MIT license);KDE Classic icons from Torsen Rahn
Example=computer
Inherits=kdeclassic,BluecurveRH,commonality
FollowsColorScheme=true

# KDE Specific Stuff
DisplayDepth=32
LinkOverlay=link_overlay
LockOverlay=lock_overlay
ZipOverlay=zip_overlay
DesktopDefault=48
DesktopSizes=16,22,32,48,64,128,256
ToolbarDefault=32
ToolbarSizes=16,22,32,48
MainToolbarDefault=32
MainToolbarSizes=16,22,32,48
SmallDefault=22
SmallSizes=16,22,32,48
PanelDefault=48
PanelSizes=16,22,32,48,64,128,256
DialogDefault=32
DialogSizes=16,22,32,48,64,128,256

# Directory list

#Directories=actions/16,actions/22,actions/32,actions/48,actions/256FIXED,applets/22,apps/16,apps/22,apps/32,apps/48,apps/256FIXED,categories/16,categories/256FIXED,devices/16,devices/32,devices/48,emblems/22,emblems/24,mimetypes/16,mimetypes/64,places/16,places/22,places/32,places/48,places/256FIXED,preferences/16,preferences/48,preferences/256FIXED,status/16,status/22,status/32,apps/256FIXED,categories/256FIXED,places/256FIXED,preferences/256FIXED

Directories=actions/16,actions/22,actions/32,actions/256FIXED,applets/22,apps/16,apps/22,apps/32,apps/48,apps/256FIXED,categories/16,categories/256FIXED,devices/16,devices/32,devices/48,emblems/22,emblems/24,mimetypes/16,mimetypes/64,places/16,places/22,places/32,places/48,places/256FIXED,preferences/16,preferences/256FIXED,status/16,status/22,status/32,apps/256FIXED,categories/256FIXED,places/256FIXED,preferences/256FIXED

# ACTIONS

[actions/16]
Context=Actions
Size=16
Scale=1
MinSize=8
MaxSize=22
Type=Scalable

[actions/22]
Context=Actions
Size=22
Scale=1
MinSize=22
MaxSize=24
Type=Scalable

[actions/32]
Context=Actions
Size=32
Scale=1
MinSize=24
MaxSize=64
Type=Scalable

#[actions/48]
#Context=Actions
#Size=48
#Scale=1
#MinSize=32
#MaxSize=128
#Type=Scalable

[actions/256FIXED]
Size=256
Context=Actions
Type=Fixed

# APPLETS

[applets/22]
Context=Status
Size=22
Scale=1
Type=Scalable
MinSize=16
MaxSize=24

# APPLICATIONS

[apps/16]
Context=Applications
Size=16
Scale=1
Type=Scalable
MinSize=16
MaxSize=22

[apps/22]
Context=Applications
Size=22
Scale=1
Type=Scalable
MinSize=16
MaxSize=24

[apps/32]
Context=Applications
Size=32
Scale=1
Type=Scalable
MinSize=24
MaxSize=48

[apps/48]
Context=Applications
Size=48
Scale=1
Type=Scalable
MinSize=32
MaxSize=256

[apps/256FIXED]
Context=Applications
Size=256
Type=Fixed

# CATEGORIES

[categories/16]
Context=Categories
Size=16
Scale=1
Type=Scalable
MinSize=16
MaxSize=24

[categories/256FIXED]
Context=Categories
Size=256
Type=Fixed

# DEVICES

[devices/16]
Context=Devices
Size=16
Scale=1
Type=Scalable
MinSize=16
MaxSize=24

[devices/32]
Context=Devices
Size=32
Scale=1
Type=Scalable
MinSize=24
MaxSize=48

[devices/48]
Context=Devices
Size=48
Scale=1
Type=Scalable
MinSize=32
MaxSize=256

# EMBLEMS

[emblems/22]
Context=Emblems
Size=22
Scale=1
Type=Scalable
MinSize=8
MaxSize=256

[emblems/24]
Context=Emblems
Size=24
Scale=1
Type=Scalable
MinSize=8
MaxSize=256

# MIMETYPES

[mimetypes/16]
Context=MimeTypes
Size=16
Scale=1
Type=Scalable
MinSize=16
MaxSize=24

[mimetypes/64]
Context=MimeTypes
Size=64
Scale=1
Type=Scalable
MinSize=32
MaxSize=256

# PLACES

[places/16]
Context=Places
Size=16
Scale=1
Type=Scalable
MinSize=8
MaxSize=22

[places/22]
Context=Places
Size=22
Scale=1
Type=Scalable
MinSize=16
MaxSize=24

[places/32]
Context=Places
Size=16
Scale=1
Type=Scalable
MinSize=24
MaxSize=48

[places/48]
Context=Places
Size=48
Scale=1
Type=Scalable
MinSize=32
MaxSize=256

[places/256FIXED]
Context=Places
Size=256
Type=Fixed

# PREFERENCES

[preferences/16]
Context=Applications
Size=16
Scale=1
Type=Scalable
MinSize=8
MaxSize=24

[preferences/48]
Context=Applications
Size=48
Scale=1
Type=Scalable
MinSize=32
MaxSize=256

[preferences/256FIXED]
Context=Applications
Size=256
Type=Fixed

# STATUS

[status/16]
Context=Status
Size=16
Scale=1
Type=Scalable
MinSize=8
MaxSize=22

[status/22]
Context=Status
Size=22
Scale=1
Type=Scalable
MinSize=22
MaxSize=32

[status/32]
Context=Status
Size=32
Scale=1
Type=Scalable
MinSize=24
MaxSize=256
