# My favourite OS theme ever is Windows XP.
# This was later used by Microsoft for Windows ME as well. AFAIK, the only difference is WinME
# didn't support shadows or fading. It used the Win98 "scroll" effect by default.
# Finally, it was used as the base for "Windows Classic" theme in Windows XP.
# There were some minor diffences, the Start Menu button size/icon come to mind.
# Windows Vista/7 had a inaccurate implementation that was a "Software Rendered" port
# however, it didn't use the native engine like XP did so was slower.


ThemeDescription="Windows XP / ME"
ThemeAuthor="PixelOCDGuy, modified by tf and enfaun"
Look="flat"
TaskbuttonIconOffset=5

#DesktopBackgroundColor="#3a/6e/a5"
TaskBarClockLeds=0
TrayDrawBevel=1

TitleButtonsLeft="s"
TitleButtonsRight="xmi"
TitleButtonsSupported="xmis"
TitleBarHeight=19
Gradients="titleAB.xpm titleAT.xpm titleIB.xpm titleIT.xpm separator.xpm buttonI.xpm buttonA.xpm switchbg.xpm dialogbg.xpm"
TitleBarJoinRight=1

BorderSizeX=4
BorderSizeY=4
CornerSizeX=4
CornerSizeY=4
DlgBorderSizeX=4
DlgBorderSizeY=4

ColorNormalButton="#d4d0c8"
ColorNormalButtonText="#000000"
ColorActiveButton="#d4d0c8"
ColorActiveButtonText="#000000"

ColorNormalTitleBarText="#d4d0c8"
ColorActiveTitleBarText="#ffffff"
ColorActiveBorder="#d4d0c8"
ColorInactiveBorder="#d4d0c8"
ColorNormalBorder="#d4d0c8"

ColorDialog="#d4d0c8"
ColorListBox="#ffffff"
ColorListBoxText="#000000"
ColorListBoxSelection="#4d4f7d"
ColorListBoxSelectionText="#ffffff"
ColorScrollBar="#d4d0c8"
ColorScrollBarSlider="#d4d0c8"
ColorScrollBarButton="#d4d0c8"
ColorScrollBarButtonArrow="#000000"
ColorLabel="#d4d0c8"
ColorLabelText="#000000"

ColorNormalMenu="#d4d0c8"
ColorActiveMenuItem="#404040"
ColorNormalMenuItemText="#000000"
ColorActiveMenuItemText="#ffffff"
ColorDisabledMenuItemText="#808080"

ColorDefaultTaskBar="#d4d0c8"
ColorNormalTaskBarApp="#d4d0c8"
ColorNormalTaskBarAppText="#000000"
ColorActiveTaskBarApp="#d4d0c8"
ColorActiveTaskBarAppText="#000000"
ColorMinimizedTaskBarApp="#d4d0c8"
ColorMinimizedTaskBarAppText="#000000"

ColorInput="#ffffff"
ColorInputText="#000000"
ColorClock="#d4d0c8"
ColorClockText="#000000"

ColorToolTip="#ffffe1"
ColorToolTipText="#000000"
ColorMoveSizeStatus="#d4d0c8"
ColorMoveSizeStatusText="#000000"
ColorQuickSwitch="#d4d0c8"
ColorQuickSwitchText="#000000"
ColorQuickSwitchActive="#4d4f7d"

#PreferFreetypeFonts=1

# Font Specification
TitleFontNameXft	   =	"Tahoma:size=8:bold"
MenuFontNameXft	           =    "tahoma:size=8"
MinimizedWindowFontNameXft =    "tahoma:size=8"
ActiveButtonFontNameXft    =    "tahoma:size=8"
NormalButtonFontNameXft    =    "tahoma:size=8"
QuickSwitchFontNameXft     =    "tahoma:size=8:bold"
ListBoxFontNameXft         =    "tahoma:size=8"
StatusFontNameXft          =    "tahoma:size=8"
ToolTipFontNameXft         =    "tahoma:size=8"
ActiveTaskBarFontNameXft   =    "tahoma:size=8:bold"
NormalTaskBarFontNameXft   =    "tahoma:size=8"
ClockFontNameXft           =    "tahoma:size=8"
ApmFontNameXft             =    "tahoma:size=8"
LabelFontNameXft	   =    "tahoma:size=8"
NormalWorkspaceFontNameXft =    "tahoma:size=8"
ActiveWorkspaceFontNameXft =    "tahoma:size=8:bold"

TitleFontName		=	"-cronyx-helvetica-bold-r-normal-*-11-80-100-100-p-46-iso10646-1"
MenuFontName		=	"-cronyx-helvetica-medium-r-normal-*-11-80-100-100-p-46-iso10646-1"
MinimizedWindowFontName	=	"-cronyx-helvetica-medium-r-normal-*-11-80-100-100-p-46-iso10646-1"
ActiveButtonFontName	=	"-cronyx-helvetica-medium-r-normal-*-11-80-100-100-p-46-iso10646-1"
NormalButtonFontName	=	"-cronyx-helvetica-medium-r-normal-*-11-80-100-100-p-46-iso10646-1"
QuickSwitchFontName	=	"-cronyx-helvetica-medium-r-normal-*-11-80-100-100-p-46-iso10646-1"
ListBoxFontName		=	"-cronyx-helvetica-medium-r-normal-*-11-80-100-100-p-46-iso10646-1"
StatusFontName		=	"-cronyx-helvetica-medium-r-normal-*-11-80-100-100-p-46-iso10646-1"
ToolTipFontName		=	"-cronyx-helvetica-medium-r-normal-*-11-80-100-100-p-46-iso10646-1"
ActiveTaskBarFontName	=	"-cronyx-helvetica-medium-r-normal-*-11-80-100-100-p-46-iso10646-1"
NormalTaskBarFontName	=	"-cronyx-helvetica-medium-r-normal-*-11-80-100-100-p-46-iso10646-1"
ClockFontName		=	"-cronyx-helvetica-medium-r-normal-*-11-80-100-100-p-46-iso10646-1"
ApmFontName		=	"-cronyx-helvetica-medium-r-normal-*-11-80-100-100-p-46-iso10646-1"
LabelFontName		=	"-cronyx-helvetica-medium-r-normal-*-11-80-100-100-p-46-iso10646-1"
NormalWorkspaceFontName	=	"-cronyx-helvetica-medium-r-normal-*-11-80-100-100-p-46-iso10646-1"
ActiveWorkspaceFontName	=	"-cronyx-helvetica-medium-r-normal-*-11-80-100-100-p-46-iso10646-1"


MenuButtonIconVertOffset=-1

#[taskbar]
#TaskBarHeight=1
#TaskBarEdgeTop=5
#TaskBarEdgeBottom=5
