#
# Tosh 0.2
#

ThemeDescription="Rhapsody - QTStep - Beige"
ThemeAuthor="Row [david@comunidadnet.org]"

Look=pixmap

TitleBarCentered=1
ShowMenuButtonIcon=1
TaskBarShowStartMenu=0

TitleButtonsSupported="xmris"
TitleButtonsRight="im"
TitleButtonsLeft="x"


TitleBarHeight="19"
BorderSizeX="6"
BorderSizeY="6"
CornerSizeX="23"
CornerSizeY="23"
DlgBorderSizeX="6"
DlgBorderSizeY="6"
ButtonX="16"
ButtonY="19"

ColorDialog="rgb:d4/d0/c8"
ColorActiveBorder="rgb:8a/87/82"
ColorNormalBorder="rgb:d4/d0/c8"

ColorNormalTitleButton="rgb:f0/f0/f0"
ColorNormalTitleButtonText="rgb:00/00/00"
ColorNormalButton="rgb:f0/f0/f0"
ColorNormalButtonText="rgb:00/00/00"
ColorActiveButton="rgb:73/ad/ef"
ColorActiveButtonText="rgb:00/00/00"
ColorActiveTitleBar="rgb:9e/9e/9e"
ColorNormalTitleBar="rgb:d8/d8/d8"
ColorActiveTitleBarText="rgb:00/00/00"
ColorNormalTitleBarText="rgb:00/00/00"
ColorNormalMinimizedWindow="rgb:f0/f0/f0"
ColorNormalMinimizedWindowText="rgb:00/00/00"
ColorActiveMinimizedWindow="rgb:73/ad/ef"
ColorActiveMinimizedWindowText="rgb:00/00/00"

ColorNormalMenu="rgb:d4/d0/c8"
ColorActiveMenuItem="rgb:b1/a9/95"
ColorActiveMenuItemText="rgb:00/00/00"
ColorNormalMenuItemText="rgb:00/00/00"
ColorDisabledMenuItemText="rgb:80/80/80"

ColorMoveSizeStatus="rgb:f0/f0/f0"
ColorMoveSizeStatusText="rgb:00/00/00"

ColorQuickSwitch="rgb:f0/f0/f0"
ColorQuickSwitchText="rgb:00/00/00"

ColorDefaultTaskBar="rgb:d4/d0/c8"
ColorNormalTaskBarApp="rgb:d4/d0/c8"
ColorNormalTaskBarAppText="rgb:00/00/00"
ColorActiveTaskBarApp="rgb:b1/a9/95"
ColorActiveTaskBarAppText="rgb:00/00/00"
ColorMinimizedTaskBarApp="rgb:f0/f0/f0"
ColorMinimizedTaskBarAppText="rgb:00/00/00"

ColorInvisibleTaskBarApp="rgb:80/80/80"
ColorInvisibleTaskBarAppText="rgb:00/00/00"

ColorScrollBar="rgb:d4/d0/c8"
ColorScrollBarArrow="rgb:e1/de/d8"
ColorScrollBarSlider="rgb:e1/de/d8"

ColorListBox="rgb:d4/d0/c8"
ColorListBoxText="rgb:00/00/00"
ColorListBoxSelection="rgb:b1/a9/95"
ColorListBoxSelectionText="rgb:00/00/00"

ColorToolTip="rgb:f0/f0/f0"
ColorToolTipText="rgb:00/00/00"

ColorClock="rgb:f0/f0/f0"
ColorClockText="rgb:00/00/00"

ColorApm="rgb:f0/f0/f0"
ColorApmText="rgb:00/00/00"

ColorLabel="rgb:f0/f0/f0"
ColorLabelText="rgb:00/00/00"

ColorInput="rgb:d4/d0/c8"
ColorInputText="rgb:00/00/00"
ColorInputSelection="rgb:b1/a9/95"
ColorInputSelectionText="rgb:00/00/00"