[Appearance]
color_scheme_path=@GUEST_QT5CT_COLORS@
custom_palette=true
icon_theme=hicolor
standard_dialogs=default
style=kvantum

[Interface]
menus_have_icons=false
dialog_buttons_have_icons=0
underline_shortcut=1
toolbutton_style=4

[Fonts]
general="Sans,8,-1,5,50,0,0,0,0,0"
fixed="Monospace,8,-1,5,50,0,0,0,0,0"
