#
# Tosh 0.2
#

ThemeDescription="NeXTSTEP - QTStep - OpenStep CDPlayer"
ThemeAuthor="Row [david@comunidadnet.org]"

Look=pixmap

TitleBarCentered=1
ShowMenuButtonIcon=1
TaskBarShowStartMenu=0

TitleButtonsSupported="xmris"
TitleButtonsRight="im"
TitleButtonsLeft="x"


TitleBarHeight="19"
BorderSizeX="3"
BorderSizeY="3"
CornerSizeX="3"
CornerSizeY="3"
DlgBorderSizeX="3"
DlgBorderSizeY="3"
ButtonX="16"
ButtonY="19"

ColorDialog="rgb:3b/3b/4c"
ColorActiveBorder="rgb:00/00/00"
ColorNormalBorder="rgb:3b/3b/4c"

ColorNormalTitleButton="rgb:f0/f0/f0"
ColorNormalTitleButtonText="rgb:00/00/00"
ColorNormalButton="rgb:f0/f0/f0"
ColorNormalButtonText="rgb:00/00/00"
ColorActiveButton="rgb:73/ad/ef"
ColorActiveButtonText="rgb:00/00/00"
ColorActiveTitleBar="rgb:00/00/00"
ColorNormalTitleBar="rgb:44/44/44"
ColorActiveTitleBarText="rgb:ff/ff/ff"
ColorNormalTitleBarText="rgb:ff/ff/ff"
ColorNormalMinimizedWindow="rgb:f0/f0/f0"
ColorNormalMinimizedWindowText="rgb:00/00/00"
ColorActiveMinimizedWindow="rgb:73/ad/ef"
ColorActiveMinimizedWindowText="rgb:00/00/00"

ColorNormalMenu="rgb:3b/3b/4c"
ColorActiveMenuItem="rgb:0b/f9/3e"
ColorActiveMenuItemText="rgb:00/00/00"
ColorNormalMenuItemText="rgb:ff/ff/ff"
ColorDisabledMenuItemText="rgb:80/80/80"

ColorMoveSizeStatus="rgb:f0/f0/f0"
ColorMoveSizeStatusText="rgb:00/00/00"

ColorQuickSwitch="rgb:f0/f0/f0"
ColorQuickSwitchText="rgb:00/00/00"

ColorDefaultTaskBar="rgb:3b/3b/4c"
ColorNormalTaskBarApp="rgb:3b/3b/4c"
ColorNormalTaskBarAppText="rgb:00/00/00"
ColorActiveTaskBarApp="rgb:0b/f9/3e"
ColorActiveTaskBarAppText="rgb:00/00/00"
ColorMinimizedTaskBarApp="rgb:f0/f0/f0"
ColorMinimizedTaskBarAppText="rgb:00/00/00"

ColorInvisibleTaskBarApp="rgb:80/80/80"
ColorInvisibleTaskBarAppText="rgb:00/00/00"

ColorScrollBar="rgb:3b/3b/4c"
ColorScrollBarArrow="rgb:76/76/82"
ColorScrollBarSlider="rgb:76/76/82"

ColorListBox="rgb:3b/3b/4c"
ColorListBoxText="rgb:ff/ff/ff"
ColorListBoxSelection="rgb:0b/f9/3e"
ColorListBoxSelectionText="rgb:00/00/00"

ColorToolTip="rgb:f0/f0/f0"
ColorToolTipText="rgb:00/00/00"

ColorClock="rgb:f0/f0/f0"
ColorClockText="rgb:00/00/00"

ColorApm="rgb:f0/f0/f0"
ColorApmText="rgb:00/00/00"

ColorLabel="rgb:f0/f0/f0"
ColorLabelText="rgb:00/00/00"

ColorInput="rgb:3b/3b/4c"
ColorInputText="rgb:ff/ff/ff"
ColorInputSelection="rgb:0b/f9/3e"
ColorInputSelectionText="rgb:00/00/00"