# This theme is based on the FMotif icewm theme designed by Alexander Voigt
# This theme is inspired by the look of the window-manager
#  of the CDE (Common Desktop Environment) 1990-2000 HP-UX Workstations
# Author: Stéphane Lassalvy
# License: LGPL 3
# 2022-10
#
ThemeDescripton = "CDE 'Mustard' theme based on Icewm FMotif Theme by Alexander Voigt and the CDE desktop environment"
ThemeAuthor = "Stéphane Lassalvy"

Look = metal
Gradients="workspacebuttonbg.xpm workspacebuttonactive.xpm menusel.xpm"

TitleButtonsLeft="s"
TitleButtonsRight="mi"
TitleButtonsSupported="sxmihrd"
TitleBarJustify=50

BorderSizeX = 6
BorderSizeY = 6
DlgBorderSizeX = 6
DlgBorderSizeY = 6
TitleBarHeight = 24
TitleBarJustify = 50
TitleButtonsSupported = "xmirs"
CornerSizeX = 6
CornerSizeY = 6
DlgBorderSizeX=6
DlgBorderSizeY=6
ShowMenuButtonIcon = 0
MenuIconSize = 22
CenterTransientsOnOwner=1
TaskBarShowTransientWindows=0

# Fonts
# Name of the title bar font.
#TitleFontName    = "-bitstream-*-medium-*-*-*-*-120-*-*-*-*-*-*"
TitleFontNameXft = "serif:size=12"

# Name of the menu font.
#MenuFontName    = "-bitstream-*-medium-*-*-*-*-80-*-*-*-*-*-*"
MenuFontNameXft = "serif:size=9"

# Name of the status display font.
#StatusFontName    = "-bitstream-*-medium-*-*-*-*-120-*-*-*-*-*-*"
StatusFontNameXft = "serif:size=12:italic"

# Name of the font for Alt+Tab switcher window.
#QuickSwitchFontName    = "-bitstream-*-bold-*-*-*-*-120-*-*-*-*-*-*"
QuickSwitchFontNameXft = "serif:size=12:bold"

# Name of the normal button font.
#NormalButtonFontName    = "-bitstream-*-medium-*-*-*-*-120-*-*-*-*-*-*"
NormalButtonFontNameXft = "serif:size=12"

# Name of the active button font.
#ActiveButtonFontName     = "-bitstream-*-medium-*-*-*-*-120-*-*-*-*-*-*"
ActiveButtonFontNameXft  = "sans:size=12"

# Name of the normal task bar item font.
#NormalTaskBarFontName     = "-bitstream-*-medium-*-*-*-*-120-*-*-*-*-*-*"
NormalTaskBarFontNameXft  = "serif:size=12"

# Name of the active task bar item font.
#ActiveTaskBarFontName    = "-bitstream-*-bold-*-*-*-*-120-*-*-*-*-*-*" 
ActiveTaskBarFontNameXft = "serif:size=12:bold"

# Name of the tool button font (fall
back: NormalButtonFontName).
#ToolButtonFontName    = "-bitstream-*-medium-*-*-*-*-120-*-*-*-*-*-*"
ToolButtonFontNameXft ="sans-serif:size=12"

# Name of the normal workspace button font (fallback: NormalButtonFontName).
#NormalWorkspaceFontName    = "-bitstream-*-medium-*-*-*-*-120-*-*-*-*-*-*"
NormalWorkspaceFontNameXft = "serif:size=12"

# Name of the active workspace button font (fallback: ActiveButtonFontName).
#ActiveWorkspaceFontName = "-bitstream-*-bold-*-*-*-*-120-*-*-*-*-*-*"
ActiveWorkspaceFontNameXft = "serif:size=12:bold"

# Name of the mini-window font.
#MinimizedWindowFontName    = "-bitstream-*-medium-*-*-*-*-120-*-*-*-*-*-*"
MinimizedWindowFontNameXft = "serif:size=12"

#Name of the window list font.
#ListBoxFontName    = "-bitstream-*-medium-*-*-*-*-120-*-*-*-*-*-*"
ListBoxFontNameXft = "serif:size=12"

#Name of the tool tip font.
#ToolTipFontName    = "-bitstream-*-medium-*-*-*-*-120-*-*-*-*-*-*"
ToolTipFontNameXft = "serif:size=10"

#Name of the task bar clock font.
#ClockFontName   = "-bitstream-*-medium-*-*-*-*-140-*-*-*-*-*-*"
ClockFontNameXft = "serif:size=12"

#Name of the task bar temperature font.
#TempFontName    = "-bitstream-*-medium-*-*-*-*-140-*-*-*-*-*-*"
TempFontNameXft = "serif:size=12"

#Name of the task bar battery font.
#ApmFontName    = "-bitstream-*-medium-*-*-*-*-140-*-*-*-*-*-*"
ApmFontNameXft = "monospace:size=12"

#Name of the input field font.
#InputFontName    = "-bitstream-*-medium-*-*-*-*-140-*-*-*-*-*-*"
InputFontNameXft = "serif:size=12"

# Labels
#LabelFontName    = "-bitstream-*-medium-*-*-*-*-140-*-*-*-*-*-*"
LabelFontNameXft = "serif:size=12"

#Place new mini-icons from bottom to top
MiniIconsBottomToTop = 1

# Colors
# Workspace
ColorNormalWorkspaceButton        = "#90a793"
ColorNormalWorkspaceButtonText    = "#000000"
ColorActiveWorkspaceButton        = "#5e9c7b"
ColorActiveWorkspaceButtonText    = "#000000"

# Taskbar
ColorDefaultTaskBar               = "#a4a9aa"
ColorNormalTaskBarApp             = "#a4a9aa"
ColorActiveTaskBarApp             = "#60879e"
ColorActiveTaskBarAppText         = "#000000"
ColorMinimizedTaskBarApp          = "#60879e"
ColorInvisibleTaskBarApp          = "#60879e"

# Buttons
ColorToolButton                   = "#a4a9aa"

ColorNormalButton                 = "#a4a9aa" 
ColorNormalButtonText             = "#000000"
ColorActiveButton                 = "#bec6b7"
ColorActiveButtonText             = "#000000"

# Dialog boxes
ColorDialog                       = "#a4a9aa"

# Menu
ColorNormalMenu                   = "#a4a9aa"
ColorActiveMenuItem               = "#bec6b7"
ColorNormalMenuItemText           = "#000000"
ColorActiveMenuItemText           = "#000000"

# Titlebar
ColorNormalTitleBarText = "#000000"
ColorActiveTitleBarText = "#000000"

# Tarkbar justification
TaskBarJustify="center"

# Bitmask of buttons that raise the window when pressedButtonRaiseMask=1 # [0-255]

# Background centered
DesktopBackgroundCenter = 0

# Background scaled
DesktopBackgroundScaled = 0

# Background Tiled
DesktopBackgroundTiled = 1

# Choose background
DesktopBackgroundImage = ""
DesktopBackgroundColor = ""

# Taskbar height
TrayIconMaxHeight = 32

# Width of APM Monitor
TaskBarApmGraphWidth = 60 # [1-1000]

# Height of taskbar monitoring applets
TaskBarGraphHeight = 32 # [16-1000]

# Clock
ColorClock     = "#a4a9aa"
ColorClockText = "#000000"

#CPU
ColorCPUStatusUser   = "#90a793"
ColorCPUStatusSystem = "#90a793"

# Tooltips
ColorToolTip     = "#90a793"
ColorToolTipText = "#000000"

# Labels
ColorLabel               = "#a4a9aa"
ColorLabelText          = "#000000"

# Keyboard layout
ColorKeyboardLayoutText = “#000000”
