[Icon Theme]
Name=Iris
Comment=Iris, Converted by Gnome-ArtNG 0.7.0
Inherits=Tango,Tango-Blue-Materia,gnome,crystalsvg
Example=folder

Directories=16x16/apps,16x16/actions,32x32/apps,32x32/device,32x32/mimetypes,32x32/status,36x36/animations,scalable/,scalable/actions,scalable/apps,scalable/devices,scalable/emblems,scalable/mimetypes,scalable/places,scalable/status

[16x16/apps]
Size=16
Context=Applications
Type=Fixed

[16x16/actions]
Size=16
Context=Actions
Type=Fixed

[32x32/apps]
Size=32
Context=Applications
Type=Fixed

[32x32/device]
Size=32
Context=Device
Type=Fixed

[32x32/mimetypes]
Size=32
Context=Mimetypes
Type=Fixed

[32x32/status]
Size=32
Context=Status
Type=Fixed

[36x36/animations]
Size=36
Context=Animations
Type=Fixed

[scalable/]
Size=32
Context=TooOldToConvert
Type=Scalable
MinSize=24
MaxSize=256

[scalable/actions]
Size=32
Context=Actions
Type=Scalable
MinSize=24
MaxSize=256

[scalable/apps]
Size=32
Context=Applications
Type=Scalable
MinSize=24
MaxSize=256

[scalable/devices]
Size=32
Context=Devices
Type=Scalable
MinSize=24
MaxSize=256

[scalable/emblems]
Size=32
Context=Emblems
Type=Scalable
MinSize=24
MaxSize=256

[scalable/mimetypes]
Size=32
Context=MimeTypes
Type=Scalable
MinSize=24
MaxSize=256

[scalable/places]
Size=32
Context=Places
Type=Scalable
MinSize=24
MaxSize=256

[scalable/status]
Size=32
Context=Status
Type=Scalable
MinSize=24
MaxSize=256

