;;; doom-base16-theme.el -*- no-byte-compile: t; -*-
(require 'doom-themes)

(defgroup doom-base16-theme nil "Options for doom-base16" :group 'doom-themes)
(defcustom doom-base16-brighter-modeline nil "Vivid modeline" :type 'boolean)
(defcustom doom-base16-brighter-comments nil "Vivid comments" :type 'boolean)
(defcustom doom-base16-comment-bg doom-base16-brighter-comments "Comment bg" :type 'boolean)
(defcustom doom-base16-padded-modeline doom-themes-padded-modeline "Mode-line padding" :type '(choice integer boolean))

(def-doom-theme doom-base16
		"Pure Base16 (dark) — generated by LainCore"
		((bg '("#1f1f1f" nil nil)) (bg-alt '("#242424"))
		 (base0 '("#1f1f1f")) (base1 '("#242424"))
		 (base2 '("#454545")) (base3 '("#6a6a6a"))
		 (base4 '("#cbcbcb")) (base5 '("#d2d4d4"))
		 (base6 '("#f0f0f0")) (base7 '("#ffffff"))
		 (base8 '("#ffffff")) (fg '("#f0f0f0"))
		 (fg-alt '("#cbcbcb")) (grey '("#cbcbcb"))
		 (red '("#dc322f")) (orange '("#cb4b16"))
		 (yellow '("#b58900")) (green '("#4caf50"))
		 (cyan '("#15b8cf")) (blue '("#268bd2"))
		 (magenta '("#a681d6")) (teal cyan) (violet magenta)
		 (dark-blue `(,(doom-darken (car blue) 0.35)))
		 (dark-cyan `(,(doom-darken (car cyan) 0.2)))
		 (highlight blue) (vertical-bar base2)
		 (selection '("#4b6983")) (builtin magenta)
		 (comments
		  (if doom-base16-brighter-comments dark-cyan base3))
		 (doc-comments `(,(doom-lighten (car comments) 0.15)))
		 (constants violet) (functions magenta)
		 (keywords blue) (methods cyan) (operators blue)
		 (type yellow) (strings green) (variables base5)
		 (numbers orange) (region '("#4b6983")) (error red)
		 (warning yellow) (success green) (vc-modified orange)
		 (vc-added green) (vc-deleted red)
		 (-modeline-bright doom-base16-brighter-modeline)
		 (-modeline-pad
		  (when doom-base16-padded-modeline
		    (if (integerp doom-base16-padded-modeline)
			doom-base16-padded-modeline
		      4)))
		 (modeline-fg fg) (modeline-fg-alt base5)
		 (modeline-bg `(,(doom-darken (car bg-alt) 0.15)))
		 (modeline-bg-l `(,(doom-darken (car bg-alt) 0.1)))
		 (modeline-bg-inactive
		  `(,(doom-darken (car bg-alt) 0.05)))
		 (modeline-bg-inactive-l bg-alt))
		(((line-number &override) :foreground base3)
		 ((line-number-current-line &override) :foreground
		  base5)
		 ((region &override) :background region)
		 (font-lock-comment-face :foreground comments
					 :background
					 (when doom-base16-comment-bg
					   (doom-lighten bg 0.05)))
		 (font-lock-doc-face :inherit 'font-lock-comment-face
				     :foreground doc-comments)
		 (mode-line :background modeline-bg :foreground
			    modeline-fg :box
			    (when -modeline-pad
			      `(:line-width ,-modeline-pad :color
					    ,modeline-bg)))
		 (mode-line-inactive :background modeline-bg-inactive
				     :foreground modeline-fg-alt :box
				     (when -modeline-pad
				       `(:line-width ,-modeline-pad
						     :color
						     ,modeline-bg-inactive)))
		 (mode-line-emphasis :foreground highlight)
		 (markdown-markup-face :foreground base5)
		 (markdown-header-face :inherit 'bold :foreground red)
		 ((markdown-code-face &override) :background base1)
		 (css-proprietary-property :foreground orange)
		 (css-property :foreground green)
		 (css-selector :foreground blue)
		 (org-hide :foreground bg)
		 ((org-block &override) :background base1)
		 ((org-block-begin-line &override) :foreground fg-alt
		  :slant 'italic)
		 ((centaur-tabs-unselected &override) :background
		  base2 :foreground base4)
		 ((centaur-tabs-unselected-modified &override)
		  :background base2 :foreground orange)
		 ((tab-line &override) :background base2 :foreground
		  base5)
		 ((tab-line-tab-inactive &override) :background base2
		  :foreground base4 :box nil)
		 ((tab-line-highlight &override) :background selection)
		 (tooltip :background base1 :foreground fg))
		nil)

;; vterm ANSI 0..15 = Base16 (keep 5!=13 like the terminals)
(with-eval-after-load 'vterm
  (custom-set-faces
   `(vterm-color-black          ((t (:foreground "#1f1f1f" :background "#1f1f1f"))))
   `(vterm-color-red            ((t (:foreground "#dc322f" :background "#dc322f"))))
   `(vterm-color-green          ((t (:foreground "#4caf50" :background "#4caf50"))))
   `(vterm-color-yellow         ((t (:foreground "#b58900" :background "#b58900"))))
   `(vterm-color-blue           ((t (:foreground "#268bd2" :background "#268bd2"))))
   `(vterm-color-magenta        ((t (:foreground "#4b6983" :background "#4b6983"))))  ;; 5 = 0F
   `(vterm-color-cyan           ((t (:foreground "#15b8cf" :background "#15b8cf"))))
   `(vterm-color-white          ((t (:foreground "#f0f0f0" :background "#f0f0f0"))))
   `(vterm-color-bright-black   ((t (:foreground "#6a6a6a" :background "#6a6a6a"))))  ;; 8
   `(vterm-color-bright-red     ((t (:foreground "#cb4b16" :background "#cb4b16"))))
   `(vterm-color-bright-green   ((t (:foreground "#242424" :background "#242424"))))  ;; 10
   `(vterm-color-bright-yellow  ((t (:foreground "#454545" :background "#454545"))))  ;; 11
   `(vterm-color-bright-blue    ((t (:foreground "#cbcbcb" :background "#cbcbcb"))))  ;; 12
   `(vterm-color-bright-magenta ((t (:foreground "#a681d6" :background "#a681d6"))))  ;; 13 = 0E
   `(vterm-color-bright-cyan    ((t (:foreground "#d2d4d4" :background "#d2d4d4"))))  ;; 14
   `(vterm-color-bright-white   ((t (:foreground "#ffffff" :background "#ffffff"))))))

(with-eval-after-load 'treemacs
  (add-hook 'treemacs-mode-hook
            (lambda ()
              (hl-line-mode 1)
              (face-remap-add-relative 'default :background "#242424")
              (face-remap-add-relative 'fringe  :background "#242424"))))

(provide 'doom-base16-theme)
;;; end
