[Icon Theme]
Name=Serenity Durrque
Comment=SerenityOS community icon theme (Durrque)
Inherits=Chicago95,hicolor
Directories=16x16,32x32,browser,calculator,pixelpaint,serenity

[16x16]
Size=16
Context=Applications
Type=Fixed
[32x32]
Size=32
Context=Applications
Type=Fixed
[browser]
Size=16
Context=Applications
Type=Fixed
[calculator]
Size=16
Context=Applications
Type=Fixed
[pixelpaint]
Size=16
Context=Applications
Type=Fixed
[serenity]
Size=9
Context=Applications
Type=Fixed
