# honey/.local/share/honey-claude/lib/launch.bash (generated by agents-bots-honey.org)
# Shared body of honey-opus / honey-sonnet / honey-haiku.

honey_claude_path_append() {
    local dir
    for dir in "$@"; do
        [[ -d "$dir" ]] || continue
        case ":$PATH:" in *":$dir:"*) ;; *) PATH="${PATH:+$PATH:}$dir" ;; esac
    done
    export PATH
}

# honey_claude_launch <bot> <model> [--telegram] [claude args...]
honey_claude_launch() {
    local bot="$1" model="$2"
    shift 2
    local name="honey-$bot"
    local agent="honey-$bot-bot"
    local state_dir="$HOME/.claude/channels/telegram-$bot"
    local work_dir="${HONEY_CLAUDE_WORK_ROOT:-$HOME/honey-work}/$bot"
    local telegram=0 arg
    local passthrough=()

    for arg in "$@"; do
        case "$arg" in
            --telegram) telegram=1 ;;
            *) passthrough+=("$arg") ;;
        esac
    done

    # The bot user's own npm prefix (claude, bun), agent Guix profile (node), stowed
    # bin, and this checkout's all/.local/bin (claude-warm for an unstowed agent
    # account); appended, never replacing PATH.
    local repo_bin=""
    [[ -n "${LIB_DIR:-}" ]] && repo_bin="$(cd -- "$LIB_DIR/../../../../../all/.local/bin" 2>/dev/null && pwd || true)"
    honey_claude_path_append "$HOME/.local/bin" "${NPM_CONFIG_PREFIX:-$HOME/.npm-global}/bin" \
        "$HOME/.guix-extra-profiles/agent/agent/bin" ${repo_bin:+"$repo_bin"}

    [[ -d "$work_dir" ]] || {
        printf '%s\n' "$name: refused: working directory $work_dir is missing (see agents-bots-honey.org)" >&2
        return 1
    }
    [[ -f "$work_dir/CLAUDE.md" ]] || {
        printf '%s\n' "$name: refused: $work_dir/CLAUDE.md (the Honey boundary law) is missing" >&2
        return 1
    }
    cd "$work_dir" || return 1

    if [[ "$telegram" -eq 1 ]]; then
        honey_telegram_preflight "$name" "$state_dir" || return 1
    fi
    # Gillean's usage guard (preservation.bash); inert with a reason if it cannot bind.
    honey_claude_preservation_bindings "$name"
    # The OpenRC service finds this supervisor by pid: exec keeps the pid.
    if [[ -n "${XDG_RUNTIME_DIR:-}" && -d "$XDG_RUNTIME_DIR" ]]; then
        printf '%s\n' "$$" > "$XDG_RUNTIME_DIR/$name.pid"
    fi
    if [[ "$telegram" -eq 1 ]]; then
        # acceptEdits (auto) mode: plan mode blocks unattended bot work (as on kikin).
        exec env CLAUDE_WARM_HERDR_AGENT="$agent" TELEGRAM_STATE_DIR="$state_dir" \
            claude-warm --model "$model" --permission-mode acceptEdits \
            --channels plugin:telegram@claude-plugins-official "${passthrough[@]+"${passthrough[@]}"}"
    fi
    exec env CLAUDE_WARM_HERDR_AGENT="$agent" \
        claude-warm --model "$model" "${passthrough[@]+"${passthrough[@]}"}"
}
