# honey/.local/share/honey-claude/lib/preservation.bash (generated by agents-bots-honey.org)
# Gillean's usage guard: kikin's claude-preservation.bash bindings, pointed at her pool.

honey_claude_preservation_bindings() {
    local name="${1:-honey-claude}"
    local account_file="${CLAUDE_WARM_PRESERVATION_ACCOUNT_FILE:-$HOME/.claude.json}"
    local mirror="${HONEY_HELMCORTEX_MIRROR:-$HOME/.local/share/helmcortex/skills-mirror}"
    local account_identity account_digest

    if [[ -n "${CLAUDE_WARM_PRESERVATION_ACCOUNT_HASH:-}" ]]; then
        account_digest="$CLAUDE_WARM_PRESERVATION_ACCOUNT_HASH"
    else
        if ! command -v jq >/dev/null 2>&1 || ! command -v sha256sum >/dev/null 2>&1; then
            printf '%s\n' "$name: usage guard inert: jq and sha256sum are required" >&2
            return 0
        fi
        account_identity="$({ jq -er \
            '.oauthAccount.organizationUuid // .oauthAccount.accountUuid // .oauthAccount.userID // empty' \
            "$account_file" 2>/dev/null || true; } | tr -d '\n')"
        if [[ -z "$account_identity" ]]; then
            printf '%s\n' "$name: usage guard inert: no Claude account identity in $account_file (run claude /login)" >&2
            return 0
        fi
        account_digest="sha256:$(printf '%s' "$account_identity" | sha256sum | awk '{print $1}')"
        unset account_identity
    fi

    export CLAUDE_WARM_PRESERVATION_BRIDGE="${CLAUDE_WARM_PRESERVATION_BRIDGE:-$mirror/FORGE/bin/fleet-preservation}"
    export CLAUDE_WARM_PRESERVATION_BRIDGE_ADAPTER="${CLAUDE_WARM_PRESERVATION_BRIDGE_ADAPTER:-federated_preservation.SshAuthorityTransport}"
    export CLAUDE_WARM_PRESERVATION_AUTHORITY_HOST="${CLAUDE_WARM_PRESERVATION_AUTHORITY_HOST:-kikin}"
    export CLAUDE_WARM_PRESERVATION_AUTHORITY_IDENTITY="${CLAUDE_WARM_PRESERVATION_AUTHORITY_IDENTITY:-kikin-kushi}"
    export CLAUDE_WARM_PRESERVATION_AUTHORITY_EXECUTABLE="${CLAUDE_WARM_PRESERVATION_AUTHORITY_EXECUTABLE:-/home/metsatron/HelmCortex/FORGE/bin/fleet-preservation}"
    export CLAUDE_WARM_PRESERVATION_LEDGER_ROOT="${CLAUDE_WARM_PRESERVATION_LEDGER_ROOT:-/home/metsatron/.local/state/fleet-preservation/claude-gillean}"
    export CLAUDE_WARM_PRESERVATION_TELEMETRY_SOURCE="${CLAUDE_WARM_PRESERVATION_TELEMETRY_SOURCE:-authority:${CLAUDE_WARM_PRESERVATION_AUTHORITY_HOST}}"
    export CLAUDE_WARM_PRESERVATION_TELEMETRY_HOST="${CLAUDE_WARM_PRESERVATION_TELEMETRY_HOST:-honey-metsatron}"
    export CLAUDE_WARM_PRESERVATION_TRANSPORT="${CLAUDE_WARM_PRESERVATION_TRANSPORT:-ssh}"
    export CLAUDE_WARM_PRESERVATION_PROVIDER="${CLAUDE_WARM_PRESERVATION_PROVIDER:-claude}"
    export CLAUDE_WARM_PRESERVATION_ACCOUNT_HASH="$account_digest"
    export CLAUDE_WARM_PRESERVATION_MODEL_POOL="${CLAUDE_WARM_PRESERVATION_MODEL_POOL:-shared-subscription}"
    # Same calibration as kikin: 5 percent per 500k input tokens.
    export CLAUDE_WARM_PRESERVATION_ESTIMATE_PERCENT="${CLAUDE_WARM_PRESERVATION_ESTIMATE_PERCENT:-5}"
    export CLAUDE_WARM_PRESERVATION_ESTIMATE_UNCERTAINTY_PERCENT="${CLAUDE_WARM_PRESERVATION_ESTIMATE_UNCERTAINTY_PERCENT:-1}"
    export CLAUDE_WARM_PRESERVATION_IN_FLIGHT_RESERVE_PERCENT="${CLAUDE_WARM_PRESERVATION_IN_FLIGHT_RESERVE_PERCENT:-0.5}"
    export CLAUDE_WARM_PRESERVATION_CONTROL_RESERVE_PERCENT="${CLAUDE_WARM_PRESERVATION_CONTROL_RESERVE_PERCENT:-0.5}"
    export CLAUDE_WARM_PRESERVATION_PROTECTION_ENABLED="${CLAUDE_WARM_PRESERVATION_PROTECTION_ENABLED:-1}"
    export CLAUDE_WARM_PRESERVATION_NUDGE_ENABLED="${CLAUDE_WARM_PRESERVATION_NUDGE_ENABLED:-0}"
}
