# honey/.local/share/honey-claude/lib/telegram-preflight.bash (generated by agents-bots-honey.org)
# Port of kikin's FORGE/bin/lib/claude-telegram-preflight.bash for Honey.
#
# The official Telegram integration is not a daemon: the plugin's .mcp.json
# starts server.ts through Claude Code's MCP stdio client. This preflight
# validates that inline server and reserves the per-token state directory;
# it never daemonizes server.ts or starts an unrelated Telegram service.
# The token itself never lands in a path, a log or the environment.

honey_telegram_preflight() {
    local wrapper_name="${1:-}"
    local state_dir="${2:-}"
    local settings="${CLAUDE_SETTINGS_FILE:-$HOME/.claude/settings.json}"
    local plugin_cache="$HOME/.claude/plugins/cache/claude-plugins-official/telegram"
    local plugin_root="" candidate plugin_command pid pid_command pid_state_dir
    local runtime_root lock_path token_fingerprint

    if [[ ! "$wrapper_name" =~ ^honey-(opus|sonnet|haiku)$ ]]; then
        printf '%s\n' "honey Telegram launch refused: invalid wrapper identity" >&2
        return 1
    fi
    if [[ ! "$state_dir" =~ ^$HOME/\.claude/channels/[a-z0-9-]+$ ]]; then
        printf '%s\n' "$wrapper_name: Telegram launch refused: invalid channel state path" >&2
        return 1
    fi
    command -v jq >/dev/null 2>&1 || {
        printf '%s\n' "$wrapper_name: Telegram launch refused: jq is required for plugin preflight" >&2
        return 1
    }
    [[ -f "$settings" ]] || {
        printf '%s\n' "$wrapper_name: Telegram launch refused: settings are missing at $settings" >&2
        return 1
    }
    jq -e '.enabledPlugins["telegram@claude-plugins-official"] == true' "$settings" >/dev/null 2>&1 || {
        printf '%s\n' "$wrapper_name: Telegram launch refused: Telegram plugin is not enabled in $settings" >&2
        return 1
    }
    [[ -d "$plugin_cache" ]] || {
        printf '%s\n' "$wrapper_name: Telegram launch refused: official Telegram plugin cache is missing" >&2
        return 1
    }
    while IFS= read -r candidate; do
        plugin_root="$candidate"
    done < <(find "$plugin_cache" -mindepth 1 -maxdepth 1 -type d -print 2>/dev/null | sort -V)
    [[ -n "$plugin_root" && -f "$plugin_root/.mcp.json" && -f "$plugin_root/server.ts" ]] || {
        printf '%s\n' "$wrapper_name: Telegram launch refused: no complete official plugin server was found" >&2
        return 1
    }
    plugin_command="$(jq -r '.mcpServers.telegram.command // empty' "$plugin_root/.mcp.json" 2>/dev/null || true)"
    # Plugin 0.0.6 declares a bare "bun"; on Honey bun lives in metsatron's npm prefix.
    if [[ "$plugin_command" != /* ]]; then
        plugin_command="$(command -v -- "$plugin_command" 2>/dev/null || true)"
    fi
    [[ "$plugin_command" = /* && -x "$plugin_command" ]] || {
        printf '%s\n' "$wrapper_name: Telegram launch refused: plugin MCP command is unavailable" >&2
        return 1
    }
    [[ -f "$state_dir/.env" ]] && grep -Eq '^TELEGRAM_BOT_TOKEN=[^[:space:]].*$' "$state_dir/.env" || {
        printf '%s\n' "$wrapper_name: Telegram launch refused: bot token state is missing at $state_dir/.env" >&2
        return 1
    }
    command -v sha256sum >/dev/null 2>&1 || {
        printf '%s\n' "$wrapper_name: Telegram launch refused: sha256sum is required for token locking" >&2
        return 1
    }
    token_fingerprint="$(grep '^TELEGRAM_BOT_TOKEN=' "$state_dir/.env" | sha256sum | awk '{print substr($1,1,16)}')"
    if [[ ! "$token_fingerprint" =~ ^[0-9a-f]{16}$ ]]; then
        printf '%s\n' "$wrapper_name: Telegram launch refused: bot token state could not be fingerprinted" >&2
        return 1
    fi

    # One getUpdates consumer per token: hold a per-token lock across the exec.
    runtime_root="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}/claude-idle-compaction"
    mkdir -p "$runtime_root"
    lock_path="$runtime_root/telegram-token-${token_fingerprint}.launch.lock"
    exec 9>"$lock_path"
    if ! flock -n 9; then
        printf '%s\n' "$wrapper_name: Telegram launch refused: another session owns this bot token" >&2
        return 1
    fi

    # Never kill or replace a live plugin server; a stale pid file is the plugin's to recover.
    if [[ -f "$state_dir/bot.pid" ]]; then
        pid="$(tr -d '[:space:]' < "$state_dir/bot.pid" 2>/dev/null || true)"
        if [[ "$pid" =~ ^[1-9][0-9]*$ && -r "/proc/$pid/cmdline" ]]; then
            pid_command="$(tr '\0' ' ' < "/proc/$pid/cmdline" 2>/dev/null || true)"
            pid_state_dir="$(tr '\0' '\n' < "/proc/$pid/environ" 2>/dev/null \
                | sed -n 's/^TELEGRAM_STATE_DIR=//p' | head -1 || true)"
            if [[ "$pid_state_dir" == "$state_dir" && "$pid_command" == *server.ts* ]]; then
                printf '%s\n' "$wrapper_name: Telegram launch refused: an active inline plugin server already owns $state_dir" >&2
                return 1
            fi
        fi
    fi
    return 0
}
