# This theme is based on the FMotif icewm theme designed by Alexander Voigt
# This theme is inspired by the look of the window-manager
#  of the CDE (Common Desktop Environment) 1990-2000 HP-UX Workstations
# Author: Stéphane Lassalvy
# License: LGPL 3
# 2022-10
#
ThemeDescripton = "CDE 'Sand' theme based on Icewm FMotif Theme by Alexander Voigt and the CDE desktop environment"
ThemeAuthor = "Stéphane Lassalvy"

Look = flat
Gradients="workspacebuttonbg.xpm workspacebuttonactive.xpm menusel.xpm"

TitleButtonsLeft="s"
TitleButtonsRight="mi"
TitleButtonsSupported="sxmihrd"
TitleBarJustify=50

BorderSizeX = 6
BorderSizeY = 6
DlgBorderSizeX = 6
DlgBorderSizeY = 6
TitleBarHeight = 24
TitleBarJustify = 50
TitleButtonsSupported = "xmirs"
CornerSizeX = 6
CornerSizeY = 6
DlgBorderSizeX=6
DlgBorderSizeY=6
ShowMenuButtonIcon = 0
MenuIconSize = 22
CenterTransientsOnOwner=1
TaskBarShowTransientWindows=0

# Fonts
# Name of the title bar font.
#TitleFontName    = "-bitstream-*-medium-*-*-*-*-120-*-*-*-*-*-*"
TitleFontNameXft = "sans:size=12"

# Name of the menu font.
#MenuFontName    = "-bitstream-*-medium-*-*-*-*-80-*-*-*-*-*-*"
MenuFontNameXft = "sans:size=9"

# Name of the status display font.
#StatusFontName    = "-bitstream-*-medium-*-*-*-*-120-*-*-*-*-*-*"
StatusFontNameXft = "sans:size=12:italic"

# Name of the font for Alt+Tab switcher window.
#QuickSwitchFontName    = "-bitstream-*-bold-*-*-*-*-120-*-*-*-*-*-*"
QuickSwitchFontNameXft = "sans:size=12:bold"

# Name of the normal button font.
#NormalButtonFontName    = "-bitstream-*-medium-*-*-*-*-120-*-*-*-*-*-*"
NormalButtonFontNameXft = "sans:size=12"

# Name of the active button font.
#ActiveButtonFontName     = "-bitstream-*-medium-*-*-*-*-120-*-*-*-*-*-*"
ActiveButtonFontNameXft  = "sans:size=12"

# Name of the normal task bar item font.
#NormalTaskBarFontName     = "-bitstream-*-medium-*-*-*-*-120-*-*-*-*-*-*"
NormalTaskBarFontNameXft  = "sans:size=12"

# Name of the active task bar item font.
#ActiveTaskBarFontName    = "-bitstream-*-bold-*-*-*-*-120-*-*-*-*-*-*" 
ActiveTaskBarFontNameXft = "sans:size=12:bold"

# Name of the tool button font (fallback: NormalButtonFontName).
#ToolButtonFontName    = "-bitstream-*-medium-*-*-*-*-120-*-*-*-*-*-*"
ToolButtonFontNameXft ="sans:size=12"

# Name of the normal workspace button font (fallback: NormalButtonFontName).
#NormalWorkspaceFontName    = "-bitstream-*-medium-*-*-*-*-120-*-*-*-*-*-*"
NormalWorkspaceFontNameXft = "sans:size=12"

# Name of the active workspace button font (fallback: ActiveButtonFontName).
#ActiveWorkspaceFontName = "-bitstream-*-bold-*-*-*-*-120-*-*-*-*-*-*"
ActiveWorkspaceFontNameXft = "sans:size=12:bold"

# Name of the mini-window font.
#MinimizedWindowFontName    = "-bitstream-*-medium-*-*-*-*-120-*-*-*-*-*-*"
MinimizedWindowFontNameXft = "sans:size=12"

#Name of the window list font.
#ListBoxFontName    = "-bitstream-*-medium-*-*-*-*-120-*-*-*-*-*-*"
ListBoxFontNameXft = "sans:size=12"

#Name of the tool tip font.
#ToolTipFontName    = "-bitstream-*-medium-*-*-*-*-120-*-*-*-*-*-*"
ToolTipFontNameXft = "sans:size=10"

#Name of the task bar clock font.
#ClockFontName   = "-bitstream-*-medium-*-*-*-*-140-*-*-*-*-*-*"
ClockFontNameXft = "sans:size=12"

#Name of the task bar temperature font.
#TempFontName    = "-bitstream-*-medium-*-*-*-*-140-*-*-*-*-*-*"
TempFontNameXft = "sans:size=12"

#Name of the task bar battery font.
#ApmFontName    = "-bitstream-*-medium-*-*-*-*-140-*-*-*-*-*-*"
ApmFontNameXft = "monospace:size=12"

#Name of the input field font.
#InputFontName    = "-bitstream-*-medium-*-*-*-*-140-*-*-*-*-*-*"
InputFontNameXft = "sans:size=12"

# Labels
#LabelFontName    = "-bitstream-*-medium-*-*-*-*-140-*-*-*-*-*-*"
LabelFontNameXft = "sans:size=12"

#Place new mini-icons from bottom to top
MiniIconsBottomToTop = 1

# Colors
# Workspace
ColorNormalWorkspaceButton        = "#90a793"
ColorNormalWorkspaceButtonText    = "#ffffff"
ColorActiveWorkspaceButton        = "#5e9c7b"
ColorActiveWorkspaceButtonText    = "#ffffff"

# Taskbar
ColorDefaultTaskBar               = "#93abbe"
ColorNormalTaskBarApp             = "#93abbe"
ColorActiveTaskBarApp             = "#97a692"
ColorActiveTaskBarAppText         = "#000000"
ColorMinimizedTaskBarApp          = "#a0b2c7"
ColorInvisibleTaskBarApp          = "#c5b2a8"

# Buttons
ColorToolButton                   = "#93abbe"

ColorNormalButton                 = "#93abbe" 
ColorNormalButtonText             = "#000000"
ColorActiveButton                 = "#90a793"
ColorActiveButtonText             = "#000000"

# Dialog boxes
ColorDialog                       = "#93abbe"

# Menu
ColorNormalMenu                   = "#93abbe"
ColorActiveMenuItem               = "#b3aa94"
ColorNormalMenuItemText           = "#ffffff"
ColorActiveMenuItemText           = "#ffffff"

# Titlebar
ColorNormalTitleBarText = "#000000"
ColorActiveTitleBarText = "#ffffff"

# Tarkbar justification
TaskBarJustify="center"

# Bitmask of buttons that raise the window when pressedButtonRaiseMask=1 # [0-255]

# Background centered
DesktopBackgroundCenter = 0

# Background scaled
DesktopBackgroundScaled = 0

# Background Tiled
DesktopBackgroundTiled = 1

# Choose background
DesktopBackgroundImage = "~/.icewm/themes/nIceCDE.Mustard/backgrounds/Sprinkles_sand.xpm"
DesktopBackgroundColor = ""

# Taskbar height
TrayIconMaxHeight = 32

# Width of APM Monitor
TaskBarApmGraphWidth = 60 # [1-1000]

# Height of taskbar monitoring applets
TaskBarGraphHeight = 32 # [16-1000]

# Clock
ColorClock     = "#93abbe"
ColorClockText = "#000000"

#CPU
ColorCPUStatusUser   = "#93abbe"
ColorCPUStatusSystem = "#93abbe"

# Tooltips
ColorToolTip     = "#b6aea9"
ColorToolTipText = "#000000"

# Labels
ColorLabel              = "#93abbe"
ColorLabelText          = "#000000"

# Keyboard layout
ColorKeyboardLayoutText = “#000000”
