[Icon Theme]
Name=KDE 1 Classic Silver with Mac OS 9 Folder
Comment=KDE Classic Silver with the native Platinum9 folder graft.
Inherits=KDE-1-Classic-Silver-Original,KDE-Classic,Chicago95,hicolor
Directories=16x16/places,22x22/places,24x24/places,32x32/places,48x48/places

[16x16/places]
Size=16
Context=Places
Type=Threshold

[22x22/places]
Size=22
Context=Places
Type=Threshold

[24x24/places]
Size=24
Context=Places
Type=Threshold

[32x32/places]
Size=32
Context=Places
Type=Threshold

[48x48/places]
Size=48
Context=Places
Type=Threshold
