[Icon Theme]
Name=KDE 1 Classic Silver MacOS
Name[ast]=KDE-Clásicu
Name[bg]=Класическа KDE
Name[br]=KDE-Classic
Name[bs]=KDE-Klasični
Name[ca]=KDE-Clàssic
Name[ca@valencia]=KDE-Clàssic
Name[cs]=Klasický
Name[cy]=Clasurol KDE
Name[da]=KDE-Classic
Name[de]=KDE-Classic
Name[el]=KDE-Classic
Name[en_GB]=KDE-Classic
Name[eo]=KDE-klasika
Name[es]=KDE-Clásico
Name[et]=KDE klassikaline
Name[eu]=KDE-Klasikoa
Name[fa]=KDE کلاسیک
Name[fi]=Klassinen KDE
Name[fr]=KDE Classique
Name[fy]=KDE-klassyk
Name[ga]=KDE Clasaiceach
Name[gl]=KDE-Clásico
Name[he]=קלסי של KDE
Name[hne]=केडीई-क्लासिक
Name[hu]=KDE-Classic
Name[is]=KDE-klassíkt
Name[it]=Classico di KDE
Name[ja]=KDE クラシック
Name[kk]=Классикалық KDE
Name[ko]=KDE 고전
Name[lt]=KDE-Klasika
Name[lv]=KDE klasiskā
Name[mk]=KDE-Класик
Name[ml]=കെഡിഇ-നിത്യഹരിതം
Name[mr]=केडीई क्लासिक
Name[ms]=KDE-Klasik
Name[nb]=KDE-Klassisk
Name[nds]=KDE-Classic
Name[ne]=पुरानो-केडीई
Name[nl]=KDE-klassiek
Name[nn]=Klassisk KDE
Name[pa]=KDE-ਟਕਸਾਲੀ
Name[pl]=Klasyczny KDE
Name[pt]=KDE-Clássico
Name[pt_BR]=KDE clássico
Name[ro]=KDE Clasic
Name[ru]=Классика KDE
Name[sk]=KDE - klasická
Name[sl]=KDE - Klasično
Name[sq]=KDE-Classic
Name[sr]=Класични КДЕ
Name[sr@ijekavian]=Класични КДЕ
Name[sr@ijekavianlatin]=Klasični KDE
Name[sr@latin]=Klasični KDE
Name[sv]=KDE klassisk
Name[ta]=KDE-பழைய
Name[tg]=Классика
Name[th]=KDE แบบคลาสสิค
Name[tr]=Klasik KDE
Name[ug]=KDE
Name[uk]=Класичний KDE
Name[uz]=KDE klassika
Name[uz@cyrillic]=KDE классика
Name[vi]=KDE-Truyền thống
Name[xh]=KDE-Endala
Name[x-test]=xxKDE-Classicxx
Name[zh_CN]=KDE 经典
Name[zh_TW]=KDE-古典
Comment=KDE Classic Silver with native Platinum9 folders and trash.
Comment[ast]=Tema d'iconos KDE clásicu
Comment[bg]=Класическата тема с икони за KDE
Comment[br]=Giz arlun da gustum evit KDE
Comment[bs]=KDE Klasična tema ikona
Comment[ca]=Tema d'icones KDE clàssic
Comment[ca@valencia]=Tema d'icones KDE clàssic
Comment[cs]=Klasický motiv ikon KDE
Comment[cy]=Thema Eicon Clasurol KDE
Comment[da]=KDE's klassiske ikontema
Comment[de]=Symboldesign KDE-Classic
Comment[el]=Κλασικό θέμα εικονιδίων του KDE
Comment[en_GB]=KDE Classic Icon Theme
Comment[eo]=KDE klasika piktogrametoso
Comment[es]=Tema de iconos KDE clásico
Comment[et]=KDE klassikaline ikooniteema
Comment[eu]=KDE-ren ikono gai klasikoa
Comment[fa]=چهره شمایل KDE کلاسیک
Comment[fi]=Klassisen KDE:n kuvaketeema
Comment[fr]=Thème d'icônes « KDE Classique »
Comment[fy]=It klassike KDE-piktogramtema
Comment[ga]=Téama Deilbhíní Clasaiceach KDE
Comment[gl]=As iconas clásicas de KDE
Comment[he]=ערכת סמלים קלסית של KDE
Comment[hne]=केडीई क्लासिक चिनहा प्रसंग
Comment[hr]=Klasična tema ikona KDE-a
Comment[hu]=Hagyományos KDE-s ikontéma
Comment[is]=KDE Klassískt táknmyndaþema
Comment[it]=Il tema di KDE con icone classiche
Comment[ja]=KDE クラシックアイコンテーマ
Comment[kk]=Классикалық KDE таңбашаларының нақышы
Comment[ko]=KDE 고전 아이콘 테마
Comment[lt]=KDE klasikinių piktogramų tema
Comment[lv]=Klasiskā KDE ikonu tēma
Comment[mk]=Класична тема за икони во KDE
Comment[ml]=കെഡിഇ നിത്യഹരിത ചിഹ്ന പ്രമേയം
Comment[ms]=Tema Ikon Klasik KDE
Comment[nb]=KDE Klassisk ikontema
Comment[nds]=Dat klass'sche Lüttbildmuster vun KDE
Comment[ne]=केडीईको पुरानो प्रतिमा विषयवस्तु
Comment[nl]=Het klassieke KDE-pictogramthema
Comment[nn]=Klassisk KDE-ikontema
Comment[pa]=KDE ਟਕਸਾਲੀ ਆਈਕਾਨ ਸਰੂਪ
Comment[pl]=Klasyczny motyw ikon KDE
Comment[pt]=Tema de Ícones Clássico do KDE
Comment[pt_BR]=Tema de ícones clássico do KDE
Comment[ro]=Tematică de pictograme KDE clasică
Comment[ru]=Классический набор значков для KDE
Comment[sk]=Klasická ikonová téma KDE
Comment[sl]=Tema klasičnih ikon KDE
Comment[sq]=KDE Classic Temë Ikonash
Comment[sr]=Класична КДЕ‑ова тема икона
Comment[sr@ijekavian]=Класична КДЕ‑ова тема икона
Comment[sr@ijekavianlatin]=Klasična KDE‑ova tema ikona
Comment[sr@latin]=Klasična KDE‑ova tema ikona
Comment[sv]=Klassiskt KDE-ikontema
Comment[ta]=KDE பழைய சின்ன பொருள்
Comment[tg]=Мавзӯъи классикии пиктограммаи KDE
Comment[th]=ชุดไอคอน KDE แบบดั้งเดิม ได้ความคลาสสิคสำหรับผู้คุ้นเคย
Comment[tr]=KDE Klasik Simge Teması
Comment[uk]=Класична тема піктограм KDE
Comment[uz]=KDE klassik nishonchalar mavzusi
Comment[uz@cyrillic]=KDE классик нишончалар мавзуси
Comment[vi]=Sắc thái Biểu tượng Truyền thống KDE
Comment[xh]=Umxholo Wephawu lomfanekiso We KDE Wakudala
Comment[x-test]=xxKDE Classic Icon Themexx
Comment[zh_CN]=KDE 经典图标主题
Comment[zh_TW]=KDE 古典圖示主題
DisplayDepth=32
Inherits=hicolor
Example=exec
LinkOverlay=link
LockOverlay=lockoverlay
ZipOverlay=zip
DesktopDefault=32
DesktopSizes=16,32,48,64
ToolbarDefault=22
ToolbarSizes=16,22,32
MainToolbarDefault=22
MainToolbarSizes=16,22,32
SmallDefault=16
SmallSizes=16
PanelDefault=32
PanelSizes=16,32,48
Directories=8x8/emblems,16x16/actions,16x16/apps,16x16/categories,16x16/devices,16x16/emblems,16x16/filesystems,16x16/mimetypes,16x16/places,22x22/actions,22x22/animations,22x22/apps,22x22/categories,22x22/devices,22x22/emblems,22x22/filesystems,22x22/mimetypes,22x22/places,24x24/actions,24x24/animations,24x24/apps,24x24/categories,24x24/devices,24x24/emblems,24x24/filesystems,24x24/mimetypes,24x24/places,32x32/actions,32x32/animations,32x32/apps,32x32/categories,32x32/devices,32x32/emblems,32x32/filesystems,32x32/mimetypes,32x32/places,48x48/actions,48x48/apps,48x48/categories,48x48/devices,48x48/filesystems,48x48/mimetypes,48x48/places,64x64/apps,64x64/filesystems,64x64/mimetypes,64x64/places
[16x16/actions]
Size=16
Context=Actions
Type=Threshold
[22x22/actions]
Size=22
Context=Actions
Type=Threshold
[32x32/actions]
Size=32
Context=Actions
Type=Threshold
[16x16/apps]
Size=16
Context=Applications
Type=Threshold
[16x16/devices]
Size=16
Context=Devices
Type=Threshold
[32x32/apps]
Size=32
Context=Applications
Type=Threshold
[32x32/devices]
Size=32
Context=Devices
Type=Threshold
[16x16/filesystems]
Size=16
Context=FileSystems
Type=Threshold
[32x32/filesystems]
Size=32
Context=FileSystems
Type=Threshold
[16x16/mimetypes]
Size=16
Context=MimeTypes
Type=Threshold
[32x32/mimetypes]
Size=32
Context=MimeTypes
Type=Threshold
[48x48/apps]
Size=48
Context=Applications
Type=Threshold
[48x48/devices]
Size=48
Context=Devices
Type=Threshold
[48x48/filesystems]
Size=48
Context=FileSystems
Type=Threshold
[48x48/mimetypes]
Size=48
Context=MimeTypes
Type=Threshold
[64x64/mimetypes]
Size=64
Context=MimeTypes
Type=Threshold
[64x64/filesystems]
Size=64
Context=FileSystems
Type=Threshold
[64x64/apps]
Size=64
Context=Applications
Type=Threshold
[16x16/places]
Size=16
Context=Places
Type=Threshold
[22x22/places]
Size=22
Context=Places
Type=Threshold
[32x32/places]
Size=32
Context=Places
Type=Threshold
[48x48/places]
Size=48
Context=Places
Type=Threshold
[64x64/places]
Size=64
Context=Places
Type=Threshold
[22x22/animations]
Size=22
Context=Animations
Type=Threshold
[32x32/animations]
Size=32
Context=Animations
Type=Threshold
[16x16/categories]
Size=16
Context=Animations
Type=Threshold
[22x22/categories]
Size=22
Context=Animations
Type=Threshold
[32x32/categories]
Size=32
Context=Animations
Type=Threshold
[48x48/categories]
Size=48
Context=Animations
Type=Threshold
[64x64/categories]
Size=64
Context=Animations
Type=Threshold
[scalable/categories]
Size=128
Type=Scalable
MinSize=1
MaxSize=256
Context=FileSystems
[8x8/emblems]
Size=8
Context=Emblems
Type=Threshold
[11x11/emblems]
Size=11
Context=Emblems
Type=Threshold
[16x16/emblems]
Size=16
Context=Emblems
Type=Threshold
[24x24/emblems]
Size=24
Context=Emblems
Type=Threshold
[32x32/emblems]
Size=32
Context=Emblems
Type=Threshold

[22x22/apps]
Size=22
Context=Applications
Type=Threshold

[22x22/devices]
Size=22
Context=Devices
Type=Threshold

[22x22/emblems]
Size=22
Context=Emblems
Type=Threshold

[22x22/filesystems]
Size=22
Context=FileSystems
Type=Threshold

[22x22/mimetypes]
Size=22
Context=MimeTypes
Type=Threshold

[24x24/actions]
Size=24
Context=Actions
Type=Threshold

[24x24/animations]
Size=24
Context=Animations
Type=Threshold

[24x24/apps]
Size=24
Context=Applications
Type=Threshold

[24x24/categories]
Size=24
Context=Categories
Type=Threshold

[24x24/devices]
Size=24
Context=Devices
Type=Threshold

[24x24/filesystems]
Size=24
Context=FileSystems
Type=Threshold

[24x24/mimetypes]
Size=24
Context=MimeTypes
Type=Threshold

[24x24/places]
Size=24
Context=Places
Type=Threshold

[48x48/actions]
Size=48
Context=Actions
Type=Threshold
