#
# Tosh 0.2
#

ThemeDescription="Highlights - QTStep - Industrial"
ThemeAuthor="Row [david@comunidadnet.org]"

Look=pixmap

TitleBarCentered=1
ShowMenuButtonIcon=1
TaskBarShowStartMenu=0

TitleButtonsSupported="xmris"
TitleButtonsRight="im"
TitleButtonsLeft="x"


TitleBarHeight="19"
BorderSizeX="6"
BorderSizeY="6"
CornerSizeX="23"
CornerSizeY="23"
DlgBorderSizeX="6"
DlgBorderSizeY="6"
ButtonX="16"
ButtonY="19"

ColorDialog="rgb:00/00/00"
ColorActiveBorder="rgb:00/00/00"
ColorNormalBorder="rgb:00/00/00"

ColorNormalTitleButton="rgb:f0/f0/f0"
ColorNormalTitleButtonText="rgb:00/00/00"
ColorNormalButton="rgb:f0/f0/f0"
ColorNormalButtonText="rgb:00/00/00"
ColorActiveButton="rgb:73/ad/ef"
ColorActiveButtonText="rgb:00/00/00"
ColorActiveTitleBar="rgb:9e/9e/9e"
ColorNormalTitleBar="rgb:d8/d8/d8"
ColorActiveTitleBarText="rgb:00/00/00"
ColorNormalTitleBarText="rgb:00/00/00"
ColorNormalMinimizedWindow="rgb:f0/f0/f0"
ColorNormalMinimizedWindowText="rgb:00/00/00"
ColorActiveMinimizedWindow="rgb:73/ad/ef"
ColorActiveMinimizedWindowText="rgb:00/00/00"

ColorNormalMenu="rgb:00/00/00"
ColorActiveMenuItem="rgb:69/6d/6f"
ColorActiveMenuItemText="rgb:ff/ff/ff"
ColorNormalMenuItemText="rgb:ff/ff/ff"
ColorDisabledMenuItemText="rgb:80/80/80"

ColorMoveSizeStatus="rgb:f0/f0/f0"
ColorMoveSizeStatusText="rgb:00/00/00"

ColorQuickSwitch="rgb:f0/f0/f0"
ColorQuickSwitchText="rgb:00/00/00"

ColorDefaultTaskBar="rgb:00/00/00"
ColorNormalTaskBarApp="rgb:00/00/00"
ColorNormalTaskBarAppText="rgb:00/00/00"
ColorActiveTaskBarApp="rgb:69/6d/6f"
ColorActiveTaskBarAppText="rgb:ff/ff/ff"
ColorMinimizedTaskBarApp="rgb:f0/f0/f0"
ColorMinimizedTaskBarAppText="rgb:00/00/00"

ColorInvisibleTaskBarApp="rgb:80/80/80"
ColorInvisibleTaskBarAppText="rgb:00/00/00"

ColorScrollBar="rgb:00/00/00"
ColorScrollBarArrow="rgb:4c/4c/4c"
ColorScrollBarSlider="rgb:69/6d/6f"

ColorListBox="rgb:00/00/00"
ColorListBoxText="rgb:ff/ff/ff"
ColorListBoxSelection="rgb:69/6d/6f"
ColorListBoxSelectionText="rgb:ff/ff/ff"

ColorToolTip="rgb:f0/f0/f0"
ColorToolTipText="rgb:00/00/00"

ColorClock="rgb:f0/f0/f0"
ColorClockText="rgb:00/00/00"

ColorApm="rgb:f0/f0/f0"
ColorApmText="rgb:00/00/00"

ColorLabel="rgb:f0/f0/f0"
ColorLabelText="rgb:00/00/00"

ColorInput="rgb:00/00/00"
ColorInputText="rgb:ff/ff/ff"
ColorInputSelection="rgb:69/6d/6f"
ColorInputSelectionText="rgb:ff/ff/ff"