# This theme is a modification of the Windows 2000 / ME theme
# by PixelOCDGuy (https://www.box-look.org/p/1648821). The icons were
# sourced from the Chicago95 theme (https://github.com/grassmunk/Chicago95)
# The Tux Start button was sourced from screenshots of FVWM95.

ThemeDescription="Serenity"
ThemeAuthor=bongo
Look="flat"

DesktopBackgroundColor="rgb:00/80/80"
TaskBarClockLeds=0
TrayDrawBevel=1
TaskbuttonIconOffset=5

TitleButtonsLeft="s"
TitleButtonsRight="xmi"
TitleButtonsSupported="xmis"
TitleBarHeight=18

TitleBarJoinRight=1

BorderSizeX=4
BorderSizeY=4
CornerSizeX=24
CornerSizeY=24
DlgBorderSizeX=3
DlgBorderSizeY=3

ColorNormalButton="rgb:D4/D0/C8"
ColorNormalButtonText="rgb:00/00/00"
ColorActiveButton="rgb:D4/D0/C8"
ColorActiveButtonText="rgb:00/00/00"

ColorNormalTitleBarText="rgb:D4/D0/C8"
ColorActiveTitleBarText="rgb:ff/ff/ff"
ColorActiveBorder="rgb:D4/D0/C8"
ColorNormalBorder="rgb:D4/D0/C8"
ColorNormalTitleBar="rgb:80/80/80"
ColorActiveTitleBar="rgb:6E/22/09"

ColorDialog="rgb:D4/D0/C8"
ColorListBox="rgb:ff/ff/ff"
ColorListBoxText="rgb:00/00/00"
ColorListBoxSelection="rgb:6E/22/09"
ColorListBoxSelectionText="rgb:ff/ff/ff"
ColorScrollBar="rgb:D4/D0/C8"
ColorScrollBarSlider="rgb:D4/D0/C8"
ColorScrollBarButton="rgb:D4/D0/C8"
ColorScrollBarButtonArrow="rgb:00/00/00"
ColorLabel="rgb:D4/D0/C8"
ColorLabelText="rgb:00/00/00"

ColorNormalMenu="rgb:D4/D0/C8"
ColorActiveMenuItem="rgb:D2/C0/B6"
ColorNormalMenuItemText="rgb:00/00/00"
ColorActiveMenuItemText="rgb:00/00/00"
ColorDisabledMenuItemText="rgb:80/80/80"

ColorDefaultTaskBar="rgb:D4/D0/C8"
ColorNormalTaskBarApp="rgb:D4/D0/C8"
ColorNormalTaskBarAppText="rgb:00/00/00"
ColorActiveTaskBarApp="rgb:ea/e8/e4"
ColorActiveTaskBarAppText="rgb:00/00/00"
ColorMinimizedTaskBarApp="rgb:D4/D0/C8"
ColorMinimizedTaskBarAppText="rgb:00/00/00"

ColorInput="rgb:ff/ff/ff"
ColorInputText="rgb:00/00/00"
ColorClock="rgb:D4/D0/C8"
ColorClockText="rgb:00/00/00"

ColorToolTip="rgb:ff/ff/e1"
ColorToolTipText="rgb:00/00/00"
ColorMoveSizeStatus="rgb:D4/D0/C8"
ColorMoveSizeStatusText="rgb:00/00/00"
ColorQuickSwitch="rgb:D4/D0/C8"
ColorQuickSwitchText="rgb:00/00/00"

# Font Specification
# Please refer to the font instructions in the extras folder if you want
# a more authentic-looking font. Otherwise, modify the values below
# to a font of your choice.
TitleFontNameXft	   = 	"Tahoma8pt:size=8:bold"
MenuFontNameXft	           =    "Tahoma8pt:size=8"
MinimizedWindowFontNameXft =    "Tahoma8pt:size=8"
ActiveButtonFontNameXft    =    "Tahoma8pt:size=8"
NormalButtonFontNameXft    =    "Tahoma8pt:size=8"
QuickSwitchFontNameXft     =    "Tahoma8pt:size=8"
ListBoxFontNameXft         =    "Tahoma8pt:size=8"
StatusFontNameXft          =    "Tahoma8pt:size=8"
ToolTipFontNameXft         =    "Tahoma8pt:size=8"
ActiveTaskBarFontNameXft   =    "Tahoma8pt:size=8:bold"
NormalTaskBarFontNameXft   =    "Tahoma8pt:size=8"
ClockFontNameXft           =    "Tahoma8pt:size=8"
ApmFontNameXft             =    "Tahoma8pt:size=8"
LabelFontNameXft             =    "Tahoma8pt:size=8"
