ThemeAuthor="J.S."
ThemeDescription="Beish"
Look=metal

TitleBarHeight=24
TitleBarHorzOffset=0
TitleBarVertOffset=-1
TitleBarCentered=1
TitleButtonsSupported="xmis"

TitleButtonsLeft="xmi"
TitleButtonsRight=""

ShowMenuButtonIcon=0

MoveSizeDimLines=1

BorderSizeX=4
BorderSizeY=4
CornerSizeX=19
CornerSizeY=19
DlgBorderSizeX=4
DlgBorderSizeY=4
ConsiderHorizBorder=1
ConsiderVertBorder=1

TitleFontNameXft="tahoma:size=8:bold"
#TitleFontName="-*-tahoma-*-r-*-*-11-*-*-*-*-*-koi8-r"
MenuFontNameXft="tahoma:size=8"
ClockFontNameXft="helvetica:size=8:bold"
#NormalTaskBarFontName="-*-Tahoma-*-r-*-*-11-*-*-*-*-*-*-*"
#ActiveTaskBarFontName="-*-Tahoma-*-r-*-*-11-*-*-*-*-*-*-*"
QuickSwitchFontNameXft="tahoma:size=8:bold"
#ListBoxFontName="-*-Tahoma-*-r-*-*-11-*-*-*-*-*-*-*"
#StatusFontName="-*-Tahoma-*-r-*-*-11-*-*-*-*-*-*-*"
#NormalButtonFontName="-*-Tahoma-*-r-*-*-11-*-*-*-*-*-*-*"
#ActiveButtonFontName="-*-Tahoma-*-r-*-*-11-*-*-*-*-*-*-*"
ApmFontNameXft="monospace:size=6"
MinimizedWindowFontNameXft="tahoma:size=8"
ToolButtonFontNameXft="sans-serif:size=8"
ActiveTaskBarFontNameXft="tahoma:size=8"
NormalTaskBarFontNameXft="tahoma:size=8"

#DesktopBackgroundCenter=1 # 0/1
DesktopBackgroundColor="rgb:74/80/93"
#DesktopBackgroundI`mage="bcg.xpm"

ColorNormalBorder="rgb:DD/DD/DD"
ColorActiveBorder="rgb:DD/DD/DD"
ColorActiveTitleBar="rgb:CC/CC/CC"
ColorNormalTitleBar="rgb:CC/CC/CC"
ColorNormalButton="#dedede"
ColorActiveButton="#e0e0e0"
ColorNormalTitleBarText="rgb:00/00/00"
ColorActiveTitleBarText=#000000
ColorNormalMenu="#e7e7e7"
ColorActiveMenuItem="#000000"
ColorNormalMenuItemText="rgb:00/00/00"
ColorActiveMenuItemText="#FFFFFF"
ColorDisabledMenuItemText="#888888"
ColorMoveSizeStatus="rgb:DD/DD/DD"
ColorMoveSizeStatusText="rgb:00/00/00"
ColorDefaultTaskBar="#e7e7e7"
ColorNormalTaskBarApp="#e7e7e7"
ColorNormalTaskBarAppText="#000000"
ColorActiveTaskBarApp="#e2e2e2"
ColorActiveTaskBarAppText="#000000"
ColorMinimizedTaskBarApp="#dedede"
ColorMinimizedTaskBarAppText="#000000"
ColorListBox="#dedede"
ColorListBoxText=#000000
ColorListBoxSelection=#588090
ColorListBoxSelectionText=#c0c088
ColorNetReceive="rgb:a5/7b/c2"
ColorNetSend="rgb:70/54/83"
ColorCPUStatusSystem="rgb:69/69/a4"
ColorCPUStatusUser="rgb:9c/9c/f5"
ColorLabel="rgb:de/de/de"
ColorInvisibleTaskBarAppText="rgb:74/80/93"
ColorInvisibleTaskBarApp="rgb:d0/d0/d0"
ColorQuickSwitch="rgb:de/de/de"
ColorActiveMinimizedWindow="rgb:ef/ef/ef"
ColorDialog="rgb:de/de/de"
