# T480s exports — add one line per client
/home/metsatron   t480(rw,sync,no_subtree_check,no_root_squash)
/home/metsatron   x230(rw,sync,no_subtree_check,no_root_squash)
/home/metsatron   t1700(rw,sync,no_subtree_check,no_root_squash)
