;; Auto-generated by guix-apply-pull-url on 20250925-171155
;; Mirror chosen: https://mirror.git.savannah.gnu.org/r/guix.git
(list
  (channel
    (name 'guix)
    (url "https://mirror.git.savannah.gnu.org/r/guix.git")
    (introduction
      (make-channel-introduction
        "9edb3f66fd807b096b48283debdcddccfea34bad"
        (openpgp-fingerprint "BBB0 2DDF 2E8C 26C5 7D28  9DDA 013A 06C9 4F2A E8C4")))))
