# -*- coding: utf-8 -*-
# This file is part of ranger, the console file manager.
# License: GNU GPL version 3, see the file "AUTHORS" for details.
#
# LainCore -- DreamWeave colorscheme for ranger.
# Source of truth: ~/DotCortex/term.org ("Ranger Colorscheme (LainCore)" block).
# Do NOT edit this file directly -- edit term.org and re-tangle with tangle-one.
#
# Palette lineage: style.org's lc/base16 'dreamweaver-cc2017 -- the same base16
# slots already wired into all/.config/kitty/kitty.conf (color0-15) and
# all/.config/rofi/colors/laincore-dreamweave.rasi. ranger/curses addresses
# colors as 256-color pairs, not 24-bit truecolor, so each hex below is mapped
# to the nearest xterm-256 index (216-color cube + greyscale ramp).
#
#   slot    hex        256-idx  role here
#   base00  #1f1f1f    234      bg (left as terminal default in most contexts)
#   base01  #242424    235      panel / alt background (reserved)
#   base02  #454545    238      inactive tab background
#   base03  #6a6a6a    242      muted: plain filenames, inactive pane, cut marker
#   base04  #cbcbcb    251      dim foreground (reserved)
#   base05  #d2d4d4    252      inactive tab foreground
#   base06  #f0f0f0    255      bright foreground (reserved)
#   base07  #ffffff    231      white: tag marker, active tab foreground
#   base08  #dc322f    160      rasi 'urgent': errors, bad links, vcs conflict
#                                (hand-nudged from the raw-nearest 166 so it
#                                 doesn't collide with base09's orange -- the
#                                 256 cube is too coarse to separate them)
#   base09  #cb4b16    166      archives / containers
#   base0A  #b58900    136      marked rows, fifo, device, vcs commit
#   base0B  #4caf50    71       rasi 'active': executables, good hostname/tab,
#                                vcs staged/sync
#   base0C  #15b8cf    38       rasi 'selected': selection bar, links,
#                                permissions-good, progress bar, vcs date
#   base0D  #268bd2    32       directories, vcsinfo, vcs-ahead
#   base0E  #a681d6    140      sockets, other media, vcs-diverged, badinfo
#   base0F  #4b6983    60       reserved (kept for palette completeness)

from __future__ import (absolute_import, division, print_function)

from ranger.gui.colorscheme import ColorScheme
from ranger.gui.color import default, normal, bold, reverse, dim, default_colors

MUTED    = 242  # base03 -- plain filenames / inactive pane / cut marker
WHITE    = 231  # base07
URGENT   = 160  # base08 (hand-nudged, see header)
ORANGE   = 166  # base09
WARN     = 136  # base0A
ACTIVE   = 71   # base0B
ACCENT   = 38   # base0C
DIR_BLUE = 32   # base0D — kept for vcsinfo/titlebar roles
DIR_YELLOW = 221  # folders: canonical #ffcb63 per Mètsàtron's ruling 2026-07-10 (already live in nvim); 221=#ffd75f is the nearest cell ranger's 256-color curses palette can reach
VIOLET   = 140  # base0E
LIGHT_BG = 238  # base02 -- inactive tab background
LIGHT_FG = 252  # base05 -- inactive tab foreground


class Scheme(ColorScheme):
    progress_bar_color = ACCENT

    def use(self, context):  # pylint: disable=too-many-branches,too-many-statements
        fg, bg, attr = default_colors

        if context.reset:
            return default_colors

        elif context.in_browser:
            if context.selected:
                attr |= reverse
                fg = ACCENT
            else:
                attr = normal
                fg = MUTED
            if context.empty or context.error:
                bg = URGENT
            if context.border:
                fg = default
            if context.media:
                fg = WARN if context.image else VIOLET
            if context.container:
                fg = ORANGE
            if context.directory:
                attr |= bold
                fg = DIR_YELLOW
            elif context.executable and not \
                    any((context.media, context.container,
                         context.fifo, context.socket)):
                attr |= bold
                fg = ACTIVE
            if context.socket:
                attr |= bold
                fg = VIOLET
            if context.fifo or context.device:
                fg = WARN
                if context.device:
                    attr |= bold
            if context.link:
                fg = ACCENT if context.good else URGENT
            if context.tag_marker and not context.selected:
                attr |= bold
                fg = WHITE if fg in (URGENT, VIOLET) else URGENT
            if not context.selected:
                if context.copied:
                    attr |= bold
                    fg = WARN
                elif context.cut:
                    attr |= dim
                    fg = MUTED
            if context.main_column:
                if context.selected:
                    attr |= bold
                if context.marked:
                    attr |= bold
                    fg = WARN
            if context.badinfo:
                if attr & reverse:
                    bg = VIOLET
                else:
                    fg = VIOLET
            if context.inactive_pane:
                fg = MUTED

        elif context.in_titlebar:
            if context.hostname:
                fg = URGENT if context.bad else ACTIVE
            elif context.directory:
                fg = DIR_BLUE
            elif context.tab:
                if context.good:
                    bg = ACTIVE
            elif context.link:
                fg = ACCENT
            attr |= bold
            if context.tab and not context.good:
                bg = LIGHT_BG
                fg = LIGHT_FG

        elif context.in_statusbar:
            if context.permissions:
                if context.good:
                    fg = ACCENT
                elif context.bad:
                    fg = URGENT
            if context.marked:
                attr |= bold | reverse
                fg = WARN
            if context.frozen:
                attr |= bold | reverse
                fg = ACCENT
            if context.message:
                if context.bad:
                    attr |= bold
                    fg = URGENT
            if context.loaded:
                bg = self.progress_bar_color
            if context.vcsinfo:
                fg = DIR_BLUE
                attr &= ~bold
            if context.vcscommit:
                fg = WARN
                attr &= ~bold
            if context.vcsdate:
                fg = ACCENT
                attr &= ~bold

        if context.text:
            if context.highlight:
                attr |= reverse

        if context.in_taskview:
            if context.title:
                fg = DIR_BLUE

            if context.selected:
                attr |= reverse

            if context.loaded:
                if context.selected:
                    fg = self.progress_bar_color
                else:
                    bg = self.progress_bar_color

        if context.vcsfile and not context.selected:
            attr &= ~bold
            if context.vcsconflict:
                fg = VIOLET
            elif context.vcsuntracked:
                fg = ACCENT
            elif context.vcschanged:
                fg = URGENT
            elif context.vcsunknown:
                fg = URGENT
            elif context.vcsstaged:
                fg = ACTIVE
            elif context.vcssync:
                fg = ACTIVE
            elif context.vcsignored:
                fg = default

        elif context.vcsremote and not context.selected:
            attr &= ~bold
            if context.vcssync or context.vcsnone:
                fg = ACTIVE
            elif context.vcsbehind:
                fg = URGENT
            elif context.vcsahead:
                fg = DIR_BLUE
            elif context.vcsdiverged:
                fg = VIOLET
            elif context.vcsunknown:
                fg = URGENT

        return fg, bg, attr
