# Termux shell configuration
# https://wiki.termux.com/wiki/Terminal_Settings

# Bell notification
bell=vibrate

# Close keyboard after return in shell
back-key=back

# Extra keys row
extra-keys = [['ESC','|','/','~','`'],['TAB','CTRL','ALT','DEL']]

# Cursor/bell/IME handling
cursor-blink-rate=500

# Use black background
use-black-ui=true
